#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20160312

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=bully
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://github.com/aanarchyy/$PRGNAM
	RAMA=`curl -s $WEB/releases|grep .tar.gz|head -1|cut -d / -f5|cut -d t -f-1|sed 's/.$//g'`
	VERSION=`echo ${RAMA}_"$(curl -s $WEB|grep commit/|head -1|cut -d / -f5|cut -c1-7)"`
}

F_download(){
echo 
echo "$VERDE"Clonando git ..."$CIERRE"
sleep 1
cd $TMP
git clone $WEB
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1
cd $TMP/$PRGNAM/src
sed -i 's,/local,,g' Makefile
make
make install DESTDIR=$PKG
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
F_download
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales