#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20160211

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=crunch
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://sourceforge.net/projects/crunch-wordlist/files/crunch-wordlist/
	VERSION=$(curl -s $WEB|grep -E *\.tgz|awk '{print $1}'|sed -e 's/\(<[^<][^<]*>\)//g'|grep crunch-| head -1|sed 's/.tgz//g'|cut -d- -f2)
	EXTENSION=tgz
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	DOWNLOAD=$WEB/$SOURCES
}


# Descomprimimos el fichero descargado y compilamos
F_compilar(){
mkdir -p $PKG/usr/{bin,share/crunch}
make  || exit 1
mv -f crunch $PKG/usr/bin
mv -f charset.lst $PKG/usr/share/crunch
mv -f unicode_test.lst $PKG/usr/share/crunch
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales