#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20151024

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	WEB=http://sourceforge.net/projects/crunch-wordlist/files/crunch-wordlist/
	SOURCES=$(curl -s $WEB | grep -E *\.tgz |awk '{print $1}'| sed -e 's/\(<[^<][^<]*>\)//g' | grep crunch- | head -1)
	VERSION=$(echo $SOURCES | sed 's/.tgz//g' | cut -d- -f2)
	PRGNAM=crunch
	echo -ne "\033]2;${PRGNAM}_updater\007"
	DOWNLOAD=$WEB/$SOURCES
}

# Creamos directorios extra
F_extradirs(){
mkdir -p $PKG/usr/{bin,share/crunch}
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
tar -xvf $SOURCES
cd crunch-$VERSION
make  || exit 1
mv -f crunch $PKG/usr/bin
mv -f charset.lst $PKG/usr/share/crunch
mv -f unicode_test.lst $PKG/usr/share/crunch
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
# Creamos directorios extra
F_extradirs
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales
