#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20150502

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	WEB=http://ettercap.github.io/ettercap/downloads.html
	VERSION=`curl -s $WEB | grep latest | cut -d ":" -f 2 | cut -d- -f-1 | sed "s/ //g"`
	DESCARGA=https://github.com/Ettercap/ettercap/archive/v$VERSION.tar.gz
	PRGNAM=ettercap
	echo -ne "\033]2;${PRGNAM}_updater\007"
}

# Creamos directoprios extra
F_extradirs(){
mkdir -p $PKG/usr/share/applications/wifislax/Redes
}

# Comprobar dependencias
#F_dependencias(){

#}

# Si el paquete no existe se descargara de internet
F_download(){
	if [ ! -f $PRGNAM-$VERSION.tar.gz ]; then
	echo ""
	echo "$CYAN"Descargando sources de $PRGNAM-$VERSION"$CIERRE"
	sleep 3
	aria2c -x 3 $DESCARGA
	fi
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo ""
echo "$VERDE"Descomprimiendo ..."$CIERRE"
sleep 3
tar xvf $PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
 -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
 
# Configuramos paquete
echo ""
echo "$VERDE"Configurando ..."$CIERRE"
sleep 3
mkdir -p build
cd build
  cmake \
    -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DLIB_SUFFIX=${LIBDIRSUFFIX} \
    -DMAN_INSTALLDIR=/usr/man \
    -DBUNDLED_LIBS=OFF \
    -DCMAKE_BUILD_TYPE=Release ..
  make -j$NUCLEOS || exit 1
  make install DESTDIR=$PKG || exit 1
cd ..

# Creamos un nuevo desktop
rm -rf $PKG/usr/share/pixmaps/$PRGNAM.svg
rm -f $PKG/usr/share/applications/$PRGNAM.desktop 
cp -rf $PKG/usr/share/$PRGNAM/$PRGNAM.png $PKG/usr/share/pixmaps/$PRGNAM-gtk.png
echo "[Desktop Entry]
Name=Ettercap GTK
Comment=Nework sniffer/analyser
Exec=ettercap-pkexec -G
Icon=ettercap-gtk
Terminal=false
Type=Application
Categories=Redes" > $PKG/usr/share/applications/wifislax/Redes/$PRGNAM.desktop

}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
# Creamos directoprios extra
F_extradirs
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos conexion a Internet
f_comprobarConexion
#Comprobamos updates del script
f_comprobarUpdates
#Compronar dependencias
#F_dependencias
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
F_download
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales
