#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20151021

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=john
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=http://www.openwall.com/john/
	VERSION=`echo $(curl -s $WEB | grep \.gz | head -n1 | cut -d "/" -f2 | cut -d "t" -f1 | cut -d "-" -f2 | sed "s/.$//g")`
	EXTENSION=tar.gz
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	SRCNAM=src
	DOWNLOAD=$WEB/j/$PRGNAM-$VERSION.$EXTENSION
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
	echo 
	echo "$VERDE"Compilando..."$CIERRE"
	echo
	sleep 1
	mkdir -p $PKG/usr/share/john
	cp -a run/* $PKG/usr/share/john
	rm $PKG/usr/share/john/mailer
	make -j1 -C src clean generic CFLAGS="-DJOHN_SYSTEMWIDE=1 -c -Wall -O2 -fomit-frame-pointer"

	mkdir -p $PKG/usr/bin
	cp -a run/$PRGNAM run/mailer $PKG/usr/bin
	ln -s $PRGNAM $PKG/usr/bin/unafs
	ln -s $PRGNAM $PKG/usr/bin/unique
	ln -s $PRGNAM $PKG/usr/bin/unshadow
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales