#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20160211

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=netactview
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://sourceforge.net/projects/${PRGNAM}/files/${PRGNAM}/
	VERSION=`curl -s $WEB |grep $PRGNAM-[0-9]|head -1|cut -d- -f2|cut -d "/" -f-1`
	EXTENSION=tar.bz2
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	DOWNLOAD=https://sourceforge.net/projects/$PRGNAM/files/$PRGNAM/$PRGNAM-$VERSION/$SOURCES
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){

echo 
echo "$VERDE"Configurando ..."$CIERRE"
sleep 1
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib$LIBDIRSUFFIX \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --mandir=/usr/man \
  --build=$ARCH-slackware-linux

echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1

make  || exit 1
make install DESTDIR=$PKG

mkdir -p $PKG/usr/share/applications/wifislax/Redes/
mv -f $PKG/usr/share/applications/netactview.desktop $PKG/usr/share/applications/wifislax/Redes/
sed -i 's/Categories=GNOME;GTK;Network;Monitor;/Categories=Redes;/g' $PKG/usr/share/applications/wifislax/Redes/netactview.desktop
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales
