#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20151004

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	WEB=https://nmap.org/dist/
	VERSION=`curl -s $WEB | grep nmap-[0-9] | grep .tgz | tail -1 | cut -d- -f3 | cut -d "t" -f1 | sed "s/.$//g"`
	PRGNAM=nmap
	echo -ne "\033]2;${PRGNAM}_updater\007"
	EXTENSION=tar.bz2
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	DOWNLOAD=http://nmap.org/dist/$SOURCES
}

# Creamos directorios extra
F_extradirs(){
mkdir -p $PKG/usr/share/applications/wifislax/Redes/
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo ""
echo "$VERDE"Descomprimiendo ..."$CIERRE"
sleep 3
tar xvf $SOURCES
cd $PRGNAM-$VERSION
chown -R root:root .
find -L . \
  \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 -o -perm 511 \) \
  -exec chmod 755 {} \; -o \
  \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
  -exec chmod 644 {} \;
  
# Configuramos
LIBS="-lnl" \
CFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --with-liblua=included \
  --with-libpcap=included \
  --mandir=/usr/man \
  --docdir=/usr/doc/nmap-$VERSION \
  --without-nmap-update \
  --build=$ARCH-slackware-linux
  
make  || exit 1
make install DESTDIR=$PKG || exit 1

# Gneramos desktop
echo "[Desktop Entry]
Categories=Redes;
Exec=zenmap %F
GenericName=GUI Port Scanner
Icon=/usr/share/zenmap/pixmaps/zenmap.png
MimeType=
Name=Zenmap
Path=
StartupNotify=true
Terminal=false
TerminalOptions=
TryExec=zenmap
Type=Application" > $PKG/usr/share/applications/wifislax/Redes/$PRGNAM.desktop

# Eliminamos los desktops originales e idiomas extras
rm -Rf $PKG/usr/share/applications/*.desktop
rm -Rf $PKG/usr/share/zenmap/docs
rm -Rf $PKG/usr/share/zenmap/locale
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
# Creamos directorios extra
F_extradirs
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales
