#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20151209

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=pixiewps
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://github.com/wiire/${PRGNAM}
	VERSION=`curl -s $WEB/blob/master/version.mk|grep PKG_VERSION|head -1|rev|cut -d '=' -f-1|cut -d '<' -f2|rev`
	DOWNLOAD=https://github.com/wiire/pixiewps.git
}

F_download(){
if [ -d $TMP/${PRGNAM} ]; then
rm -rf $TMP/${PRGNAM}
fi
echo 
echo "$VERDE"Descargando ..."$CIERRE"
git clone $DOWNLOAD
echo
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){

cd $TMP/${PRGNAM}/src

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \

echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1
sed -i 's,/local,,g' Makefile
make  || exit 1
mkdir -p $PKG/usr/bin/
cp -rf $TMP/${PRGNAM}/src/${PRGNAM}  $PKG/usr/bin/
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
F_download
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales