#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20151105

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=snort
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://www.snort.org/
	VERSION=`echo $(curl -s $WEB/downloads|grep "tar.gz"|head -n1|cut -d "/" -f4|cut -d "-" -f2|cut -d "t" -f1|sed 's/.$//g')`
	EXTENSION=tar.gz
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	DOWNLOAD=$WEB/downloads/$PRGNAM/$PRGNAM-$VERSION.$EXTENSION
}

# Comprobar dependencias
F_dependencias(){
	DEPENDENCIAS="daq"
	f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
	echo 
	echo "$VERDE"Compilando ..."$CIERRE"
	sleep 1
	./configure --prefix=/usr --enable-sourcefire
	make || exit 1
	make install-strip DESTDIR=$PKG || exit 1
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
#Compronar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales