#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20150502

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	WEB=https://es.libreoffice.org/descarga/libreoffice-nuevo/
	VERSION=`curl -s $WEB | grep LibreOffice_ | head -1 | cut -d "/" -f 9 | cut -d "_" -f2`
	DESCARGA1=http://download.documentfoundation.org/libreoffice/stable/${VERSION}/rpm/x86/LibreOffice_${VERSION}_Linux_x86_rpm.tar.gz
	DESCARGA2=http://download.documentfoundation.org/libreoffice/stable/${VERSION}/rpm/x86/LibreOffice_${VERSION}_Linux_x86_rpm_langpack_es.tar.gz
	DESCARGA3=http://download.documentfoundation.org/libreoffice/stable/${VERSION}/rpm/x86/LibreOffice_${VERSION}_Linux_x86_rpm_helppack_es.tar.gz
	PRGNAM=LibreOffice
	echo -ne "\033]2;${PRGNAM}_updater\007"
	PRGNAM2=libreoffice-langpack_es
	PRGNAM3=libreoffice-helppack_es
	WJRE=${WJRE:-no}
	DISABLE_JAVA=${DISABLE_JAVA:-NO}
	SRCSHORT=$(echo $VERSION | cut -f1-2 -d.)
}

# Si el paquete no existe se descargara de internet
F_download(){
	if [ ! -f ${PRGNAM}_${VERSION}_Linux_${ARCH}_rpm.tar.gz ]; then
	echo ""
	echo "$CYAN"Descargando sources de $PRGNAM-$VERSION"$CIERRE"
	sleep 3
	aria2c -x 3 $DESCARGA1
	fi
# Si el paquete no existe se descargara de internet
	if [ ! -f ${PRGNAM}_${VERSION}_Linux_${ARCH}_rpm_langpack_es.tar.gz ]; then
	echo ""
	echo "$CYAN"Descargando sources de $PRGNAM2-$VERSION"$CIERRE"
	sleep 3
	aria2c -x 3 $DESCARGA2
	fi
# Si el paquete no existe se descargara de internet
	if [ ! -f ${PRGNAM}_${VERSION}_Linux_${ARCH}_rpm_helppack_es.tar.gz ]; then
	echo ""
	echo "$CYAN"Descargando sources de $PRGNAM3-$VERSION"$CIERRE"
	sleep 3
	aria2c -x 3 $DESCARGA3
	fi
}

# Descomprimir
F_compilar(){
	tar xvf ${PRGNAM}_${VERSION}_Linux_${ARCH}_rpm.tar.gz -C $TMP
	tar xvf ${PRGNAM}_${VERSION}_Linux_${ARCH}_rpm_helppack_es.tar.gz -C $TMP
	tar xvf ${PRGNAM}_${VERSION}_Linux_${ARCH}_rpm_langpack_es.tar.gz -C $TMP

# Eliminamos partes que no queremos de java
	rm -rf $TMP/${PRGNAM}_${VERSION}_Linux_${ARCH}_rpm/{JavaSetup.jar,installdata,setup}
	rm -rf $TMP/${PRGNAM}_${VERSION}_Linux_${ARCH}_rpm/RPMS/{userland,jre-*-linux-*.rpm}

# Convertimos los rpm
	cd $TMP/${PRGNAM}_${VERSION}*_Linux_x86_rpm/RPMS/
	rm -f *onlineupdate*.rpm
	for FILE in *.rpm ; do rpm2cpio < $FILE | cpio -imdv ; done
	rm -rf desktop-integration *.rpm
	mv opt usr $PKG

	cd $TMP/${PRGNAM}_${VERSION}*_rpm_helppack_es/RPMS/
	for FILE in *.rpm ; do rpm2cpio < $FILE | cpio -imdv ; done
	cp -Rf opt $PKG

	cd $TMP/${PRGNAM}_${VERSION}*_rpm_langpack_es/RPMS/
	for FILE in *.rpm ; do rpm2cpio < $FILE | cpio -imdv ; done
	cp -Rf opt $PKG
	cd $PKG

# Eliminar un simbolico muerto
	rm -f $PKG/usr/share/applications/libreoffice3-startcenter.desktop

# Creamos los simbolicos de los ejecutables
	cd $PKG/usr/bin
	for FILE in \
	sbase scalc sdraw simpress smath soffice spadmin swriter unopkg ; do
	rm -f $FILE
	ln -sf ../../opt/libreoffice$SRCSHORT/program/$FILE $FILE ;
	done
	cd -

# Eliminamos un par de fuentes innecesarias
	rm -f opt/libreoffice$SRCSHORT/share/fonts/truetype/{DejaVu,Liberation}*.ttf

# Fijamos la orden exec de los ficheros desktop
	cd $PKG/opt/libreoffice$SRCSHORT/share/xdg/
	for APP in base calc draw impress math writer; do
	sed -i "s%Exec=libreoffice -%Exec=/opt/libreoffice$SRCSHORT/program/s%" $APP.desktop ;
	done
	cd -

	if [ "$DISABLE_JAVA" = "YES" ]; then
	chmod -x $PKG/opt/libreoffice$SRCSHORT/ure/bin/javaldx
	fi

# Fix ownership and permissions and make the package
chown -R root:root .
find . -type d -exec chmod 755 {} \;
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
 -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

# Eliminamos de los desktop la categoria education
	cd $PKG/opt/libreoffice*/share/xdg/
	for DESKTOP in $(find -type f); do

	cat $DESKTOP | sed 's/Cate.*/Categories=Office;/g' >${DESKTOP}2
	rm $DESKTOP
	mv ${DESKTOP}2 ${DESKTOP}

	done
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura x86
#Comprobamos version instalada del script
f_versionInstalada
#Si no existe el fichero se descargara
F_download
#Descomprimir fichero descargado y compilamos
F_compilar
#Creamos xzm , instalamos y salimos
f_tareasFinales