#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20160404

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	if [ $ARCH = i586 ]; then
	ARCH=i386
	else
	ARCH=amd64
	fi
	PRGNAM=MasterPDFEditor
	SRCNAM=master-pdf-editor
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://code-industry.net/free-pdf-editor/
	VERSION=`curl -s $WEB|grep $ARCH.tar.gz|head -1|cut -d _  -f-1|rev|cut -d- -f1|rev`
	RAMA=`echo $VERSION|cut -d . -f1`
	DOWNLOAD=http://get.code-industry.net/public/${SRCNAM}-${VERSION}_$ARCH.tar.gz
}

# Si el paquete no existe se descargara de internet
F_download(){
	if [ ! -f ${SRCNAM}-${VERSION}_$ARCH.tar.gz ]; then
	echo 
	echo "$CYAN"Descargando sources de $PRGNAM-$VERSION"$CIERRE"
	sleep 1
	aria2c -x 3 $DOWNLOAD
	fi
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Descomprimiendo ..."$CIERRE"
sleep 1
rm -rf $SRCNAM-$RAMA
tar xvf $TMP/${SRCNAM}-${VERSION}_$ARCH.tar.gz
mkdir -p $PKG/opt
mv -f $SRCNAM-$RAMA $PKG/opt/$SRCNAM-$RAMA
cd $PKG/opt/$SRCNAM-$RAMA

mkdir -p $PKG/usr/bin
( ln -s /opt/$SRCNAM-$RAMA/masterpdfeditor$RAMA $PKG/usr/bin/ )

mkdir -p $PKG/usr/share/applications/
mv $PKG/opt/master-pdf-editor-$RAMA/masterpdfeditor$RAMA.desktop $PKG/usr/share/applications/$PRGNAM.desktop
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
F_download
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales