#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20160404

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	if [ $ARCH = i586 ]; then
	ARCH=x86
	else
	ARCH=x86-64
	fi
	PRGNAM=openoffice
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://sourceforge.net/projects/openofficeorg.mirror/files/
	VERSION=`curl -s $WEB|grep -m 1 "<tr title="|cut -d '"' -f2|sed "s/ //g"`
	RAMA=$(echo $VERSION|cut -f1 -d.)
	EXTENSION=tar.gz
	if [ $LANG = es_ES.utf8 ]; then
	IDIOMA=es
	else
	IDIOMA=en-US
	fi
	SOURCES=Apache_OpenOffice_${VERSION}_Linux_${ARCH}_install-rpm_$IDIOMA.$EXTENSION
	SRCNAM=$IDIOMA
	DOWNLOAD=https://sourceforge.net/projects/openofficeorg.mirror/files/$VERSION/binaries/$IDIOMA/$SOURCES
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
mkdir -p $PKG/usr/bin/
mkdir -p $PKG/usr/share/applications/
mkdir -p $PKG/usr/share/icons/
rm -f *onlineupdate*.rpm
cd $TMP/$SRCNAM/RPMS/desktop-integration
for FILE in *.rpm ; do rpm2cpio < $FILE | cpio -imdv ; done
mv $TMP/$SRCNAM/RPMS/desktop-integration/usr/share/icons/* $PKG/usr/share/icons/
rm -rf $TMP/$SRCNAM/RPMS/desktop-integration
cd $TMP/$SRCNAM/RPMS/
for FILE in *.rpm ; do rpm2cpio < $FILE | cpio -imdv ; done
rm -rf $TMP/$SRCNAM/RPMS/*.rpm
mv opt $PKG
cd $PKG

## fix desktop files, so they can launch
cat <<EOT > $PKG/usr/bin/${PRGNAM}$RAMA
#!/bin/sh
/opt/${PRGNAM}${RAMA}/program/soffice "\$@"
EOT
chmod 755 $PKG/usr/bin/${PRGNAM}$RAMA

## desktop files!
for APP in base calc draw impress math writer; do
  cp -av $PKG/opt/${PRGNAM}${RAMA}/share/xdg/$APP.desktop $PKG/usr/share/applications/open-$APP.desktop ;
done

mv $TMP/$IDIOMA $PKG/opt/${PRGNAM}${RAMA}/lang/

# Fix ownership and permissions and make the package
chown -R root:root .
find . -type d -exec chmod 755 {} \;
chmod -R u+rw,go+r-w,a-s .
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales