#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20151008

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=aria2
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=http://sourceforge.net/projects/aria2/files/stable/
	VERSION=`curl -s $WEB | grep latest | grep .bz2 | cut -d = -f4 | cut -d '/' -f3 | cut -d '-' -f2`
	EXTENSION=tar.bz2
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	DOWNLOAD=http://sourceforge.net/projects/aria2/files/stable/$PRGNAM-$VERSION/$SOURCES
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
# Aplicamos parche necesario para gcc 4.9
cat > aria2-gcc4.9.patch << "EOF"
--- aria2-1.19.0/src/a2gmp.h.orig	2015-05-26 23:16:33.145925238 +0700
+++ aria2-1.19.0/src/a2gmp.h	2015-05-26 23:17:01.022556391 +0700
@@ -35,6 +35,7 @@
 #ifndef D_A2GMP_H
 #define D_A2GMP_H
 
+#include <stddef.h>
 #include <gmp.h>
 
 namespace aria2 {
--- aria2-1.19.0/src/LibgmpDHKeyExchange.h.orig	2015-05-26 23:34:32.190146786 +0700
+++ aria2-1.19.0/src/LibgmpDHKeyExchange.h	2015-05-26 23:34:46.847939101 +0700
@@ -36,7 +36,7 @@
 #define D_LIBGMP_DH_KEY_EXCHANGE_H
 
 #include "common.h"
-
+#include <stddef.h>
 #include <gmp.h>
 
 namespace aria2 {

EOF


# Aplicamos parche
patch -p1 < aria2-gcc4.9.patch || exit 1
  
# Configuramos 
echo 
echo "$VERDE"Configurando ..."$CIERRE"
sleep 1
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --mandir=/usr/man \
  --docdir=/usr/doc/$PRGNAM-$VERSION \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --build=$ARCH-slackware-linux

# Compilamos
echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1
make || exit 1
make install DESTDIR=$PKG || exit 1

}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales

