#!/bin/bash

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20151116

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
#Definicion de variables
F_variables() {
	PRGNAM=dropbox
	SRCNAM=nautilus-dropbox
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://linux.dropbox.com/packages/fedora/
	VERSION=`curl -s $WEB|grep .rpm|grep i386|tail -1|cut -d- -f3|sed 's/ //g'`
	RAMA=`curl -s $WEB|grep .rpm|grep i386|tail -1|cut -d- -f4|cut -d . -f-1`
	SOURCES=$SRCNAM-$VERSION-$RAMA.fedora.i386.rpm
	DOWNLOAD=$WEB/$SOURCES
}

#Descomprime el fichero descargado
F_compilar() {
	echo ""
	echo "$VERDE"Descomprimiendo ..."$CIERRE"
	sleep 1
	rpm2dir $SOURCES $PKG
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura noarch
#Comprobamos version instalada del script
f_versionInstalada
#Descargamos el paquete si no existe
f_download
#Descomprimimos el paquete descargado 
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales