#!/bin/bash

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20151116

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
#Definicion de variables
F_variables() {
	PRGNAM=filezilla
	echo -ne "\033]2;${PRGNAM}_updater\007"
	PRGNAM2=FileZilla
	WEB=http://sourceforge.net/projects/filezilla/files/FileZilla_Client/
	VERSION=`curl -s $WEB | grep -m 1 "<tr title="|cut -d '"' -f2| sed "s/ //g"`
	EXTENSION=tar.bz2
	SOURCES=${PRGNAM2}_${VERSION}_src.$EXTENSION
	DOWNLOAD=${WEB}${VERSION}/$SOURCES
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="wxGTK3"
f_dependencias
}

#Compilamos el paquete
F_compilar() {
	echo ""
	echo "$VERDE"Configurando ..."$CIERRE"
	sleep 1

	LDFLAGS="-ldl" \
	CFLAGS="$SLKCFLAGS" \
	CXXFLAGS="$SLKCFLAGS" \
	./configure \
	  --prefix=/usr \
	  --libdir=/usr/lib${LIBDIRSUFFIX} \
	  --sysconfdir=/etc \
	  --localstatedir=/var \
	  --mandir=/usr/man \
	  --docdir=/usr/doc/$PRGNAM-$VERSION \
	  --disable-static \
	  --disable-manualupdatecheck \
	  --disable-autoupdatecheck \
	  --enable-locales \
	  --with-tinyxml=builtin \
	  --with-pugixml=builtin \
	  --build=$ARCH-slackware-linux

	make  LDFLAGS=-latomic || exit 1
	make install DESTDIR=$PKG || exit 1
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del script
f_versionInstalada
#Comprobar dependencias
F_dependencias
#Descargamos el paquete si no existe
f_download
#Preparamos entorno
f_preparar
#Compilamos el paquete
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales 