#!/bin/bash

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20151008

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
#Definicion de variables
F_variables() {
	PRGNAM=filezilla
	echo -ne "\033]2;${PRGNAM}_updater\007"
	PRGNAM2=FileZilla
	WEB=http://sourceforge.net/projects/filezilla/files/FileZilla_Client/
	VERSION=`curl -s $WEB | grep -m 1 "<tr title="|cut -d '"' -f2| sed "s/ //g"`
	EXTENSION=tar.bz2
	SOURCES=${PRGNAM2}_${VERSION}_src.$EXTENSION
	DOWNLOAD=${WEB}${VERSION}/$SOURCES
}

# Comprobar dependencias
F_dependencias(){
	echo 
	if [ -f /usr/lib/wx/config/gtk2-unicode-3.0 ]; then
	EXIST=`echo "$VERDE"Instalada"$CIERRE"`
	else
	EXIST=`echo "$ROJO"No Instalada"$CIERRE"`
	fi
	echo "$ROSA"Comprobando dependencias ..."$CIERRE"
	echo
sleep 3
	echo "$CYAN"Dependencias de este paquete:""
	echo ""
	echo "$AMARILLO"wxGTK3"$CIERRE: $EXIST"
	DEPENDENCIA=`ps -A | grep -o wxGTK3_updat`
	if [ ! $DEPENDENCIA = "" ]; then
		echo ""
		echo ""$ROJO"Se ha detectado en funcionamiento el "$AMARILLO"wxPython_updater"$CIERRE"..."
		echo ""
		echo ""$ROJO"Cuando acabe dicho updater lanza de nuevo este"$CIERRE"..."
		echo ""
		exit 1
	fi
	if [ ! -f /usr/lib/wx/config/gtk2-unicode-3.0 ]; then
		echo ""
		echo ""$ROJO"No se cumplen los requisitos"$CIERRE"... "$VERDE"resolviendo"$CIERRE"..."
		sleep 3
		cd /opt/wifislax-updaters/Librerias/
		statusfile=$(mktemp)
		xterm -e sh -c '/opt/wifislax-updaters/Librerias/wxGTK3_updater; echo $? > '$statusfile 
		status=$(cat $statusfile)
		rm $statusfile
		if [ -z $status ] || [ $status != "0" ]; then
		  echo "$ROJO"ERROR. No se ha podido crear el paquete"$CIERRE"
		  if [ -z $status ]; then
		    exit 1
		  else
		    exit $status
		  fi
		fi
		
		cd $TMP
	else
		echo ""
		echo "$VERDE"Bien ..podemos continuar"$CIERRE"
		echo ""
		sleep 3
	fi
}


#Compilamos el paquete
F_compilar() {
	echo ""
	echo "$VERDE"Configurando ..."$CIERRE"
	sleep 3

	LDFLAGS="-ldl" \
	CFLAGS="$SLKCFLAGS" \
	CXXFLAGS="$SLKCFLAGS" \
	./configure \
	  --prefix=/usr \
	  --libdir=/usr/lib${LIBDIRSUFFIX} \
	  --sysconfdir=/etc \
	  --localstatedir=/var \
	  --mandir=/usr/man \
	  --docdir=/usr/doc/$PRGNAM-$VERSION \
	  --disable-static \
	  --disable-manualupdatecheck \
	  --disable-autoupdatecheck \
	  --enable-locales \
	  --with-tinyxml=builtin \
	  --with-pugixml=builtin \
	  --build=$ARCH-slackware-linux

	make  LDFLAGS=-latomic || exit 1
	make install DESTDIR=$PKG || exit 1

}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobar dependencias
F_dependencias
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del script
f_versionInstalada
#Descargamos el paquete si no existe
f_download
#Preparamos entorno
f_preparar
#Compilamos el paquete
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales 
