#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20160113

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=skype
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=$(wget --spider http://www.skype.com/go/getskype-linux-beta-suse 2>&1 | grep "download.skype.com/linux" -m 1| awk '{print $2}')
	VERSION=$(echo $WEB | cut -d "-" -f2)
	EXTENSION=tar.bz2
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	DOWNLOAD=http://download.skype.com/linux/$SOURCES
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
mkdir -p $PKG/usr/{bin,share/{skype,pixmaps,applications}} $PKG/etc/dbus-1/system.d
cp -a skype $PKG/usr/bin
cp -a avatars lang sounds $PKG/usr/share/skype
cat skype.desktop > $PKG/usr/share/applications/skype.desktop
cat icons/SkypeBlue_48x48.png > $PKG/usr/share/pixmaps/skype.png
cat skype.conf > $PKG/etc/dbus-1/system.d/skype.conf
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del script
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparar entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Creamos xzm , instalamos y salimos
f_tareasFinales
