#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20150706

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=skype
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=$(wget --spider http://www.skype.com/go/getskype-linux-beta-suse 2>&1 | grep "download.skype.com/linux" -m 1| awk '{print $2}')
	VERSION=$(echo $WEB | cut -d "-" -f2)
	DESCARGA=http://download.skype.com/linux/$PRGNAM-$VERSION.tar.bz2
}

# Comprobar dependencias
F_dependencias() {
if [ -f /usr/bin/apulse ]; then
EXIST=`echo "$VERDE"Instalada"$CIERRE"`
else
EXIST=`echo "$ROJO"No Instalada"$CIERRE"`
fi
echo "$ROSA"Comprobando dependencias ..."$CIERRE"
sleep 3
echo "$CYAN"Dependencias de este paquete:""
echo ""
echo "$AMARILLO"apulse"$CIERRE: $EXIST"
if [ ! -f /usr/bin/apulse ]; then
echo ""
echo ""$ROJO"No se cumplen los requisitos"$CIERRE"... "$VERDE"resolviendo"$CIERRE"..."
sleep 3
cd /opt/wifislax-updaters/Librerias/ && xterm /opt/wifislax-updaters/Librerias/apulse_updater && cd $TMP
else
echo ""
echo "$VERDE"Bien ..podemos continuar"$CIERRE"
echo ""
sleep 3
fi
}

# Si el paquete no existe se descargara de internet
	F_download(){
	if [ ! -f $PRGNAM-$VERSION.tar.bz2 ]; then
	echo ""
	echo "$CYAN"Descargando sources de $PRGNAM-$VERSION"$CIERRE"
	sleep 3
	aria2c -x 3 $DESCARGA
	fi
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo ""
echo "$VERDE"Descomprimiendo ..."$CIERRE"
sleep 3
rm -rf $PRGNAM-$VERSION
tar xvf $PRGNAM-$VERSION.tar.bz2
cd $PRGNAM-$VERSION
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
 -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

mkdir -p $PKG/usr/{bin,share/{skype,pixmaps,applications}} $PKG/etc/dbus-1/system.d
cp -a skype $PKG/usr/bin
cp -a avatars lang sounds $PKG/usr/share/skype
cat skype.desktop > $PKG/usr/share/applications/skype.desktop
cat icons/SkypeBlue_48x48.png > $PKG/usr/share/pixmaps/skype.png
cat skype.conf > $PKG/etc/dbus-1/system.d/skype.conf

# Cambio en el desktop si apulse se compilo
if [ -f /usr/bin/apulse ]; then
sed -i 's/Exec=skype %U/Exec=apulse skype %U/g' $PKG/usr/share/applications/skype.desktop
fi
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
# Comprobar dependencias
F_dependencias
#Comprobamos version instalada del script
f_versionInstalada
#Si no existe el fichero se descargara
F_download
#Descomprimir fichero descargado y compilamos
F_compilar
#Creamos xzm , instalamos y salimos
f_tareasFinales
