#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20150906

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=teamviewer
	echo -ne "\033]2;${PRGNAM}_updater\007"
	DOWNLOAD=http://download.teamviewer.com/download/teamviewer_linux.tar.gz
	WEB=https://www.teamviewer.com/es/download/linux.aspx
	VERSION=$(curl -sk $WEB | grep _ctl4_Version | head -1 | cut -d "v" -f2 | cut -d '<' -f-1)
}

# Creamos directorios extra
F_extradirs(){
mkdir -p $PKG/opt $PKG/usr/share/{applications,pixmaps}
}

# Si el paquete no existe se descargara de internet
F_download(){
	if [ ! -f teamviewer_linux.tar.gz ]; then
	echo 
	echo "$CYAN"Descargando sources de $PRGNAM-$VERSION"$CIERRE"
	sleep 1
	aria2c -x 3 $DOWNLOAD
	fi
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Descomprimiendo ..."$CIERRE"
sleep 1
tar xvf teamviewer_linux.tar.gz -C $PKG/opt

# Copiamos desktop & icono
cp -rf $PKG/opt/teamviewer/tv_bin/desktop/teamviewer.png $PKG/usr/share/pixmaps/teamviewer.png
cp -rf $PKG/opt/teamviewer/tv_bin/desktop/*.desktop $PKG/usr/share/applications/teamviewer.desktop

rm -rf /opt/teamviewer*
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Creamos directorios extra
F_extradirs
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
F_download
#Descomprimir fichero descargado y compilamos
F_compilar
#Creamos xzm , instalamos y salimos
f_tareasFinales