#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20160807

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=teamviewer
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=http://www.teamviewer.com/es/download/linux/
	VERSION=`curl -sL $WEB|grep tar.xz|grep -v i386|head -1|cut -d '>' -f2|cut -d ' ' -f-1|cut -d v -f2`
	DOWNLOAD=http://download.teamviewer.com/download/${PRGNAM}_i386.deb
}

# Si el paquete no existe se descargara de internet
F_download(){
	if [ ! -f ${PRGNAM}_${VERSION}_i386.deb ]; then
	echo 
	echo "$CYAN"Descargando sources de $PRGNAM-$VERSION"$CIERRE"
	sleep 1
	aria2c -x 3 $DOWNLOAD
	fi
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Descomprimiendo ..."$CIERRE"
sleep 1
mkdir -p $PKG/opt $PKG/usr/share/{applications,pixmaps}
mkdir -p "$TMP/deb"
deb2dir $TMP/${PRGNAM}_${VERSION}_i386.deb "$TMP/deb"
cp -rfp "$TMP"/deb/* "$PKG"
# Copiamos desktop & icono
cp -rf $PKG/opt/teamviewer/tv_bin/desktop/teamviewer.png $PKG/usr/share/pixmaps/teamviewer.png
cp -rf $PKG/opt/teamviewer/tv_bin/desktop/*.desktop $PKG/usr/share/applications/teamviewer.desktop
# Metemos el servicio
mkdir -p $PKG/etc/rc.d
echo "
IyEvYmluL3NoCiMKIyAvZXRjL3JjLmQvcmMudGVhbXZpZXdlcmQKIwojIFN0YXJ0L3N0b3AvcmVz
dGFydCB0aGUgVGVhbVZpZXdlciBEYWVtb24KIwojIFRvIG1ha2UgVGVhbVZpZXdlciBEYWVtb24g
c3RhcnQgYXV0b21hdGljYWxseSBhdCBib290LCBtYWtlIHRoaXMKIyBmaWxlIGV4ZWN1dGFibGU6
ICBjaG1vZCA3NTUgL2V0Yy9yYy5kL3JjLnRlYW12aWV3ZXJkCiMgQWxzbywgYWRkIHRoaXMgbGlu
ZSBpbiB5b3VyIC9ldGMvcmMuZC9yYy5sb2NhbDoKIwojIGlmIFsgLXggL2V0Yy9yYy5kL3JjLnRl
YW12aWV3ZXJkIF07IHRoZW4KIyAgICAgICAgL2V0Yy9yYy5kL3JjLnRlYW12aWV3ZXJkIHN0YXJ0
CiMgZmkKIwoKdGVhbXZpZXdlcmRfc3RhcnQoKSB7CiAgaWYgWyAteCAvb3B0L3RlYW12aWV3ZXIv
dHZfYmluL3RlYW12aWV3ZXJkIF07IHRoZW4KICAgIGVjaG8gIlN0YXJ0aW5nIFRlYW1WaWV3ZXIg
RGFlbW9uIgogICAgL29wdC90ZWFtdmlld2VyL3R2X2Jpbi90ZWFtdmlld2VyZCAtLWRhZW1vbiBz
dGFydAogIGZpCn0KCnRlYW12aWV3ZXJkX3N0b3AoKSB7CiAgICBlY2hvICJUZXJtaW5hdGluZyBU
ZWFtVmlld2VyIERhZW1vbiIKICBraWxsYWxsIHRlYW12aWV3ZXJkCn0KCnRlYW12aWV3ZXJkX3Jl
c3RhcnQoKSB7CiAgdGVhbXZpZXdlcmRfc3RvcAogIHNsZWVwIDIKICB0ZWFtdmlld2VyZF9zdGFy
dAp9CgpjYXNlICIkMSIgaW4KJ3N0YXJ0JykKICB0ZWFtdmlld2VyZF9zdGFydAogIDs7CidzdG9w
JykKICB0ZWFtdmlld2VyZF9zdG9wCiAgOzsKJ3Jlc3RhcnQnKQogIHRlYW12aWV3ZXJkX3Jlc3Rh
cnQKICA7OwoqKQogIGVjaG8gInVzYWdlICQwIHN0YXJ0fHN0b3B8cmVzdGFydCIKZXNhYwo=
" | base64 -d > $PKG/etc/rc.d/rc.teamviewerd
chmod 777 $PKG/etc/rc.d/rc.teamviewerd
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
F_download
#Descomprimir fichero descargado y compilamos
F_compilar
#Creamos xzm , instalamos y salimos
f_tareasFinales