#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20160902

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=gambas
	RAMA=3
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://sourceforge.net/projects/gambas/files/gambas$RAMA/
	VERSION=`curl -s $WEB|grep .bz2|grep title|grep -v latest|head -1|cut -d- -f2|cut -d t -f-1|sed 's/.$//g'|sed 's/ //g'`
	EXTENSION=tar.bz2
	SRCNAM=gambas${RAMA}-$VERSION
	SOURCES=$SRCNAM.$EXTENSION
	DOWNLOAD="https://downloads.sourceforge.net/project/gambas/gambas$RAMA/$SOURCES"
}

# Descomprimimos el fichero descargado
F_compilar(){
echo ""
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1

./reconf-all \

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --build=$ARCH-slackware-linux
  
make || exit 1
make -j1 install-strip DESTDIR=$PKG XDG_UTILS=""

mkdir -p $PKG/usr/share/icons/hicolor/{scalable/apps,48x48/apps,64x64/mimetypes}
cp -a app/desktop/gambas${RAMA}.svg $PKG/usr/share/icons/hicolor/scalable/apps
cp -a app/desktop/gambas${RAMA}.png $PKG/usr/share/icons/hicolor/48x48/apps
cp -a app/mime/application-x-${PRGNAM}{script,serverpage}.png \
  $PKG/usr/share/icons/hicolor/64x64/mimetypes
cp -a main/mime/application-x-gambas${RAMA}.png \
  $PKG/usr/share/icons/hicolor/64x64/mimetypes

mkdir -p $PKG/usr/share/{applications,mime/packages}
cp -a app/desktop/gambas${RAMA}.desktop $PKG/usr/share/applications
cp -a app/mime/application-x-${PRGNAM}{script,serverpage}.xml \
  $PKG/usr/share/mime/packages
cp -a main/mime/application-x-gambas${RAMA}.xml $PKG/usr/share/mime/packages
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del script
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Creamos xzm , instalamos y salimos
f_tareasFinales