#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20151222

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	WEB=https://www.python.org/downloads/
	#VERSION=`curl -s $WEB | grep .tar.xz | head -1 | cut -d "-" -f2 | cut -d "t" -f-1 | sed "s/.$//g"`
	VERSION=3.5.1
	PRGNAM=python3
	echo -ne "\033]2;${PRGNAM}_updater\007"
	PRGNAM2=Python
	PYVER=$(cut -d. -f1,2 <<< "$VERSION")
	SITEPK=$PKG/usr/lib${LIBDIRSUFFIX}/python${PYVER}/site-packages
	TOOLSDIR=/usr/lib${LIBDIRSUFFIX}/python${PYVER}/site-packages
	EXTENSION=tar.xz
	SOURCES=$PRGNAM2-$VERSION.$EXTENSION
	DOWNLOAD=https://www.python.org/ftp/python/$VERSION/$SOURCES
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
cd $PRGNAM2-$VERSION

# Parcheamos
echo "
ZGlmZiAtdWFyIFB5dGhvbi0zLjUuMC5vcmlnL01ha2VmaWxlLnByZS5pbiBQeXRob24tMy41LjAv
TWFrZWZpbGUucHJlLmluCi0tLSBQeXRob24tMy41LjAub3JpZy9NYWtlZmlsZS5wcmUuaW4JMjAx
NS0wOS0xMyAxNDo0MToyMy4wMDAwMDAwMDAgKzAzMDAKKysrIFB5dGhvbi0zLjUuMC9NYWtlZmls
ZS5wcmUuaW4JMjAxNS0xMC0yNSAxNjozMzo1Ni4xOTExMzAyNjkgKzAyMDAKQEAgLTU0OSw3ICs1
NDksNyBAQAogCSQoUlVOU0hBUkVEKSAkKFBZVEhPTl9GT1JfQlVJTEQpIC4vVG9vbHMvY2xpbmlj
L2NsaW5pYy5weSAtLW1ha2UKIAogIyBCdWlsZCB0aGUgaW50ZXJwcmV0ZXIKLSQoQlVJTERQWVRI
T04pOglQcm9ncmFtcy9weXRob24ubyAkKExJQlJBUlkpICQoTERMSUJSQVJZKSAkKFBZM0xJQlJB
UlkpCiskKEJVSUxEUFlUSE9OKToJUHJvZ3JhbXMvcHl0aG9uLm8gJChMRExJQlJBUlkpICQoUFkz
TElCUkFSWSkKIAkkKExJTktDQykgJChQWV9MREZMQUdTKSAkKExJTktGT1JTSEFSRUQpIC1vICRA
IFByb2dyYW1zL3B5dGhvbi5vICQoQkxETElCUkFSWSkgJChMSUJTKSAkKE1PRExJQlMpICQoU1lT
TElCUykgJChMRExBU1QpCiAKIHBsYXRmb3JtOiAkKEJVSUxEUFlUSE9OKSBweWJ1aWxkZGlyLnR4
dApAQCAtNTg0LDE4ICs1ODQsNiBAQAogCQlfVENMVEtfSU5DTFVERVM9JyQoVENMVEtfSU5DTFVE
RVMpJyBfVENMVEtfTElCUz0nJChUQ0xUS19MSUJTKScgXAogCQkkKFBZVEhPTl9GT1JfQlVJTEQp
ICQoc3JjZGlyKS9zZXR1cC5weSAkJHF1aWV0IGJ1aWxkCiAKLSMgQnVpbGQgc3RhdGljIGxpYnJh
cnkKLSMgYXZvaWQgbG9uZyBjb21tYW5kIGxpbmVzLCBzYW1lIGFzIExJQlJBUllfT0JKUwotJChM
SUJSQVJZKTogJChMSUJSQVJZX09CSlMpCi0JLXJtIC1mICRACi0JJChBUikgJChBUkZMQUdTKSAk
QCBNb2R1bGVzL2dldGJ1aWxkaW5mby5vCi0JJChBUikgJChBUkZMQUdTKSAkQCAkKFBBUlNFUl9P
QkpTKQotCSQoQVIpICQoQVJGTEFHUykgJEAgJChPQkpFQ1RfT0JKUykKLQkkKEFSKSAkKEFSRkxB
R1MpICRAICQoUFlUSE9OX09CSlMpIFB5dGhvbi9mcm96ZW4ubwotCSQoQVIpICQoQVJGTEFHUykg
JEAgJChNT0RVTEVfT0JKUykgJChTSUdOQUxfT0JKUykKLQkkKEFSKSAkKEFSRkxBR1MpICRAICQo
TU9ET0JKUykKLQkkKFJBTkxJQikgJEAKLQogbGlicHl0aG9uJChMRFZFUlNJT04pLnNvOiAkKExJ
QlJBUllfT0JKUykKIAlpZiB0ZXN0ICQoSU5TVFNPTkFNRSkgIT0gJChMRExJQlJBUlkpOyB0aGVu
IFwKIAkJJChCTERTSEFSRUQpIC1XbCwtaCQoSU5TVFNPTkFNRSkgLW8gJChJTlNUU09OQU1FKSAk
KExJQlJBUllfT0JKUykgJChNT0RMSUJTKSAkKFNITElCUykgJChMSUJDKSAkKExJQk0pICQoTERM
QVNUKTsgXApAQCAtNjg1LDcgKzY3Myw3IEBACiAJCWVjaG8gIi0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tIjsgXAogCWZpCiAKLVByb2dyYW1zL190ZXN0ZW1i
ZWQ6IFByb2dyYW1zL190ZXN0ZW1iZWQubyAkKExJQlJBUlkpICQoTERMSUJSQVJZKSAkKFBZM0xJ
QlJBUlkpCitQcm9ncmFtcy9fdGVzdGVtYmVkOiBQcm9ncmFtcy9fdGVzdGVtYmVkLm8gJChMRExJ
QlJBUlkpICQoUFkzTElCUkFSWSkKIAkkKExJTktDQykgJChQWV9MREZMQUdTKSAkKExJTktGT1JT
SEFSRUQpIC1vICRAIFByb2dyYW1zL190ZXN0ZW1iZWQubyAkKEJMRExJQlJBUlkpICQoTElCUykg
JChNT0RMSUJTKSAkKFNZU0xJQlMpICQoTERMQVNUKQogCiAjIyMjIyMjIyMjIyMjIyMjIyMjIyMj
IyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjCkBA
IC0xMzU3LDE4ICsxMzQ1LDYgQEAKIAkJZWxzZQl0cnVlOyBcCiAJCWZpOyBcCiAJZG9uZQotCUBp
ZiB0ZXN0IC1kICQoTElCUkFSWSk7IHRoZW4gOjsgZWxzZSBcCi0JCWlmIHRlc3QgIiQoUFlUSE9O
RlJBTUVXT1JLRElSKSIgPSBuby1mcmFtZXdvcms7IHRoZW4gXAotCQkJaWYgdGVzdCAiJChTSExJ
Ql9TVUZGSVgpIiA9IC5kbGw7IHRoZW4gXAotCQkJCSQoSU5TVEFMTF9EQVRBKSAkKExETElCUkFS
WSkgJChERVNURElSKSQoTElCUEwpIDsgXAotCQkJZWxzZSBcCi0JCQkJJChJTlNUQUxMX0RBVEEp
ICQoTElCUkFSWSkgJChERVNURElSKSQoTElCUEwpLyQoTElCUkFSWSkgOyBcCi0JCQkJJChSQU5M
SUIpICQoREVTVERJUikkKExJQlBMKS8kKExJQlJBUlkpIDsgXAotCQkJZmk7IFwKLQkJZWxzZSBc
Ci0JCQllY2hvIFNraXAgaW5zdGFsbCBvZiAkKExJQlJBUlkpIC0gdXNlIG1ha2UgZnJhbWV3b3Jr
aW5zdGFsbDsgXAotCQlmaTsgXAotCWZpCiAJJChJTlNUQUxMX0RBVEEpIE1vZHVsZXMvY29uZmln
LmMgJChERVNURElSKSQoTElCUEwpL2NvbmZpZy5jCiAJJChJTlNUQUxMX0RBVEEpIFByb2dyYW1z
L3B5dGhvbi5vICQoREVTVERJUikkKExJQlBMKS9weXRob24ubwogCSQoSU5TVEFMTF9EQVRBKSAk
KHNyY2RpcikvTW9kdWxlcy9jb25maWcuYy5pbiAkKERFU1RESVIpJChMSUJQTCkvY29uZmlnLmMu
aW4K" | base64 -d > $TMP/python3.no-static-library.diff

patch -p1 -i $TMP/python3.no-static-library.diff || exit 1

echo "
LS0tIC4vTW9kdWxlcy9yZWFkbGluZS5jLm9yaWcJMjAwOS0xMC0yNiAyMTozMjo1MS4wMDAwMDAw
MDAgKzAyMDAKKysrIC4vTW9kdWxlcy9yZWFkbGluZS5jCTIwMTAtMDUtMzAgMTQ6MDc6MTAuMDAw
MDAwMDAwICswMzAwCkBAIC0xMiw2ICsxMiw5IEBACiAjaW5jbHVkZSA8ZXJybm8uaD4KICNpbmNs
dWRlIDxzeXMvdGltZS5oPgogCisvKiBUaGlzIHNlZW1zIHRvIGJlIG5lZWRlZCBmb3Igc2V0X3By
ZV9pbnB1dF9ob29rIHRvIHdvcmsgKi8KKyNkZWZpbmUgSEFWRV9STF9QUkVfSU5QVVRfSE9PSyAx
CisKICNpZiBkZWZpbmVkKEhBVkVfU0VUTE9DQUxFKQogLyogR05VIHJlYWRsaW5lKCkgbWlzdGFr
ZW5seSBzZXRzIHRoZSBMQ19DVFlQRSBsb2NhbGUuCiAgKiBUaGlzIGlzIGV2aWwuICBPbmx5IHRo
ZSB1c2VyIG9yIHRoZSBhcHAncyBtYWluKCkgc2hvdWxkIGRvIHRoaXMhCg==
" | base64 -d > $TMP/python3.readline.set_pre_input_hook.diff

patch -p1 -i $TMP/python3.readline.set_pre_input_hook.diff || exit 1

# Fixes
sed -i '1s|^#.*/usr/local/bin/python|#!/usr/bin/python3|' Lib/cgi.py
sed -i 's|\("install",\)|\1 "--ignore-installed",|' Lib/ensurepip/__init__.py

echo 
echo "$VERDE"Configurando ..."$CIERRE"
sleep 1  
  
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --mandir=/usr/man \
  --docdir=/usr/doc/$PRGNAM-$VERSION \
  --with-threads \
  --enable-ipv6 \
  --enable-shared \
  --with-system-expat \
  --with-system-ffi \
  --build=$ARCH-slackware-linux

echo 
echo "$VERDE"Compilamos ..."$CIERRE"
sleep 1  
  
make  || exit 1
make install DESTDIR=$PKG

# Restore original ensurepip behaviour.
sed -i 's|\("install",\) "--ignore-installed",|\1|' \
  $PKG/usr/lib${LIBDIRSUFFIX}/python${PYVER}/ensurepip/__init__.py

# Remove to avoid overwriting a copy from Python2.
rm -f $PKG/usr/bin/2to3

# We'll install the python-tools under site-packages:
mkdir -p $SITEPK
cp -a Tools/* $SITEPK

# Remove DOS batch/exe files.
find $PKG \( -name '*.exe' -o -name '*.bat' \) -exec rm -f '{}' \;

# Fix permissions on dynamic libraries.
find $PKG -type f -perm 555 -exec chmod 755 '{}' \;
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales
