#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20151008

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	WEB=https://www.python.org/downloads/
	VERSION=`curl -s $WEB | grep .tar.xz | head -1 | cut -d "-" -f2 | cut -d "t" -f-1 | sed "s/.$//g"`
	PRGNAM=python3
	echo -ne "\033]2;${PRGNAM}_updater\007"
	PRGNAM2=Python
	PYVER=$(cut -d. -f1,2 <<< "$VERSION")
	SITEPK=$PKG/usr/lib${LIBDIRSUFFIX}/python${PYVER}/site-packages
	TOOLSDIR=/usr/lib${LIBDIRSUFFIX}/python${PYVER}/site-packages
	EXTENSION=tar.xz
	SOURCES=$PRGNAM2-$VERSION.$EXTENSION
	DOWNLOAD=https://www.python.org/ftp/python/$VERSION/$SOURCES
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
cd $PRGNAM2-$VERSION
# Fixes
sed -i '1s|^#.*/usr/local/bin/python|#!/usr/bin/python3|' Lib/cgi.py
sed -i 's|\("install",\)|\1 "--ignore-installed",|' Lib/ensurepip/__init__.py
sed -i 's|@SO@|@EXT_SUFFIX@|' Misc/python-config.sh.in

echo 
echo "$VERDE"Configurando ..."$CIERRE"
sleep 1  
  
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --mandir=/usr/man \
  --docdir=/usr/doc/$PRGNAM-$VERSION \
  --with-threads \
  --enable-ipv6 \
  --enable-shared \
  --with-system-expat \
  --with-system-ffi \
  --build=$ARCH-slackware-linux

echo 
echo "$VERDE"Compilamos ..."$CIERRE"
sleep 1  
  
make  || exit 1
make install DESTDIR=$PKG

# Restore original ensurepip behaviour.
sed -i 's|\("install",\) "--ignore-installed",|\1|' \
  $PKG/usr/lib${LIBDIRSUFFIX}/python${PYVER}/ensurepip/__init__.py

# Remove to avoid overwriting a copy from Python2.
rm -f $PKG/usr/bin/2to3

# We'll install the python-tools under site-packages:
mkdir -p $SITEPK
cp -a Tools/* $SITEPK

# Remove DOS batch/exe files.
find $PKG \( -name '*.exe' -o -name '*.bat' \) -exec rm -f '{}' \;

# Fix permissions on dynamic libraries.
find $PKG -type f -perm 555 -exec chmod 755 '{}' \;
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales
