#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20151024

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=qt5
	SRCNAM=qt-everywhere-opensource-src
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=http://download.qt-project.org/official_releases/qt/
	VERSION=5.5.0
	RAMA=5.5
	EXTENSION=tar.xz
	SOURCES=$SRCNAM-$VERSION.$EXTENSION
	DOWNLOAD=${WEB}$RAMA/$VERSION/single/$SOURCES
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Configurando ..."$CIERRE"
sleep 1
echo "ZGlmZiAtTmF1ciBxdC1ldmVyeXdoZXJlLW9wZW5zb3VyY2Utc3JjLTUuMS4wLm9yaWcvcXRiYXNl
L3NyYy9zcWwvZHJpdmVycy9teXNxbC9xc3FsX215c3FsX3AuaCBxdC1ldmVyeXdoZXJlLW9wZW5z
b3VyY2Utc3JjLTUuMS4wL3F0YmFzZS9zcmMvc3FsL2RyaXZlcnMvbXlzcWwvcXNxbF9teXNxbF9w
LmgKLS0tIHF0LWV2ZXJ5d2hlcmUtb3BlbnNvdXJjZS1zcmMtNS4xLjAub3JpZy9xdGJhc2Uvc3Jj
L3NxbC9kcml2ZXJzL215c3FsL3FzcWxfbXlzcWxfcC5oCTIwMTMtMDctMDIgMDc6MDk6NTIuMDAw
MDAwMDAwICswMDAwCisrKyBxdC1ldmVyeXdoZXJlLW9wZW5zb3VyY2Utc3JjLTUuMS4wL3F0YmFz
ZS9zcmMvc3FsL2RyaXZlcnMvbXlzcWwvcXNxbF9teXNxbF9wLmgJMjAxMy0wNy0yMSAyMToyMTow
MS4xOTAxNzIzNzkgKzAwMDAKQEAgLTYwLDcgKzYwLDcgQEAKICNpbmNsdWRlIDxRdENvcmUvcXRf
d2luZG93cy5oPgogI2VuZGlmCiAKLSNpbmNsdWRlIDxteXNxbC5oPgorI2luY2x1ZGUgPG15c3Fs
L215c3FsLmg+CiAKICNpZmRlZiBRVF9QTFVHSU4KICNkZWZpbmUgUV9FWFBPUlRfU1FMRFJJVkVS
X01ZU1FMCg==" | base64 -d > $TMP/qt5.mysql.h.diff
patch -p1 < $TMP/qt5.mysql.h.diff || exit 1

echo "ZGlmZiAtTmF1ciBxdC1ldmVyeXdoZXJlLW9wZW5zb3VyY2Utc3JjLTUuMC4yLm9yaWcvcXR3ZWJr
aXQvU291cmNlL1dlYktpdC9xdC9leGFtcGxlcy9wbGF0Zm9ybXBsdWdpbi9wbGF0Zm9ybXBsdWdp
bi5wcm8gcXQtZXZlcnl3aGVyZS1vcGVuc291cmNlLXNyYy01LjAuMi9xdHdlYmtpdC9Tb3VyY2Uv
V2ViS2l0L3F0L2V4YW1wbGVzL3BsYXRmb3JtcGx1Z2luL3BsYXRmb3JtcGx1Z2luLnBybwotLS0g
cXQtZXZlcnl3aGVyZS1vcGVuc291cmNlLXNyYy01LjAuMi5vcmlnL3F0d2Via2l0L1NvdXJjZS9X
ZWJLaXQvcXQvZXhhbXBsZXMvcGxhdGZvcm1wbHVnaW4vcGxhdGZvcm1wbHVnaW4ucHJvCTIwMTMt
MDQtMDkgMDA6MTE6MzguMDAwMDAwMDAwICswMDAwCisrKyBxdC1ldmVyeXdoZXJlLW9wZW5zb3Vy
Y2Utc3JjLTUuMC4yL3F0d2Via2l0L1NvdXJjZS9XZWJLaXQvcXQvZXhhbXBsZXMvcGxhdGZvcm1w
bHVnaW4vcGxhdGZvcm1wbHVnaW4ucHJvCTIwMTMtMDUtMzEgMDE6MTg6MjkuMTU3MTc1MDgyICsw
MDAwCkBAIC0yMCw3ICsyMCw4IEBACiAgICAgfQogfQogCi1ERVNURElSID0gJCRbUVRfSU5TVEFM
TF9QTFVHSU5TXS93ZWJraXQKK3RhcmdldC5wYXRoID0gJCRbUVRfSU5TVEFMTF9QTFVHSU5TXS93
ZWJraXQKK0lOU1RBTExTICs9IHRhcmdldAogCiBTT1VSQ0VTICs9IFwKICAgICBXZWJQbHVnaW4u
Y3BwIFwK" | base64 -d > $TMP/platformplugin-install-path-fix.patch
patch -p1 < $TMP/platformplugin-install-path-fix.patch || exit 1

sed -i "s|-O2|$SLKCFLAGS|" qtbase/mkspecs/common/gcc-base.conf

[[ "${ARCH}" = "i686" ]] && SSE2="-no-sse2"

export CFLAGS="$SLKCFLAGS"
export CXXFLAGS="$SLKCFLAGS"
./configure -v \
  -confirm-license \
  -opensource \
  -prefix "/usr/lib${LIBDIRSUFFIX}/$PRGNAM" \
  -sysconfdir "/etc/xdg" \
  -headerdir "/usr/include/$PRGNAM" \
  -libdir "/usr/lib${LIBDIRSUFFIX}" \
  -docdir "/usr/doc/$PRGNAM-$VERSION" \
  -system-libpng \
  -system-libjpeg \
  -system-zlib \
  -system-sqlite \
  -system-pcre \
  -plugin-sql-sqlite \
  -icu \
  -openssl \
  -verbose \
  -optimized-qmake \
  -dbus-linked \
  -qpa xcb \
  -xcb \
  -glib \
  -accessibility \
  -no-separate-debug-info \
  -no-pch \
  -no-rpath \
  -no-strip \
  -release \
  -no-use-gold-linker \
  -no-pulseaudio \
  -nomake examples \
  -no-reduce-relocations ${SSE2}

echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1
make || exit 1
make install INSTALL_ROOT=$PKG || exit 1

ln -s $PRGNAM $PKG/usr/lib${LIBDIRSUFFIX}/qt-$VERSION

mkdir -p $PKG/usr/bin
for BIN in $PKG/usr/lib${LIBDIRSUFFIX}/$PRGNAM/bin/*; do
  TMP_FILE=$(echo $BIN | sed -e "s|$PKG||")
  case $(basename $BIN) in
    syncqt.pl)
      ln -s $TMP_FILE $PKG/usr/bin/$(basename $BIN)
      ;;
    *)
      ln -s $TMP_FILE $PKG/usr/bin/$(basename $BIN)-$PRGNAM
      ;;
  esac
done

mkdir -p $PKG/etc/profile.d
echo "IyEvYmluL3NoCiMgRW52aXJvbm1lbnQgdmFyaWFibGVzIGZvciB0aGUgUXQgcGFja2FnZS4KIwoj
IEl0J3MgYmVzdCB0byB1c2UgdGhlIGdlbmVyaWMgZGlyZWN0b3J5IHRvIGF2b2lkCiMgY29tcGls
aW5nIGluIGEgdmVyc2lvbi1jb250YWluaW5nIHBhdGg6CmlmIFsgLWQgL3Vzci9saWJATElCRElS
U1VGRklYQC9xdDUgXTsgdGhlbgogIFFUNURJUj0vdXNyL2xpYkBMSUJESVJTVUZGSVhAL3F0NQpl
bHNlCiAgIyBGaW5kIHRoZSBuZXdlc3QgUXQgZGlyZWN0b3J5IGFuZCBzZXQgJFFUNURJUiB0byB0
aGF0OgogIGZvciBxdGQgaW4gL3Vzci9saWJATElCRElSU1VGRklYQC9xdDUtKiA7IGRvCiAgICBp
ZiBbIC1kICRxdGQgXTsgdGhlbgogICAgICBRVDVESVI9JHF0ZAogICAgZmkKICBkb25lCmZpClBB
VEg9IiRQQVRIOiRRVDVESVIvYmluIgpleHBvcnQgUVQ1RElSCg==" | base64 -d > $PKG/etc/profile.d/$PRGNAM.sh
sed -e "s|@LIBDIRSUFFIX@|${LIBDIRSUFFIX}|g" $PKG/etc/profile.d/$PRGNAM.sh \
  > $PKG/etc/profile.d/$PRGNAM.sh

echo "IyEvYmluL2NzaAojIEVudmlyb25tZW50IHBhdGggdmFyaWFibGVzIGZvciB0aGUgUXQgcGFja2Fn
ZToKaWYgKCAhICQ/UVQ1RElSICkgdGhlbgogICAgIyBJdCdzIGJlc3QgdG8gdXNlIHRoZSBnZW5l
cmljIGRpcmVjdG9yeSB0byBhdm9pZAogICAgIyBjb21waWxpbmcgaW4gYSB2ZXJzaW9uLWNvbnRh
aW5pbmcgcGF0aDoKICAgIGlmICggLWQgL3Vzci9saWJATElCRElSU1VGRklYQC9xdDUgKSB0aGVu
CiAgICAgICAgc2V0ZW52IFFUNURJUiAvdXNyL2xpYkBMSUJESVJTVUZGSVhAL3F0NQogICAgZWxz
ZQogICAgICAgICMgRmluZCB0aGUgbmV3ZXN0IFF0IGRpcmVjdG9yeSBhbmQgc2V0ICRRVDVESVIg
dG8gdGhhdDoKICAgICAgICBmb3JlYWNoIHF0ZCAoIC91c3IvbGliQExJQkRJUlNVRkZJWEAvcXQ1
LSogKQogICAgICAgICAgICBpZiAoIC1kICRxdGQgKSB0aGVuCiAgICAgICAgICAgICAgICBzZXRl
bnYgUVQ1RElSICRxdGQKICAgICAgICAgICAgZW5kaWYKICAgICAgICBlbmQKICAgIGVuZGlmCmVu
ZGlmCnNldCBwYXRoID0gKCAkcGF0aCAkUVQ1RElSL2JpbiApCg==" | base64 -d > $PKG/etc/profile.d/$PRGNAM.csh
sed -e "s|@LIBDIRSUFFIX@|${LIBDIRSUFFIX}|g" $PKG/etc/profile.d/$PRGNAM.csh \
  > $PKG/etc/profile.d/$PRGNAM.csh
chmod 0755 $PKG/etc/profile.d/*

cat > $PKG/usr/lib${LIBDIRSUFFIX}/pkgconfig/Qt5.pc << EOF
prefix=/usr/lib${LIBDIRSUFFIX}/$PRGNAM
bindir=\${prefix}/bin
datadir=\${prefix}
docdir=/usr/doc/$PRGNAM-$VERSION
archdatadir=\${prefix}
examplesdir=\${prefix}/examples
headerdir=/usr/include/$PRGNAM
importdir=\${prefix}/imports
qmldir=\${prefix}/qml
libdir=/usr/lib${LIBDIRSUFFIX}
libexec=\${prefix}/libexec
moc=\${bindir}/moc
plugindir=\${prefix}/plugins
qmake=\${bindir}/qmake
sysconfdir=/etc/xdg
translationdir=\${prefix}/translations

Name: Qt5
Description: Qt5 Configuration
Version: $VERSION
EOF

# Fix internal linking for Qt5WebKit.pc and Qt5WebEngineCore.pc.
sed -i \
  -e "s|-Wl,-whole-archive -lWebKit1 -Wl,-no-whole-archive -L${PWD}/qtwebkit/Source/WebKit[^ ]* ||" \
  -e "s|-Wl,-whole-archive -lWebKit2 -Wl,-no-whole-archive -L${PWD}/qtwebkit/Source/WebKit2[^ ]* ||" \
  -e "s|-Wl,-whole-archive -lWebCore -Wl,-no-whole-archive -L${PWD}/qtwebkit/Source/WebCore[^ ]* ||" \
  -e "s|-Wl,-whole-archive -lANGLE -Wl,-no-whole-archive -L${PWD}/qtwebkit/Source/ThirdParty/ANGLE[^ ]* ||" \
  -e "s|-Wl,-whole-archive -lJavaScriptCore -Wl,-no-whole-archive -L${PWD}/qtwebkit/Source/JavaScriptCore[^ ]* ||" \
  -e "s|-Wl,-whole-archive -lWTF -Wl,-no-whole-archive -L${PWD}/qtwebkit/Source/WTF[^ ]* ||" \
  -e "s|-Wl,-whole-archive -lleveldb -Wl,-no-whole-archive -L${PWD}/qtwebkit/Source/ThirdParty/leveldb[^ ]* ||" \
  $PKG/usr/lib${LIBDIRSUFFIX}/pkgconfig/Qt5WebKit.pc

sed -i 's|-Wl,--whole-archive.*-Wl,--no-whole-archive||' $PKG/usr/lib${LIBDIRSUFFIX}/pkgconfig/Qt5WebEngineCore.pc

# While we are at it, there isn't any reason to keep references to $PKG in the *.prl files.
for PRL in $(find $PKG -name "*\.prl"); do
  sed -i '/^QMAKE_PRL_BUILD_DIR/d' $PRL
done

# One more for the road.
sed -i "s|$PWD/qtbase|/usr/lib${LIBDIRSUFFIX}/$PRGNAM|" \
  $PKG/usr/lib${LIBDIRSUFFIX}/$PRGNAM/mkspecs/modules/qt_lib_bootstrap_private.pri
  
# Entradas de menu
mkdir -p $PKG/usr/share/applications/
echo "W0Rlc2t0b3AgRW50cnldCk5hbWU9UXQ1IEFzc2lzdGFudApDb21tZW50PVNob3dzIFF0NSBkb2N1
bWVudGF0aW9uIGFuZCBleGFtcGxlcwpFeGVjPS91c3IvbGliQExJQkRJUkAvcXQ1L2Jpbi9hc3Np
c3RhbnQKSWNvbj1hc3Npc3RhbnQtcXQ1ClRlcm1pbmFsPWZhbHNlClR5cGU9QXBwbGljYXRpb24K
Q2F0ZWdvcmllcz1RdDtEZXZlbG9wbWVudDtEb2N1bWVudGF0aW9uOwo=" | base64 -d > $PKG/usr/share/applications/assistant-qt5.desktop

echo "W0Rlc2t0b3AgRW50cnldCk5hbWU9UXQ1IERlc2lnbmVyCkdlbmVyaWNOYW1lPUludGVyZmFjZSBE
ZXNpZ25lcgpDb21tZW50PURlc2lnbiBHVUlzIGZvciBRdDUgYXBwbGljYXRpb25zCkV4ZWM9L3Vz
ci9saWJATElCRElSQC9xdDUvYmluL2Rlc2lnbmVyCkljb249ZGVzaWduZXItcXQ1Ck1pbWVUeXBl
PWFwcGxpY2F0aW9uL3gtZGVzaWduZXI7ClRlcm1pbmFsPWZhbHNlClR5cGU9QXBwbGljYXRpb24K
Q2F0ZWdvcmllcz1RdDtEZXZlbG9wbWVudDsK" | base64 -d > $PKG/usr/share/applications/designer-qt5.desktop

echo "W0Rlc2t0b3AgRW50cnldCk5hbWU9UXQ1IExpbmd1aXN0CkNvbW1lbnQ9QWRkIHRyYW5zbGF0aW9u
cyB0byBRdDUgYXBwbGljYXRpb25zCkV4ZWM9L3Vzci9saWJATElCRElSQC9xdDUvYmluL2xpbmd1
aXN0Ckljb249bGluZ3Vpc3QtcXQ1Ck1pbWVUeXBlPXRleHQvdm5kLnRyb2xsdGVjaC5saW5ndWlz
dDthcHBsaWNhdGlvbi94LWxpbmd1aXN0OwpUZXJtaW5hbD1mYWxzZQpUeXBlPUFwcGxpY2F0aW9u
CkNhdGVnb3JpZXM9UXQ7RGV2ZWxvcG1lbnQ7Cg==" | base64 -d > $PKG/usr/share/applications/linquist-qt5.desktop

echo "W0Rlc2t0b3AgRW50cnldCk5hbWU9UXQ1IFFEYnVzVmlld2VyIApHZW5lcmljTmFtZT1RdDUgRC1C
dXMgRGVidWdnZXIKQ29tbWVudD1EZWJ1ZyBELUJ1cyBhcHBsaWNhdGlvbnMKRXhlYz0vdXNyL2xp
YkBMSUJESVJAL3F0NS9iaW4vcWRidXN2aWV3ZXIKSWNvbj1xZGJ1c3ZpZXdlci1xdDUKVGVybWlu
YWw9ZmFsc2UKVHlwZT1BcHBsaWNhdGlvbgpDYXRlZ29yaWVzPVF0O0RldmVsb3BtZW50O0RlYnVn
Z2VyOwo=" | base64 -d > $PKG/usr/share/applications/qdbusviewer-qt5.desktop

sed -i "s|@LIBDIR@|$LIBDIRSUFFIX|" $PKG/usr/share/applications/*

install -D -m 0644 qttools/src/assistant/assistant/images/assistant-128.png \
  $PKG/usr/share/icons/hicolor/128x128/apps/assistant-qt5.png
install -D -m 0644 qttools/src/designer/src/designer/images/designer.png \
  $PKG/usr/share/icons/hicolor/128x128/apps/designer-qt5.png
install -D -m 0644 qttools/src/qdbus/qdbusviewer/images/qdbusviewer-128.png \
  $PKG/usr/share/icons/hicolor/128x128/apps/qdbusviewer-qt5.png
for i in 16 32 48 64 128; do
  install -D -m 0644 qttools/src/linguist/linguist/images/icons/linguist-${i}-32.png \
    $PKG/usr/share/icons/hicolor/${i}x${i}/apps/linguist-qt5.png
done

# Remove executable bits from files.
find $PKG \( -name "*.qml" -o -name "*.app" \) -perm 755 -exec chmod 644 '{}' \;
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales
