#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20150906

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	WEB=http://sourceforge.net/projects/yad-dialog/files/
	VERSION=`curl -s $WEB|grep /latest|cut -d "-" -f3|cut -d "t" -f1|sed "s/.$//g"`
	PRGNAM=yad
	echo -ne "\033]2;${PRGNAM}_updater\007"
}

# Si el paquete no existe se descargara de internet
F_download(){
	if [ ! -f ${PRGNAM}-${VERSION}.tar.xz ]; then
	echo 
	echo "$CYAN"Descargando sources de ${PRGNAM}-${VERSION}"$CIERRE"
	sleep 1
	aria2c -x 3 ${WEB}${PRGNAM}-${VERSION}.tar.xz
	fi
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Descomprimiendo ..."$CIERRE"
sleep 1
rm -rf $PRGNAM-$VERSION
tar xvf $PRGNAM-$VERSION.tar.xz
cd $PRGNAM-$VERSION
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 -o -perm 511 \) \
 -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
 -exec chmod 644 {} \;

 
 
if [ $VERSION = 0.29.0 ]; then
echo 
echo "$VERDE"Detectada version 0.29.0 parcheando ..."$CIERRE"
sleep 1
cat > $PRGNAM.patch << "EOF"
diff -ru a/src/main.c b/src/main.c
--- a/src/main.c	2015-07-22 22:02:17.451773876 -0400
+++ b/src/main.c	2015-07-22 22:02:34.618281726 -0400
@@ -765,6 +765,7 @@
         ret = yad_print_run ();
         break;
 
+#ifdef HAVE_HTML
       case YAD_MODE_HTML:
         /* Webkit doesn't handle focus for child dialogs when gtk_dialog_run() is used */
         /* FIXME: maybe this solution must be expanded to all dialogs */
@@ -775,6 +776,7 @@
 
         gtk_main ();
         break;
+#endif
 
       default:
         dialog = create_dialog ();

EOF

patch -p1 -i $TMP/$PRGNAM-$VERSION/$PRGNAM.patch
fi


echo 
echo "$VERDE"Configurando ..."$CIERRE"
sleep 1

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --mandir=/usr/man \
  --enable-icon-browser \
  --disable-html \
  --docdir=/usr/doc/$PRGNAM-$VERSION \
  --build=$ARCH-slackware-linux

echo 
echo "$VERDE"Compilamos ..."$CIERRE"
sleep 1  
make  || exit 1
make install-strip DESTDIR=$PKG
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
F_download
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales
