#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20151116

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	WEB=http://es.maxthon.com/
	VERSION=`curl -s $WEB | grep i386.tgz | cut -d "/" -f6 | cut -d- -f4 | sed "s/ //g"`
	PRGNAM=maxthon
	echo -ne "\033]2;${PRGNAM}_updater\007"
	DESCARGA=http://dl.maxthon.com/linux/tars/maxthon-browser-stable-$VERSION-i386.tgz
}

# Creamos directorios extra
F_extradirs(){
mkdir -p $PKG/{usr/bin,opt/$PRGNAM,usr/share/pixmaps,usr/share/applications}
}

# Si el paquete no existe se descargara de internet
F_download(){
	if [ ! -f maxthon-browser-stable-$VERSION-i386.tgz ]; then
	echo ""
	echo "$CYAN"Descargando sources de $PRGNAM-$VERSION"$CIERRE"
	sleep 1
	aria2c -x 3 $DESCARGA
	fi
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo ""
echo "$VERDE"Descomprimiendo ..."$CIERRE"
sleep 1
tar xvf maxthon-browser-stable-$VERSION-i386.tgz
cd $PRGNAM
# Copiamos recursivamente y creamos lanzador desktop
cp -rf ./* $PKG/opt/$PRGNAM
ln -s /opt/$PRGNAM/maxthon-browser $PKG/usr/bin/maxthon
cp -r $PKG/opt/$PRGNAM/product_logo_48.png $PKG/usr/share/pixmaps/$PRGNAM.png
chmod 4755 $PKG/opt/maxthon/maxthon_sandbox
echo "[Desktop Entry]
Categories=Network;
Name=Maxthon
Icon=$PRGNAM
Exec=maxthon %U --user-data-dir=/.config/$PRGNAM
StartupNotify=true
Terminal=false
Type=Application" > $PKG/usr/share/applications/$PRGNAM.desktop

# Eliminando locales extras
# Funcion extraida del script cleandir escrito en su mayoria por geminis_demon
RMDIR='rmdir -p --ignore-fail-on-non-empty'
	if [ -d $PKG/opt/maxthon/locales ]; then
	cd $PKG/opt/maxthon/locales
	IDIOMAS=$(ls|cut -d '/' -f1|grep -v -x 'es.pak'|grep -v -x 'en-US.pak')
	rm -Rf $IDIOMAS
	$RMDIR $PKG/opt/maxthon/locales
	fi
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Creamos directorios extra
F_extradirs
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura i386
#Comprobamos version instalada del script
f_versionInstalada
#Si no existe el fichero se descargara
F_download
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales