#!/bin/bash

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20151116

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
#Definicion de variables
F_variables() {
	PRGNAM=acsccid
	WEB="http://acsccid.sourceforge.net/"
	echo -ne "\033]2;${PRGNAM}_updater\007"
	DOWNLOAD=$(curl -s $WEB | grep "acsccid-" | grep -Po 'href="\K.*(?=">)')
	VERSION=$(echo "$DOWNLOAD" |rev | cut -d/ -f1 | cut -d. -f3- | cut -d- -f1 | rev )
	EXTENSION=tar.bz2
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="pcsc-lite"
f_dependencias
}

#Configurando
F_compilar() {
echo ""
echo "$VERDE"Configurando ..."$CIERRE"
sleep 1
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --sysconfdir=/etc \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --mandir=/usr/man \
  --docdir=/usr/doc/$PRGNAM-$VERSION \
  --build=$ARCH-slackware-linux

make  || exit 1
make install DESTDIR=$PKG
}


###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del script
f_versionInstalada
#Comprobar dependencias
F_dependencias
#Descargamos el paquete si no existe
f_download
#Preparamos entorno
f_preparar
#Compilamos el paquete
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales 