#!/bin/bash

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20150630

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
#Definicion de variables
F_variables() {
	PRGNAM=acsccid
	WEB="http://acsccid.sourceforge.net/"
	echo -ne "\033]2;${PRGNAM}_updater\007"
	DOWNLOAD=$(curl -s http://acsccid.sourceforge.net/ | grep "acsccid-" | grep -Po 'href="\K.*(?=">)')
	VERSION=$(echo "$DOWNLOAD" |rev | cut -d/ -f1 | cut -d. -f3- | cut -d- -f1 | rev )

}

# Comprobar dependencias
F_dependencias(){
	echo 
	if ls /usr/lib/libusb*so* >/dev/null; then
	EXIST=`echo "$VERDE"Instalada"$CIERRE"`
	else
	EXIST=`echo "$ROJO"No Instalada"$CIERRE"`
	SALIR=1
	fi
	echo "$ROSA"Comprobando dependencias ..."$CIERRE"
	echo
	sleep 3
	echo "$CYAN"Dependencias de este paquete:""
	echo ""
	echo "$AMARILLO"libusb"$CIERRE: $EXIST"
	
	if [ $SALIR ]; then
	  exit
	fi
	
	if hash pcscd 2>/dev/null; then
	  EXIST=`echo "$VERDE"Instalada"$CIERRE"`
	else
	  EXIST=`echo "$ROJO"No Instalada"$CIERRE"`
	fi
	echo "$AMARILLO"pcsc-lite"$CIERRE: $EXIST"
	
	if ! hash pcscd 2>/dev/null; then
		echo ""
		echo ""$ROJO"No se cumplen los requisitos"$CIERRE"... "$VERDE"resolviendo"$CIERRE"..."
		sleep 3
		cd /opt/wifislax-updaters/Sistema/ && xterm /opt/wifislax-updaters/Sistema/pcsc-lite_updater
	fi

	echo ""
	echo "$VERDE"Bien ..podemos continuar"$CIERRE"
	echo ""
	sleep 3
}

# Si el paquete no existe se descargara de internet
F_descargaPaquete() {
	if [ ! -f $PRGNAM-$VERSION.tar.bz2 ]; then
	echo ""
	echo "$CYAN"Descargando sources de $PRGNAM-$VERSION"$CIERRE"
	sleep 3
	aria2c -x 3 $DOWNLOAD
	fi
}

#Descomprime el fichero descargado
F_descomprime() {
	echo ""
	echo "$VERDE"Descomprimiendo ..."$CIERRE"
	sleep 3
	rm -rf $PRGNAM-$VERSION
	tar xvf $PRGNAM-$VERSION.tar.bz2
	cd $PRGNAM-$VERSION
	chown -R root:root .
	find -L . \
	\( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
	  -o -perm 511 \) -exec chmod 755 {} \; -o \
	\( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
	-o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
}

#Configurando
F_compilar() {
echo ""
echo "$VERDE"Configurando ..."$CIERRE"
sleep 3
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --sysconfdir=/etc \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --mandir=/usr/man \
  --docdir=/usr/doc/$PRGNAM-$VERSION \
  --build=$ARCH-slackware-linux

make -j$NUCLEOS
make install DESTDIR=$PKG

}


###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobar dependencias
F_dependencias
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del script
f_versionInstalada
#Descargamos el paquete si no existe
F_descargaPaquete
#Descomprimimos el paquete descargado 
F_descomprime
#Compilamos el paquete
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales 