#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20151101

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=apulse
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://github.com/i-rinat/apulse/releases
	VERSION=`curl -s $WEB | grep .tar.gz | head -1 | cut -d v -f3 | cut -d t -f-1 | sed "s/.$//g"`
	EXTENSION=zip
	SOURCES=v$VERSION.$EXTENSION
	DOWNLOAD=https://github.com/i-rinat/apulse/archive/$SOURCES
	
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
mkdir -pv build
cd build
cmake \
  -DAPULSEPATH=/usr/lib${LIBDIRSUFFIX}/apulse \
  -DAPULSE_SEARCH_PATHS=/usr/lib/apulse:/usr/lib${LIBDIRSUFFIX}/apulse \
  -DCMAKE_INSTALL_PREFIX=/usr \
  -DCMAKE_BUILD_TYPE=Release \
  ..
make  VERBOSE=1|| exit 1
make install DESTDIR=$PKG
cd ..

}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales
