#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20160817

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=aubio
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=http://aubio.org/pub/
	VERSION=`curl -s $WEB | grep tar.bz2 | tail -1 | cut -d- -f3 | cut -d t -f1 | sed "s/.$//g"`
	EXTENSION=tar.bz2
	SOURCES=${PRGNAM}-${VERSION}.$EXTENSION
	DOWNLOAD=${WEB}$SOURCES
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="ffmpeg"
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Configurando ..."$CIERRE"
python waf configure --prefix=/usr --enable-fftw3f
echo 
echo "$VERDE"Compilando ..."$CIERRE"
python waf build $MAKEFLAGS
python waf --destdir=$PKG install
python setup.py install --root=$PKG --optimize=1
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
# Comprobar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales