#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20160722

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=cryptopp
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://sourceforge.net/projects/$PRGNAM/files/
	VERSION=`curl -s $WEB | grep zip | cut -d "/" -f8 | sed "s/ //g"`
	RAMA=`echo $VERSION | sed "s/[.]//g"`
	EXTENSION=zip
	SOURCES=$PRGNAM$RAMA.$EXTENSION
	DOWNLOAD=https://downloads.sourceforge.net/project/$PRGNAM/$PRGNAM/$VERSION/$SOURCES
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1

# Fix Makefile to install correctly on x86_64.
sed -i "s%(PREFIX)/lib%(PREFIX)/lib${LIBDIRSUFFIX}%g" GNUmakefile

make dynamic CFLAGS="$SLKCFLAGS" CXXFLAGS="-DNDEBUG $SLKCFLAGS"
make install PREFIX=$PKG/usr
( cd $PKG/usr/lib${LIBDIRSUFFIX}
  mv libcryptopp.so libcryptopp-${VERSION}.so.0
  ln -s libcryptopp-${VERSION}.so.0 libcryptopp.so )
  
# This is empty
rmdir $PKG/usr/bin

# Install a pkgconfig file
cat > $PRGNAM.pc << "EOF"
prefix=/usr
exec_prefix=${prefix}
libdir=${prefix}/lib@LIBDIRSUFFIX@
includedir=${prefix}/include/cryptopp

Name: Crypto++
Description: A free C++ class library of cryptographic schemes
Version: 5.6.2
URL: http://www.cryptopp.com
Requires:
Conflicts:
Libs: -L${libdir} -lcryptopp
Cflags: -I${includedir}

EOF

# Install a pkgconfig file
mkdir $PKG/usr/lib$LIBDIRSUFFIX/pkgconfig
sed "s|@LIBDIRSUFFIX@|$LIBDIRSUFFIX|" ./$PRGNAM.pc \
  > $PKG/usr/lib$LIBDIRSUFFIX/pkgconfig/$PRGNAM.pc
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales