#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20160328

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=dcadec
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://github.com/foo86/dcadec
	VERSION=0.2.0
	EXTENSION=tar.gz
	SOURCES=v$VERSION.$EXTENSION
	DOWNLOAD=$WEB/archive/$SOURCES
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1

export CONFIG_SHARED='TRUE'

make || exit 1
export CONFIG_SHARED='TRUE'
export PREFIX='/usr'
export LIBDIR="/usr/lib$LIBDIRSUFFIX"

make DESTDIR="$PKG" install
mv "$PKG"/usr/bin/dcadec{,-hd}
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales