#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20151008

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	WEB=https://www.ffmpeg.org/download.html
	VERSION=`curl -s $WEB | grep latest | head -1 | cut -d "w" -f1 | sed "s/ //g"`
	PRGNAM=ffmpeg
	echo -ne "\033]2;${PRGNAM}_updater\007"
	EXTENSION=tar.bz2
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	DOWNLOAD=http://ffmpeg.org/releases/$SOURCES
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
chown -R root:root .
chmod -R u+w,go+r-w,a-s .

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
sed -i 's/-lflite"/-lflite -lasound"/' configure &&
  ./configure \
    --prefix=/usr \
    --libdir=/usr/lib${LIBDIRSUFFIX} \
    --shlibdir=/usr/lib${LIBDIRSUFFIX} \
    --disable-debug \
    --disable-doc \
    --disable-htmlpages \
    --disable-libpulse \
    --disable-manpages \
    --disable-podpages \
    --disable-static \
    --disable-stripping \
    --disable-txtpages \
    --enable-avfilter \
    --enable-avisynth \
    --enable-avresample \
    --enable-fontconfig \
    --enable-gnutls \
    --enable-gpl \
    --enable-libass \
    --enable-libbluray \
    --enable-libcaca \
    --enable-libcdio \
    --enable-libfreetype \
    --enable-libfribidi \
    --enable-libgsm \
    --enable-libmodplug \
    --enable-libmp3lame \
    --enable-libopencore_amrnb \
    --enable-libopencore_amrwb \
    --enable-libopenjpeg \
    --enable-libopus \
    --enable-librtmp \
    --enable-libschroedinger \
    --enable-libspeex \
    --enable-libtheora \
    --enable-libv4l2 \
    --enable-libvorbis \
    --enable-libvpx \
    --enable-libx264 \
    --enable-libx265 \
    --enable-libxvid \
    --enable-pthreads \
    --enable-postproc \
    --enable-runtime-cpudetect \
    --enable-shared \
    --enable-swresample \
    --enable-swscale \
    --enable-vdpau \
    --enable-version3 \
    --enable-opengl \
    --disable-inline-asm \
    --enable-x11grab
  
make  || exit 1
make tools/qt-faststart
make install DESTDIR=$PKG
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del script
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales
