#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20151116

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	WEB=https://www.ffmpeg.org/download.html
	VERSION=`curl -s $WEB | grep latest | head -1 | cut -d "w" -f1 | sed "s/ //g"`
	PRGNAM=ffmpeg
	echo -ne "\033]2;${PRGNAM}_updater\007"
	EXTENSION=tar.bz2
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	DOWNLOAD=http://ffmpeg.org/releases/$SOURCES
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
# Parche necesario por libvpx-1.5
echo "RnJvbSA2NTQwZmUwNGEzZjlhMTFiYTcwODRhNDliM2VlNWZhMmZjNWIzMmFiIE1vbiBTZXAgMTcg
MDA6MDA6MDAgMjAwMQpGcm9tOiBKYW1lcyBaZXJuIDxqemVybkBnb29nbGUuY29tPgpEYXRlOiBN
b24sIDE5IE9jdCAyMDE1IDIyOjQ0OjExIC0wNzAwClN1YmplY3Q6IFtQQVRDSF0gbGlidnB4ZW5j
OiByZW1vdmUgc29tZSB1bnVzZWQgY3RybCBpZCBtYXBwaW5ncwoKVlA4RV9VUERfRU5UUk9QWSwg
VlA4RV9VUERfUkVGRVJFTkNFLCBWUDhFX1VTRV9SRUZFUkVOQ0Ugd2VyZSByZW1vdmVkCmZyb20g
bGlidnB4IGFuZCB0aGUgcmVtYWluaW5nIHZhbHVlcyB3ZXJlIG5ldmVyIHVzZWQgaGVyZQoKUmV2
aWV3ZWQtYnk6IE1pY2hhZWwgTmllZGVybWF5ZXIgPG1pY2hhZWxAbmllZGVybWF5ZXIuY2M+ClNp
Z25lZC1vZmYtYnk6IEphbWVzIFplcm4gPGp6ZXJuQGdvb2dsZS5jb20+Ci0tLQogbGliYXZjb2Rl
Yy9saWJ2cHhlbmMuYyB8ICAgIDggLS0tLS0tLS0KIDEgZmlsZSBjaGFuZ2VkLCA4IGRlbGV0aW9u
cygtKQoKZGlmZiAtLWdpdCBhL2xpYmF2Y29kZWMvbGlidnB4ZW5jLmMgYi9saWJhdmNvZGVjL2xp
YnZweGVuYy5jCmluZGV4IDVmMzk3ODMuLjk5MjEyMmMgMTAwNjQ0Ci0tLSBhL2xpYmF2Y29kZWMv
bGlidnB4ZW5jLmMKKysrIGIvbGliYXZjb2RlYy9saWJ2cHhlbmMuYwpAQCAtMTA0LDE5ICsxMDQs
MTEgQEAgdHlwZWRlZiBzdHJ1Y3QgVlA4RW5jb2RlckNvbnRleHQgewogCiAvKiogU3RyaW5nIG1h
cHBpbmdzIGZvciBlbnVtIHZwOGVfZW5jX2NvbnRyb2xfaWQgKi8KIHN0YXRpYyBjb25zdCBjaGFy
ICpjb25zdCBjdGxpZHN0cltdID0gewotICAgIFtWUDhFX1VQRF9FTlRST1BZXSAgICAgICAgICAg
PSAiVlA4RV9VUERfRU5UUk9QWSIsCi0gICAgW1ZQOEVfVVBEX1JFRkVSRU5DRV0gICAgICAgICA9
ICJWUDhFX1VQRF9SRUZFUkVOQ0UiLAotICAgIFtWUDhFX1VTRV9SRUZFUkVOQ0VdICAgICAgICAg
PSAiVlA4RV9VU0VfUkVGRVJFTkNFIiwKLSAgICBbVlA4RV9TRVRfUk9JX01BUF0gICAgICAgICAg
ID0gIlZQOEVfU0VUX1JPSV9NQVAiLAotICAgIFtWUDhFX1NFVF9BQ1RJVkVNQVBdICAgICAgICAg
PSAiVlA4RV9TRVRfQUNUSVZFTUFQIiwKLSAgICBbVlA4RV9TRVRfU0NBTEVNT0RFXSAgICAgICAg
ID0gIlZQOEVfU0VUX1NDQUxFTU9ERSIsCiAgICAgW1ZQOEVfU0VUX0NQVVVTRURdICAgICAgICAg
ICA9ICJWUDhFX1NFVF9DUFVVU0VEIiwKICAgICBbVlA4RV9TRVRfRU5BQkxFQVVUT0FMVFJFRl0g
ID0gIlZQOEVfU0VUX0VOQUJMRUFVVE9BTFRSRUYiLAogICAgIFtWUDhFX1NFVF9OT0lTRV9TRU5T
SVRJVklUWV0gPSAiVlA4RV9TRVRfTk9JU0VfU0VOU0lUSVZJVFkiLAotICAgIFtWUDhFX1NFVF9T
SEFSUE5FU1NdICAgICAgICAgPSAiVlA4RV9TRVRfU0hBUlBORVNTIiwKICAgICBbVlA4RV9TRVRf
U1RBVElDX1RIUkVTSE9MRF0gID0gIlZQOEVfU0VUX1NUQVRJQ19USFJFU0hPTEQiLAogICAgIFtW
UDhFX1NFVF9UT0tFTl9QQVJUSVRJT05TXSAgPSAiVlA4RV9TRVRfVE9LRU5fUEFSVElUSU9OUyIs
Ci0gICAgW1ZQOEVfR0VUX0xBU1RfUVVBTlRJWkVSXSAgICA9ICJWUDhFX0dFVF9MQVNUX1FVQU5U
SVpFUiIsCiAgICAgW1ZQOEVfU0VUX0FSTlJfTUFYRlJBTUVTXSAgICA9ICJWUDhFX1NFVF9BUk5S
X01BWEZSQU1FUyIsCiAgICAgW1ZQOEVfU0VUX0FSTlJfU1RSRU5HVEhdICAgICA9ICJWUDhFX1NF
VF9BUk5SX1NUUkVOR1RIIiwKICAgICBbVlA4RV9TRVRfQVJOUl9UWVBFXSAgICAgICAgID0gIlZQ
OEVfU0VUX0FSTlJfVFlQRSIsCi0tIAoxLjcuMTAuNAoK" | base64 -d > $TPM/ffmpeg-2.8.1-libvpxenc-remove-some-unused-ctrl-id-mappings.patch
patch -p1 < $TPM/ffmpeg-2.8.1-libvpxenc-remove-some-unused-ctrl-id-mappings.patch || exit 1

chown -R root:root .
chmod -R u+w,go+r-w,a-s .

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
sed -i 's/-lflite"/-lflite -lasound"/' configure &&
  ./configure \
    --prefix=/usr \
    --libdir=/usr/lib${LIBDIRSUFFIX} \
    --shlibdir=/usr/lib${LIBDIRSUFFIX} \
    --disable-debug \
    --disable-doc \
    --disable-htmlpages \
    --disable-libpulse \
    --disable-manpages \
    --disable-podpages \
    --disable-static \
    --disable-stripping \
    --disable-txtpages \
    --enable-avfilter \
    --enable-avisynth \
    --enable-avresample \
    --enable-fontconfig \
    --enable-gnutls \
    --enable-gpl \
    --enable-libass \
    --enable-libbluray \
    --enable-libcaca \
    --enable-libcdio \
    --enable-libfreetype \
    --enable-libfribidi \
    --enable-libgsm \
    --enable-libmodplug \
    --enable-libmp3lame \
    --enable-libopencore_amrnb \
    --enable-libopencore_amrwb \
    --enable-libopenjpeg \
    --enable-libopus \
    --enable-librtmp \
    --enable-libschroedinger \
    --enable-libspeex \
    --enable-libtheora \
    --enable-libv4l2 \
    --enable-libvorbis \
    --enable-libvpx \
    --enable-libx264 \
    --enable-libx265 \
    --enable-libxvid \
    --enable-pthreads \
    --enable-postproc \
    --enable-runtime-cpudetect \
    --enable-shared \
    --enable-swresample \
    --enable-swscale \
    --enable-vdpau \
    --enable-version3 \
    --enable-opengl \
    --disable-inline-asm \
    --enable-x11grab
  
make  || exit 1
make tools/qt-faststart
make install DESTDIR=$PKG
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del script
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales