#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20151008

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=graphviz
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=http://graphviz.org/pub/graphviz/stable/SOURCES/
	#VERSION=`curl -s $WEB | grep graphviz-[0-9] | tail -1 | cut -d- -f3 | cut -d t -f1 | sed "s/.$//g"`
	VERSION=2.38.0
	EXTENSION=tar.gz
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	DOWNLOAD=http://pkgs.fedoraproject.org/repo/pkgs/$PRGNAM/$SOURCES/5b6a829b2ac94efcd5fa3c223ed6d3ae/$SOURCES
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
# Parcheamos
if [ $VERSION = 2.38.0 ]; then
echo 
echo "$VERDE""Version detectada 2.38.0 aplicando parche...""$CIERRE"
sleep 1
cat > graphviz.patch << "EOF"
diff -Naur old/lib/cgraph/scan.l new/lib/cgraph/scan.l
--- old/lib/cgraph/scan.l	2014-04-13 10:40:25.000000000 -1000
+++ new/lib/cgraph/scan.l	2014-12-02 08:54:21.285050735 -1000
@@ -149,7 +149,7 @@
 	agxbput(&xb,buf);
 	agxbput(&xb,fname);
 	agxbput(&xb, " splits into two tokens\n");
-	agerr(AGWARN,agxbuse(&xb));
+	agerr(AGWARN, "%s", agxbuse(&xb));
 
 	agxbfree(&xb);
 	return 1;
@@ -225,7 +225,7 @@
 	agxbput (&xb, buf);
 	agxbput (&xb, yytext);
 	agxbput (&xb,"'\n");
-	agerr(AGERR,agxbuse(&xb));
+	agerr(AGERR, "%s", agxbuse(&xb));
 	agxbfree(&xb);
 }
 /* must be here to see flex's macro defns */
 
diff -Naur graphviz-2.28.0.orig/tclpkg/gv/gv_php_init.c graphviz-2.28.0/tclpkg/gv/gv_php_init.c
--- graphviz-2.28.0.orig/tclpkg/gv/gv_php_init.c	2011-01-25 17:30:51.000000000 +0100
+++ graphviz-2.28.0/tclpkg/gv/gv_php_init.c	2012-05-30 04:10:40.657221055 +0200
@@ -19,11 +19,13 @@
 
 static size_t gv_string_writer (GVJ_t *job, const char *s, size_t len)
 {
+    TSRMLS_FETCH();
     return PHPWRITE(s, len);
 }
 
 static size_t gv_channel_writer (GVJ_t *job, const char *s, size_t len)
 {
+    TSRMLS_FETCH();
     return PHPWRITE(s, len);
 }

EOF

patch -p1 -i $TMP/$PRGNAM-$VERSION/graphviz.patch || exit 1
fi

echo 
echo "$VERDE"Configurando ..."$CIERRE"
sleep 1

sed "s:ruby-1.9:ruby-2.2:g" -i configure
sed -i 's|/php/modules|/php/extensions|' configure

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
LDFLAGS="-L/usr/lib${LIBDIRSUFFIX}" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --mandir=/usr/man \
  --disable-static \
  --enable-ocaml=no \
  --enable-java=no \
  --build=$ARCH-slackware-linux

echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1
  
make  || exit 1
make install-strip DESTDIR=$PKG

# Config
mkdir -p $PKG/etc/php
echo "; Enable graphviz extension module
; extension=gv.so

; Graphviz' own documentation mentions a "gv.php" file that should
; be included. This file is however not necessary, it is just a
; wrapper class around functions that are already available after
; loading the extension, just leave out the "gv::" prefix.
; In case you still prefer to use the wrapper class you have to
; include it using its absolute path:
; <?php
; include ('/usr/lib@LIBDIRSUFFIX@/graphviz/php/gv.php');
; ?>" > $PKG/etc/php/graphviz.ini

echo '# Dummy content.' > $PKG/usr/lib${LIBDIRSUFFIX}/graphviz/config6

rm -rf $PKG/usr/share/$PRGNAM/doc
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales
