#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20151008

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	WEB=https://www.kernel.org/pub/software/network/iw/
	VERSION=`curl -s $WEB | grep .xz | tail -1 | cut -d- -f-2 | cut -d '"' -f2 | cut -d "t" -f-1 | cut -d "-" -f 2 | sed "s/.$//g" | sed "s/ //g"`
	PRGNAM=iw
	echo -ne "\033]2;${PRGNAM}_updater\007"
	EXTENSION=tar.xz
	SOURCES=${PRGNAM}-$VERSION.$EXTENSION
	DOWNLOAD=${WEB}$SOURCES
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
# Configuramos paquete
echo ""
echo "$VERDE"Configurando ..."$CIERRE"
sleep 3
make clean
make  || make || exit 1
make install \
  BINDIR=/usr/sbin \
  MANDIR=/usr/man \
  DESTDIR=$PKG || exit 1
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del script
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales
