#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20151104

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=libaacs
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=http://www.videolan.org/developers/$PRGNAM.html
	VERSION=`curl -s $WEB|grep Latest|tail -1|cut -d ' ' -f5|cut -d '<' -f-1`
	EXTENSION=tar.bz2
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	DOWNLOAD=ftp://ftp.videolan.org/pub/videolan/$PRGNAM/$VERSION/$SOURCES
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Configurando ..."$CIERRE"
sleep 1

# Fix CL/RF formatting.
sed -e 's/\r//g' KEYDB.cfg > KEYDB.cfg.new
touch -r KEYDB.cfg KEYDB.cfg.new
mv KEYDB.cfg.new KEYDB.cfg

if [ $VERSION = 0.8.1 ]; then
echo '--- libaacs-0.8.1/src/libaacs/crypto.c
+++ libaacs-0.8.1/src/libaacs/crypto.c
@@ -37,6 +37,7 @@
 
 #ifdef HAVE_PTHREAD_H
 #if GCRYPT_VERSION_NUMBER < 0x010600
+#include <errno.h>
 #include <pthread.h>
 #endif
 #endif

' > $TMP/libaacs-0.8.1-include-errno.patch
patch -p1 < $TMP/libaacs-0.8.1-include-errno.patch
fi

CFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --disable-dependency-tracking \
  --disable-silent-rules \
  --disable-static \
  --build=$ARCH-slackware-linux

echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1

make || exit 1
make install DESTDIR=$PKG || exit 1
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales