#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20160413

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	if [ $ARCH = i586 ]; then
	ARCH=i486
	fi
	PRGNAM=libgcrypt11
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=http://slackware.cs.utah.edu/pub/slackware/slackware${LIBDIRSUFFIX}-14.1/slackware${LIBDIRSUFFIX}/n
	VERSION=1.5.3
	EXTENSION=txz
	SOURCES=libgcrypt-$VERSION-$ARCH-1.$EXTENSION
	DOWNLOAD=$WEB/$SOURCES
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
tar xvf $SOURCES
mkdir -p $PKG/lib${LIBDIRSUFFIX}
cp -rf $TMP/lib${LIBDIRSUFFIX}/libgcrypt.so.11.8.2 $PKG/lib${LIBDIRSUFFIX}/libgcrypt.so.11
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales