#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20151005

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=libmicrohttpd
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB="http://ftp.gnu.org"
	WEB_contenido=$(curl -sk $WEB/gnu/$PRGNAM/ |grep -Po 'href="\K.*(?=">)' | rev | cut -d. -f3-|rev | cut -d\" -f1 )
	VERSION=$(echo "$WEB_contenido" | grep -v "\.sig" | grep "tar.gz" | tail -1|sed "s/$PRGNAM//g" | cut -d- -f2 | rev | cut -d"." -f3- | rev)
	EXTENSION=tar.gz
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	DOWNLOAD="$WEB/gnu/$PRGNAM/$SOURCES"
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --mandir=/usr/man \
  --infodir=/usr/info \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --enable-static=no \
  --build=$ARCH-slackware-linux

make  || exit 1
make install DESTDIR=$PKG

find $PKG/usr/man -type f -exec gzip -9 {} \;

rm -f $PKG/usr/info/dir
gzip -9 $PKG/usr/info/*.info*

}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_compilar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales
