#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20160415

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	if [ ! $ARCH = x86_64 ]; then
	ARCH=i686
	fi
	PRGNAM=libspotify
	SRCNAM=Linux-$ARCH-release
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://developer.spotify.com/technologies/$PRGNAM/
	VERSION=`curl -s $WEB|grep $ARCH-release.tar.gz|cut -d '>' -f4|cut -d '<' -f-1`
	EXTENSION=tar.gz
	SOURCES=$PRGNAM-$VERSION-$SRCNAM.$EXTENSION
	DOWNLOAD=http://developer.spotify.com/download/$PRGNAM/$SOURCES
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1
make prefix="$PKG/usr" install
if [ $ARCH = x86_64 ]; then
mv -f $PKG/usr/lib $PKG/usr/lib${LIBDIRSUFFIX}
sed -i 's/\<lib\>/lib64/g' $PKG/usr/lib64/pkgconfig/libspotify.pc
fi
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales