#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20151008

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=live555
	SRCNAM=live
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=http://sourceforge.net/projects/slackbuildsdirectlinks/files/live555/
	VERSION=`curl -s $WEB | grep live | grep -o [0-9][0-9][0-9][0-9].[0-9][0-9].[0-9][0-9] | head -1`
	EXTENSION=tar.gz
	SOURCES=${SRCNAM}.$VERSION.$EXTENSION
	DOWNLOAD=${WEB}$SOURCES
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
for f in $(find . -type f |xargs grep -l "PREFIX =") ; do echo $f; sed -i -e "/PREFIX =/c\PREFIX = \/usr" $f ; done
for f in $(find . -type f |xargs grep -l "LIBDIR =") ; do echo $f; sed -i -e "/LIBDIR =/c\LIBDIR = \$(PREFIX)\/lib$LIBDIRSUFFIX" $f ; done

cat > live555.pc.in << "EOF"
prefix=%PREFIX%
exec_prefix=${prefix}
includedir=${prefix}/include
libdir=${prefix}/lib%LIBDIRSUFFIX%

Name: live555
Description: C++ multimedia streaming libraries
Version: %VERSION%
Cflags: -I${includedir} -I${includedir}/BasicUsageEnvironment -I${includedir}/UsageEnvironment -I${includedir}/groupsock -I${includedir}/liveMedia

EOF


echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1
./genMakefiles linux-with-shared-libraries
make  || exit 1
make install DESTDIR=$PKG

mkdir -p $PKG/usr/lib${LIBDIRSUFFIX}/pkgconfig
sed -e "s/%VERSION%/$VERSION/" -e "s/%LIBDIRSUFFIX%/$LIBDIRSUFFIX/" -e "s/%PREFIX%/\/usr/" live555.pc.in >$PKG/usr/lib${LIBDIRSUFFIX}/pkgconfig/live555.pc
chmod 0644 $PKG/usr/lib${LIBDIRSUFFIX}/pkgconfig/live555.pc
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales
