#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20150815

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=live555
	SRCNAM=live
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=http://sourceforge.net/projects/slackbuildsdirectlinks/files/live555/
	VERSION=`curl -s $WEB | grep live | grep -o [0-9][0-9][0-9][0-9].[0-9][0-9].[0-9][0-9] | head -1`
	DOWNLOAD=${WEB}${SRCNAM}.$VERSION.tar.gz
}

# Si el paquete no existe se descargara de internet
F_download(){
	if [ ! -f ${SRCNAM}.$VERSION.tar.gz ]; then
	echo 
	echo "$CYAN"Descargando sources de $PRGNAM-$VERSION"$CIERRE"
	sleep 1
	aria2c -x 3 $DOWNLOAD
	fi
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Descomprimiendo ..."$CIERRE"
sleep 1
rm -rf $SRCNAM
tar xvf $SRCNAM.$VERSION.tar.gz
cd $SRCNAM
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

for f in $(find . -type f |xargs grep -l "PREFIX =") ; do echo $f; sed -i -e "/PREFIX =/c\PREFIX = \/usr" $f ; done
for f in $(find . -type f |xargs grep -l "LIBDIR =") ; do echo $f; sed -i -e "/LIBDIR =/c\LIBDIR = \$(PREFIX)\/lib$LIBDIRSUFFIX" $f ; done

cat > live555.pc.in << "EOF"
prefix=%PREFIX%
exec_prefix=${prefix}
includedir=${prefix}/include
libdir=${prefix}/lib%LIBDIRSUFFIX%

Name: live555
Description: C++ multimedia streaming libraries
Version: %VERSION%
Cflags: -I${includedir} -I${includedir}/BasicUsageEnvironment -I${includedir}/UsageEnvironment -I${includedir}/groupsock -I${includedir}/liveMedia

EOF


echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1
./genMakefiles linux-with-shared-libraries
make -j$NUCLEOS || exit 1
make install DESTDIR=$PKG

mkdir -p $PKG/usr/lib${LIBDIRSUFFIX}/pkgconfig
sed -e "s/%VERSION%/$VERSION/" -e "s/%LIBDIRSUFFIX%/$LIBDIRSUFFIX/" -e "s/%PREFIX%/\/usr/" live555.pc.in >$PKG/usr/lib${LIBDIRSUFFIX}/pkgconfig/live555.pc
chmod 0644 $PKG/usr/lib${LIBDIRSUFFIX}/pkgconfig/live555.pc
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
F_download
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales
