#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20150906

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=matplotlib
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=http://sourceforge.net/projects/matplotlib/files/
	#VERSION=`curl -s $WEB | grep /latest | cut -d '/' -f 8 | cut -d- -f2`
	VERSION=1.2.0
	DOWNLOAD=http://downloads.sourceforge.net/$PRGNAM/$PRGNAM-$VERSION.tar.gz
}

# Comprobar dependencias
F_dependencias(){
	echo 
	if [ -f /usr/bin/f2py ]; then
	EXIST=`echo "$VERDE"Instalada"$CIERRE"`
	else
	EXIST=`echo "$ROJO"No Instalada"$CIERRE"`
	fi
	echo "$ROSA"Comprobando dependencias ..."$CIERRE"
	echo
sleep 3
	echo "$CYAN"Dependencias de este paquete:""
	echo ""
	echo "$AMARILLO"numpy"$CIERRE: $EXIST"
	if [ ! -f /usr/bin/f2py ]; then
	echo ""
	echo "$ROJO"No se cumplen los requisitos no se puede continuar"$CIERRE"
	echo ""
sleep 3
	exit 1
else
	echo ""
	echo "$VERDE"Bien ..podemos continuar"$CIERRE"
	echo ""
sleep 3
fi
}

# Si el paquete no existe se descargara de internet
F_download(){
	if [ ! -f $PRGNAM-$VERSION.tar.gz ]; then
	echo 
	echo "$CYAN"Descargando sources de $PRGNAM-$VERSION"$CIERRE"
	sleep 3
	aria2c -x 3 $DOWNLOAD
	fi
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Descomprimiendo ..."$CIERRE"
sleep 3
rm -rf $PRGNAM-$VERSION
tar xvf $PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 -o -perm 511 \) \
 -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
 -exec chmod 644 {} \;

mv setup.cfg.template setup.cfg
sed -i "s|#pytz|pytz|" setup.cfg
sed -i "s|#dateutil|dateutil|" setup.cfg

echo ""
echo "$VERDE"Compilando ..."$CIERRE"
sleep 3
python setup.py install --root $PKG
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Compronar dependencias
F_dependencias
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
F_download
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales
