#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20160505

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=matplotlib
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://sourceforge.net/projects/${PRGNAM}/files/${PRGNAM}
	VERSION=`curl -s $WEB/|grep -m 1 "<tr title="|cut -d '"' -f2|cut -d- -f2|sed "s/ //g"`
	EXTENSION=tar.gz
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	DOWNLOAD=https://sourceforge.net/projects/${PRGNAM}/files/${PRGNAM}/${PRGNAM}-$VERSION/$SOURCES
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="numpy python-dateutil pytz six tornado pyparsing"
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
mv setup.cfg.template setup.cfg
sed -i "s|#pytz|pytz|" setup.cfg
sed -i "s|#dateutil|dateutil|" setup.cfg

echo ""
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1
python setup.py install --root $PKG
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
#Compronar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales