#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20151020

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	WEB=http://freedesktop.org/software/pulseaudio/releases/
	VERSION=`curl -s $WEB |grep -o "[0-9].*.tar.xz" |tail -1| cut -d '-' -f2|sed 's/.tar.xz//g'`
	PRGNAM=pulseaudio
	echo -ne "\033]2;${PRGNAM}_updater\007"
	EXTENSION=tar.xz
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	DOWNLOAD=${WEB}$SOURCES
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){

# Parcheamos
echo "
LS0tIHNyYy9NYWtlZmlsZS5hbS5vcmlnCTIwMTQtMDItMTQgMjM6NDU6NDUuMDAwMDAwMDAwICsx
MDAwCisrKyBzcmMvTWFrZWZpbGUuYW0JMjAxNC0xMC0yNiAyMTo1OTozMy4yMjAyMzQzMTcgKzEw
MDAKQEAgLTE5LDYgKzE5LDggQEAKICMgRm91bmRhdGlvbiwgSW5jLiwgNTkgVGVtcGxlIFBsYWNl
LCBTdWl0ZSAzMzAsIEJvc3RvbiwgTUEgMDIxMTEtMTMwNwogIyBVU0EuCiAKKy5OT1RQQVJBTExF
TDoKKwogIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMKICMgICAgICAgRXh0cmEg
ZGlyZWN0b3JpZXMgICAgICAgICAjCiAjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMj
IwotLS0gTWFrZWZpbGUuYW0ub3JpZwkyMDE0LTAxLTI0IDA0OjU3OjU1LjAwMDAwMDAwMCArMTAw
MAorKysgTWFrZWZpbGUuYW0JMjAxNC0xMC0yNiAyMTo1ODo0Ny4wOTA2MjIxODkgKzEwMDAKQEAg
LTE1LDYgKzE1LDggQEAKICMgRm91bmRhdGlvbiwgSW5jLiwgNTkgVGVtcGxlIFBsYWNlLCBTdWl0
ZSAzMzAsIEJvc3RvbiwgTUEgMDIxMTEtMTMwNwogIyBVU0EuCiAKKy5OT1RQQVJBTExFTDoKKwog
QUNMT0NBTF9BTUZMQUdTID0gLUkgbTQKIAogRVhUUkFfRElTVCA9IFwK" | base64 -d > $TMP/020_no-parallel-make.diff

echo "
LS0tIHNoZWxsLWNvbXBsZXRpb24vYmFzaC9wdWxzZWF1ZGlvLm9yaWcJMjAxNS0wMi0xMyAwMDox
MDozNS4wMDAwMDAwMDAgKzEwMDAKKysrIHNoZWxsLWNvbXBsZXRpb24vYmFzaC9wdWxzZWF1ZGlv
CTIwMTUtMDktMTIgMTE6MDk6MzYuOTQ4MjIyOTI2ICsxMDAwCkBAIC0xLDM5ICsxLDQ1IEBACiAj
IS9iaW4vYmFzaAogCiBfX2NhcmRzICgpIHsKKyAgICAocGFjdGwgbGlzdCBjYXJkcyBzaG9ydCAy
PiAvZGV2L251bGwpIHxcCiAgICAgd2hpbGUgSUZTPSQnXHQnIHJlYWQgaWR4IG5hbWUgXzsgZG8K
ICAgICAgICAgcHJpbnRmICIlcyAlc1xuIiAiJGlkeCIgIiRuYW1lIgotICAgIGRvbmUgPCA8KHBh
Y3RsIGxpc3QgY2FyZHMgc2hvcnQgMj4gL2Rldi9udWxsKQorICAgIGRvbmUKIH0KIAogX19zaW5r
cyAoKSB7CisgICAgKHBhY3RsIGxpc3Qgc2lua3Mgc2hvcnQgMj4gL2Rldi9udWxsKSB8XAogICAg
IHdoaWxlIElGUz0kJ1x0JyByZWFkIF8gbmFtZSBfIF8gXzsgZG8KICAgICAgICAgcHJpbnRmICIl
c1xuIiAiJG5hbWUiCi0gICAgZG9uZSA8IDwocGFjdGwgbGlzdCBzaW5rcyBzaG9ydCAyPiAvZGV2
L251bGwpCisgICAgZG9uZQogfQogCiBfX3NpbmtzX2lkeCAoKSB7CisgICAgKHBhY3RsIGxpc3Qg
c2lua3Mgc2hvcnQgMj4gL2Rldi9udWxsKSB8XAogICAgIHdoaWxlIElGUz0kJ1x0JyByZWFkIGlk
eCBfIF8gXyBfOyBkbwogICAgICAgICBwcmludGYgIiVzXG4iICIkaWR4IgotICAgIGRvbmUgPCA8
KHBhY3RsIGxpc3Qgc2lua3Mgc2hvcnQgMj4gL2Rldi9udWxsKQorICAgIGRvbmUKIH0KIAogX19z
b3VyY2VzICgpIHsKKyAgICAocGFjdGwgbGlzdCBzb3VyY2VzIHNob3J0IDI+IC9kZXYvbnVsbCkg
fFwKICAgICB3aGlsZSBJRlM9JCdcdCcgcmVhZCBfIG5hbWUgXyBfIF87IGRvCiAgICAgICAgIHBy
aW50ZiAiJXNcbiIgIiRuYW1lIgotICAgIGRvbmUgPCA8KHBhY3RsIGxpc3Qgc291cmNlcyBzaG9y
dCAyPiAvZGV2L251bGwpCisgICAgZG9uZQogfQogCiBfX3NpbmtfaW5wdXRzICgpIHsKKyAgICAo
cGFjdGwgbGlzdCBzaW5rLWlucHV0cyBzaG9ydCAyPiAvZGV2L251bGwpIHxcCiAgICAgd2hpbGUg
SUZTPSQnXHQnIHJlYWQgaWR4IF8gXyBfIF87IGRvCiAgICAgICAgIHByaW50ZiAiJXNcbiIgIiRp
ZHgiCi0gICAgZG9uZSA8IDwocGFjdGwgbGlzdCBzaW5rLWlucHV0cyBzaG9ydCAyPiAvZGV2L251
bGwpCisgICAgZG9uZQogfQogCiBfX3NvdXJjZV9vdXRwdXRzICgpIHsKKyAgICAocGFjdGwgbGlz
dCBzb3VyY2Utb3V0cHV0cyBzaG9ydCAyPiAvZGV2L251bGwpIHxcCiAgICAgd2hpbGUgSUZTPSQn
XHQnIHJlYWQgaWR4IF8gXyBfIF87IGRvCiAgICAgICAgIHByaW50ZiAiJXNcbiIgIiRpZHgiCi0g
ICAgZG9uZSA8IDwocGFjdGwgbGlzdCBzb3VyY2Utb3V0cHV0cyBzaG9ydCAyPiAvZGV2L251bGwp
CisgICAgZG9uZQogfQogCiBfX3BvcnRzICgpIHsKQEAgLTc3LDI4ICs4MywzMiBAQAogfQogCiBf
X2FsbF9tb2R1bGVzICgpIHsKKyAgICAocHVsc2VhdWRpbyAtLWR1bXAtbW9kdWxlcyAyPiAvZGV2
L251bGwpIHxcCiAgICAgd2hpbGUgcmVhZCBuYW1lOyBkbwogICAgICAgICBuYW1lPSR7bmFtZSUl
ICp9CiAgICAgICAgIHByaW50ZiAiJXNcbiIgIiRuYW1lIgotICAgIGRvbmUgPCA8KHB1bHNlYXVk
aW8gLS1kdW1wLW1vZHVsZXMgMj4gL2Rldi9udWxsKQorICAgIGRvbmUKIH0KIAogX19sb2FkZWRf
bW9kdWxlcyAoKSB7CisgICAgKHBhY3RsIGxpc3QgbW9kdWxlcyBzaG9ydCAyPiAvZGV2L251bGwp
IHxcCiAgICAgd2hpbGUgSUZTPSQnXHQnIHJlYWQgaWR4IG5hbWUgXzsgZG8KICAgICAgICAgcHJp
bnRmICIlcyAlc1xuIiAiJGlkeCIgIiRuYW1lIgotICAgIGRvbmUgPCA8KHBhY3RsIGxpc3QgbW9k
dWxlcyBzaG9ydCAyPiAvZGV2L251bGwpCisgICAgZG9uZQogfQogCiBfX3Jlc2FtcGxlX21ldGhv
ZHMgKCkgeworICAgIChwdWxzZWF1ZGlvIC0tZHVtcC1yZXNhbXBsZS1tZXRob2RzIDI+IC9kZXYv
bnVsbCkgfFwKICAgICB3aGlsZSByZWFkIG5hbWU7IGRvCiAgICAgICAgIHByaW50ZiAiJXNcbiIg
IiRuYW1lIgotICAgIGRvbmUgPCA8KHB1bHNlYXVkaW8gLS1kdW1wLXJlc2FtcGxlLW1ldGhvZHMg
Mj4gL2Rldi9udWxsKQorICAgIGRvbmUKIH0KIAogX3BhY2F0X2ZpbGVfZm9ybWF0cyAoKSB7Cisg
ICAgKHBhY2F0IC0tbGlzdC1maWxlLWZvcm1hdHMgMj4gL2Rldi9udWxsKSB8XAogICAgIHdoaWxl
IElGUz0kJ1x0JyByZWFkIG5hbWUgXzsgZG8KICAgICAgICAgcHJpbnRmICIlc1xuIiAiJG5hbWUi
Ci0gICAgZG9uZSA8IDwocGFjYXQgLS1saXN0LWZpbGUtZm9ybWF0cyAyPiAvZGV2L251bGwpCisg
ICAgZG9uZQogfQogCiBpbl9hcnJheSgpIHsK" | base64 -d > $TMP/030_posix-completion.diff

patch -p0 < $TMP/020_no-parallel-make.diff || exit 1
patch -p0 < $TMP/030_posix-completion.diff || exit 1
sed -i -e '/@PA_BINARY@/ imkdir -p \$HOME/.config/pulse' src/daemon/start-pulseaudio-x11.in || exit 1
echo "X-MATE-Autostart-Phase=Initialization" >>src/daemon/pulseaudio.desktop.in || exit 1

if pkg-config --exists orc-0.4 ; then
  ORC=yes
else
  ORC=no
fi

if pkg-config --exists bash-completion ; then
  BASHCOMPLETIONDIR=$(pkg-config --variable=completionsdir bash-completion)
else
  echo "Setting completions directory manually."
  BASHCOMPLETIONDIR=/usr/share/bash-completion/completions
fi

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./bootstrap.sh \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --mandir=/usr/man \
  --disable-tcpwrap \
  --enable-orc=${ORC} \
  --disable-static \
  --enable-hal-compat \
  --with-system-user=pulse \
  --with-system-group=pulse \
  --with-access-group=audio \
  --with-bash-completion-dir=$BASHCOMPLETIONDIR \
  --build=$ARCH-slackware-linux

make check || exit 1 
make -j1 || exit 1
make install-strip DESTDIR=$PKG

# Creamos arranque automatico
# Script
echo "#!/bin/bash

pulseaudio --start

"> $PKG/usr/bin/startpulse
chmod +x $PKG/usr/bin/startpulse


echo "[Desktop Entry]
Exec=startpulse
MimeType=
Name=startpulse
Path=
Icon=
StartupNotify=true
Terminal=false
TerminalOptions=
Type=Application" > $PKG/etc/xdg/autostart/pulseaudio.desktop
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales
