#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20150906

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	WEB=http://freedesktop.org/software/pulseaudio/releases/
	VERSION=`curl -s $WEB |grep -o "[0-9].*.tar.xz" |tail -1| cut -d '-' -f2|sed 's/.tar.xz//g'`
	PRGNAM=pulseaudio
	echo -ne "\033]2;${PRGNAM}_updater\007"
}

# Si el paquete no existe se descargara de internet
F_download(){
	if [ ! -f $PRGNAM-$VERSION.tar.xz ]; then
	echo 
	echo "$CYAN"Descargando sources de $PRGNAM-$VERSION"$CIERRE"
	sleep 1
	aria2c -x 3 ${WEB}$PRGNAM-$VERSION.tar.xz
	fi
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Descomprimiendo ..."$CIERRE"
sleep 1
rm -rf $PRGNAM-$VERSION
tar xvf $PRGNAM-$VERSION.tar.xz
cd $PRGNAM-$VERSION

sed -i -e '/@PA_BINARY@/ imkdir -p \$HOME/.config/pulse' src/daemon/start-pulseaudio-x11.in || exit 1
echo "X-MATE-Autostart-Phase=Initialization" >>src/daemon/pulseaudio.desktop.in || exit 1

chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 -o -perm 511 \) \
 -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
 -exec chmod 644 {} \;

if pkg-config --exists orc-0.4 ; then
  ORC=yes
else
  ORC=no
fi

# Parcheamos
echo '--- src/Makefile.am.orig	2014-02-14 23:45:45.000000000 +1000
+++ src/Makefile.am	2014-10-26 21:59:33.220234317 +1000
@@ -19,6 +19,8 @@
 # Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
 # USA.
 
+.NOTPARALLEL:
+
 ###################################
 #       Extra directories         #
 ###################################
--- Makefile.am.orig	2014-01-24 04:57:55.000000000 +1000
+++ Makefile.am	2014-10-26 21:58:47.090622189 +1000
@@ -15,6 +15,8 @@
 # Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
 # USA.
 
+.NOTPARALLEL:
+
 ACLOCAL_AMFLAGS = -I m4
 
 EXTRA_DIST = \' > 020_no-parallel-make.diff

patch -p0 < 020_no-parallel-make.diff || exit 1

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./bootstrap.sh \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --mandir=/usr/man \
  --disable-tcpwrap \
  --enable-orc=${ORC} \
  --disable-static \
  --enable-hal-compat \
  --with-system-user=pulse \
  --with-system-group=pulse \
  --with-access-group=audio \
  --build=$ARCH-slackware-linux

make check || exit 1
make  || exit 1
make install-strip DESTDIR=$PKG

# Creamos arranque automatico
# Script
echo "#!/bin/bash

pulseaudio --start

"> $PKG/usr/bin/startpulse
chmod 777 $PKG/usr/bin/startpulse


echo "[Desktop Entry]
Exec=startpulse
MimeType=
Name=startpulse
Path=
Icon=
StartupNotify=true
Terminal=false
TerminalOptions=
Type=Application" > $PKG/etc/xdg/autostart/pulseaudio.desktop
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
F_download
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales
