#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20151114

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=qwt
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=http://sourceforge.net/projects/qwt/files/qwt/
	VERSION=`curl -s $WEB|grep qwt/[0-9]|head -1|cut -d- -f2|cut -d t -f-1|sed 's/.$//g'`
	EXTENSION=tar.bz2
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	DOWNLOAD=http://sourceforge.net/projects/qwt/files/qwt/$VERSION/$SOURCES
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
# Parches version 6.1.2
if [ $VERSION = 6.1.2 ]; then
echo "
LS0tIHF3dGNvbmZpZy5wcmkub3JpZwkyMDE0LTEyLTExIDE0OjEzOjEzLjUxMzE4NjQ5MiArMDAw
MAorKysgcXd0Y29uZmlnLnByaQkyMDE1LTA5LTI3IDA4OjMzOjAxLjk0ODQ5MDM2OSArMDAwMApA
QCAtMTYsMTEgKzE2LDggQEAKICMgSW5zdGFsbCBwYXRocwogIyMjIyMjIyMjIyMjIyMjIyMjIyMj
IyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIwogCi1RV1Rf
SU5TVEFMTF9QUkVGSVggPSAkJFtRVF9JTlNUQUxMX1BSRUZJWF0KLQogdW5peCB7Ci0gICAgUVdU
X0lOU1RBTExfUFJFRklYICAgID0gL3Vzci9sb2NhbC9xd3QtJCRRV1RfVkVSU0lPTgotICAgICMg
UVdUX0lOU1RBTExfUFJFRklYID0gL3Vzci9sb2NhbC9xd3QtJCRRV1RfVkVSU0lPTi1xdC0kJFFU
X1ZFUlNJT04KKyAgICBRV1RfSU5TVEFMTF9QUkVGSVggICAgPSAvdXNyCiB9CiAKIHdpbjMyIHsK
QEAgLTI5LDggKzI2LDEwIEBACiB9CiAKIFFXVF9JTlNUQUxMX0RPQ1MgICAgICA9ICQke1FXVF9J
TlNUQUxMX1BSRUZJWH0vZG9jCi1RV1RfSU5TVEFMTF9IRUFERVJTICAgPSAkJHtRV1RfSU5TVEFM
TF9QUkVGSVh9L2luY2x1ZGUKLVFXVF9JTlNUQUxMX0xJQlMgICAgICA9ICQke1FXVF9JTlNUQUxM
X1BSRUZJWH0vbGliCitRV1RfSU5TVEFMTF9IRUFERVJTICAgPSAkJHtRV1RfSU5TVEFMTF9QUkVG
SVh9L2luY2x1ZGUvcXd0CitRV1RfSU5TVEFMTF9MSUJTICAgICAgPSAkJHtRV1RfSU5TVEFMTF9Q
UkVGSVh9L2xpYiQke0xJQkRJUlNVRkZJWH0KKworCiAKICMjIyMjIyMjIyMjIyMjIyMjIyMjIyMj
IyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMKICMgRGVzaWdu
ZXIgcGx1Z2luCkBAIC00MiwxNCArNDEsMTIgQEAKICMgcnVudGltZSBlbnZpcm9ubWVudCBvZiBk
ZXNpZ25lci9jcmVhdG9yLgogIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMj
IyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIwogCi1RV1RfSU5TVEFMTF9QTFVHSU5TICAg
PSAkJHtRV1RfSU5TVEFMTF9QUkVGSVh9L3BsdWdpbnMvZGVzaWduZXIKLQogIyBsaW51eCBkaXN0
cmlidXRvcnMgb2Z0ZW4gb3JnYW5pemUgdGhlIFF0IGluc3RhbGxhdGlvbgogIyB0aGVpciB3YXkg
YW5kIFFUX0lOU1RBTExfUFJFRklYIGRvZXNuJ3Qgb2ZmZXIgYSBnb29kCiAjIHBhdGguIEFsc28g
UVRfSU5TVEFMTF9QUkVGSVggaXMgb25seSBvbmUgb2YgdGhlIGRlZmF1bHQKICMgc2VhcmNoIHBh
dGhzIG9mIHRoZSBkZXNpZ25lciAtIG5vdCB0aGUgUXQgY3JlYXRvcgogCi0jUVdUX0lOU1RBTExf
UExVR0lOUyAgID0gJCRbUVRfSU5TVEFMTF9QUkVGSVhdL3BsdWdpbnMvZGVzaWduZXIKK1FXVF9J
TlNUQUxMX1BMVUdJTlMgICA9ICQkW1FUX0lOU1RBTExfUExVR0lOU10vZGVzaWduZXIKIAogIyMj
IyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMj
IyMjIyMjIyMjIwogIyBGZWF0dXJlcwpAQCAtNjMsOCArNjAsNyBAQAogIyB3aXRoIGV2ZXJ5IFF0
IHVwZ3JhZGUuIAogIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMj
IyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIwogCi1RV1RfSU5TVEFMTF9GRUFUVVJFUyAgPSAkJHtR
V1RfSU5TVEFMTF9QUkVGSVh9L2ZlYXR1cmVzCi0jIFFXVF9JTlNUQUxMX0ZFQVRVUkVTICA9ICQk
W1FUX0lOU1RBTExfUFJFRklYXS9mZWF0dXJlcworUVdUX0lOU1RBTExfRkVBVFVSRVMgID0gJCRb
UU1BS0VfTUtTUEVDU10vZmVhdHVyZXMKIAogIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMj
IyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIwogIyBCdWlsZCB0aGUgc3Rh
dGljL3NoYXJlZCBsaWJyYXJpZXMuCkBAIC0xNDEsNyArMTM3LDcgQEAKICMgT3RoZXJ3aXNlIHlv
dSBoYXZlIHRvIGJ1aWxkIHRoZW0gZnJvbSB0aGUgZXhhbXBsZXMgZGlyZWN0b3J5LgogIyMjIyMj
IyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMj
IyMjIyMjIwogCi0jUVdUX0NPTkZJRyAgICAgKz0gUXd0RXhhbXBsZXMKK1FXVF9DT05GSUcgICAg
ICs9IFF3dEV4YW1wbGVzCiAKICMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMj
IyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMKICMgVGhlIHBsYXlncm91bmQgaXMgcHJp
bWFyaWx5IGludGVuZGVkIGZvciB0aGUgUXd0IGRldmVsb3BtZW50IAo=
" | base64 -d > $TMP/patch-6.1.2-qwtconfig.diff
patch -p0 < $TMP/patch-6.1.2-qwtconfig.diff

echo "
LS0tIHNyYy9zcmMucHJvLm9yaWcJMjAxNC0xMi0xMiAwMDoxMzoxMy40NjExODY0OTMgKzEwMDAK
KysrIHNyYy9zcmMucHJvCTIwMTUtMTAtMDUgMDg6NTU6NDMuNTA0MTk0MTY0ICsxMDAwCkBAIC0y
MSw2ICsyMSwxOSBAQAogCiBERVNURElSICAgICAgICAgICA9ICQke1FXVF9PVVRfUk9PVH0vbGli
CiAKKyMgQWRkIHBrZ2NvbmZpZyBzdXBwb3J0Cit1bml4IHsKKwlDT05GSUcgICs9IGNyZWF0ZV9w
YyBjcmVhdGVfcHJsIG5vX2luc3RhbGxfcHJsCisJUU1BS0VfUEtHQ09ORklHX05BTUUgICAgICAg
ICAgICA9IHF3dAorCVFNQUtFX1BLR0NPTkZJR19ERVNDUklQVElPTiAgICAgPSBHVUkgY29tcG9u
ZW50cworCVFNQUtFX1BLR0NPTkZJR19QUkVGSVggICAgICAgICAgPSAkJHtRV1RfSU5TVEFMTF9Q
UkVGSVh9CisJUU1BS0VfUEtHQ09ORklHX0xJQkRJUiAgICAgICAgICA9ICQke1FXVF9JTlNUQUxM
X0xJQlN9CisJUU1BS0VfUEtHQ09ORklHX0lOQ0RJUiAgICAgICAgICA9ICQke1FXVF9JTlNUQUxM
X0hFQURFUlN9CisJUU1BS0VfUEtHQ09ORklHX1JFUVVJUkVTICAgICAgICA9IFF0Q29yZQorCVFN
QUtFX1BLR0NPTkZJR19ERVNURElSICAgICAgICAgPSBwa2djb25maWcKK30KKworCiBjb250YWlu
cyhRV1RfQ09ORklHLCBRd3REbGwpIHsKIAogICAgIENPTkZJRyArPSBkbGwK
" | base64 -d > $TMP/patch-6.1.2-pkgconfig.diff
patch -p0 < $TMP/patch-6.1.2-pkgconfig.diff
fi

echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1
qmake LIBDIRSUFFIX=$LIBDIRSUFFIX
make \
  CFLAGS+="$SLKCFLAGS" \
  CXXFLAGS+="$SLKCFLAGS"
make install INSTALL_ROOT=$PKG
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales