#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20160211

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	WEB=https://sourceforge.net/projects/wxwindows/files/
	VERSION=`curl -s $WEB | grep /latest | cut -d '/' -f 8 | cut -d ":" -f 1 | cut -d '-' -f 2 | cut -d "t" -f-1 | sed "s/.$//g"`
	PRGNAM=wxGTK3
	echo -ne "\033]2;${PRGNAM}_updater\007"
	SRCNAM=wxWidgets
	EXTENSION=tar.bz2
	SOURCES=$SRCNAM-$VERSION.$EXTENSION
	DOWNLOAD=https://sourceforge.net/projects/wxwindows/files/$VERSION/$SOURCES
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){

# Parcheamos primero
echo "
ZGlmZiAtdXAgd3hHVEstMi44LjEyL3NyYy9jb21tb24vYXBwYmFzZS5jcHAuYWJpY2hlY2sgd3hH
VEstMi44LjEyL3NyYy9jb21tb24vYXBwYmFzZS5jcHAKLS0tIHd4R1RLLTIuOC4xMi9zcmMvY29t
bW9uL2FwcGJhc2UuY3BwLmFiaWNoZWNrCTIwMTUtMDMtMTIgMTc6MTU6MTguMDAwMDAwMDAwICsw
MTAwCisrKyB3eEdUSy0yLjguMTIvc3JjL2NvbW1vbi9hcHBiYXNlLmNwcAkyMDE1LTAzLTEyIDE3
OjE1OjU3LjAwMDAwMDAwMCArMDEwMApAQCAtNDI0LDEwICs0MjQsNyBAQCBib29sIHd4QXBwQ29u
c29sZTo6Q2hlY2tCdWlsZE9wdGlvbnMoY29uCiAgICAgICAgIG1zZy5QcmludGYoX1QoIk1pc21h
dGNoIGJldHdlZW4gdGhlIHByb2dyYW0gYW5kIGxpYnJhcnkgYnVpbGQgdmVyc2lvbnMgZGV0ZWN0
ZWQuXG5UaGUgbGlicmFyeSB1c2VkICVzLFxuYW5kICVzIHVzZWQgJXMuIiksCiAgICAgICAgICAg
ICAgICAgICAgbGliLmNfc3RyKCksIHByb2dOYW1lLmNfc3RyKCksIHByb2cuY19zdHIoKSk7CiAK
LSAgICAgICAgd3hMb2dGYXRhbEVycm9yKG1zZy5jX3N0cigpKTsKLQotICAgICAgICAvLyBub3Jt
YWxseSB3eExvZ0ZhdGFsRXJyb3IgZG9lc24ndCByZXR1cm4KLSAgICAgICAgcmV0dXJuIGZhbHNl
OworICAgICAgICB3eExvZ1dhcm5pbmcobXNnLmNfc3RyKCkpOwogICAgIH0KICN1bmRlZiB3eENN
UAogCg==" | base64 -d > $TMP/make-abicheck-non-fatal.patch

patch -Np1 -i $TMP/make-abicheck-non-fatal.patch || exit 1

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --sysconfdir=/etc \
  --enable-shared \
  --enable-mediactrl \
  --with-opengl \
  --enable-graphics_ctx \
  --with-gtk=2 \
  --enable-unicode \
  --with-libpng=sys \
  --with-libxpm=sys \
  --with-libjpeg=sys \
  --with-libtiff=sys \
  --disable-precomp-headers \
  --build=$ARCH-slackware-linux

make  || exit 1
make install DESTDIR=$PKG

ln -fs /usr/lib${LIBDIRSUFFIX}/wx/config/gtk2-unicode-3.0 \
       $PKG/usr/bin/wx-config
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales
