#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20151011

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
   PRGNAM=x265
   echo -ne "\033]2;${PRGNAM}_updater\007"
   WEB=https://bitbucket.org/multicoreware/x265/downloads
   VERSION=`curl -s $WEB | grep .tar.gz | head -1 | cut -d _ -f2 | cut -d t -f-1 | sed "s/.$//g"`
   EXTENSION=tar.gz
   SOURCES=${PRGNAM}_$VERSION.$EXTENSION
   DOWNLOAD=$WEB/$SOURCES
   SRCNAM=${PRGNAM}_$(wget -qO - $DOWNLOAD|tar tzf -|head -1|cut -d'/' -f1|cut -d'_' -f2)
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Configurando ..."$CIERRE"
sleep 1
cd $TMP/$SRCNAM/build/linux
  cmake \
    -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
    -DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS" \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DENABLE_SHARED='TRUE'  \
    -DLIB_INSTALL_DIR=lib${LIBDIRSUFFIX} \
    -DCMAKE_BUILD_TYPE=Release ../../source

echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1
make
make install DESTDIR=$PKG
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales
