#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20160328

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=yajl
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=http://github.com/lloyd/yajl/tarball
	VERSION=2.1.0
	EXTENSION=tar.gz
	SRCNAM=lloyd-yajl-66cb08c
	SOURCES=lloyd-$PRGNAM-$VERSION-0-ga0ecdde.$EXTENSION
	DOWNLOAD=$WEB/$VERSION/$SOURCES
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Configurando ..."$CIERRE"
sleep 1

mkdir build
cd build
  cmake .. \
    -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DLIB_SUFFIX:STRING="$LIBDIRSUFFIX" \
    -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \

echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1

make DESTDIR=$PKG install || exit 1
cd -
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales