#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20151008

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=kde-games
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=http://slackware.mirrors.tds.net/pub/slackware/slackware-current/
	LAGRANWEB=http://slackware.mirrors.tds.net/pub/slackware/slackware-current
	ELGRANARCHIVO=$(curl -s $LAGRANWEB/slackware/PACKAGES.TXT)
	ELPACK=$(echo "$ELGRANARCHIVO" | grep -i game -B5 | grep NAME | awk '{print $3}' | grep -vi kanagram | grep -vi khangman | grep -vi xgames | grep -vi bsd-games | grep -vi kig)
	LOSEXTRAS=$(echo "$ELGRANARCHIVO" | grep NAME | grep -E "(libkmahjongg|kmines)" | awk '{print $3}')
	LOSGRANDESJUEGOS=$(cat <<EOF
	$ELPACK
	$LOSEXTRAS
EOF
)
VERSION=$(echo "$ELGRANARCHIVO" | grep -i kdelibs | head -1 | cut -d "-" -f 2)
}

# Si el paquete no existe se descargara de internet
F_download(){
echo "$CYAN"Se han detectado $ROJO$(echo $LOSGRANDESJUEGOS | sed 's/ /\n/g' | wc -l)$CYAN paquetes..."$CIERRE"
lacuenta=1
for JUEGO in $LOSGRANDESJUEGOS; do
LAGRANRUTA=$(echo "$ELGRANARCHIVO" | grep -i $JUEGO -A1 | grep LOCATION | awk '{print $3}' | cut -d "." -f2 | cut -d- -f2-)
VERSION_JEUGO=$(echo $JUEGO | rev | cut -d "i" -f2 | cut -d- -f2 | rev)
PRGNAM_JUEGO=$(echo $JUEGO | cut -d. -f1 | rev | cut -d- -f2- | rev)
for RUTA in $LAGRANRUTA; do
# Si el paquete no existe se descargara de internet
if [ ! -f $JUEGO ]; then
echo ""
echo "$CYAN"Descargando source nº $ROJO$lacuenta$CYAN de $PRGNAM_JUEGO-$VERSION_JEUGO"$CIERRE"
sleep 1
aria2c -x 3 $WEB/$RUTA/$JUEGO
fi
let lacuenta=lacuenta+1
done
done
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo ""
echo "$VERDE"Descomprimiendo ..."$CIERRE"
sleep 3
for JUEGO in $LOSGRANDESJUEGOS; do

installpkg --root $PKG $TMP/$JUEGO

done
rm -Rf $PKG/var/log/packages/*

# Creamos xzm , instalamos y salimos
echo ""
echo "$VERDE"Instalando y creando modulo xzm ..."$CIERRE"
sleep 3
cd $PKG
cleandir $PKG

cd $PKG/usr/share/applications/
for DESKTOP in $(find -type f); do

cat $DESKTOP | sed "s/Education//g" >${DESKTOP}2
rm $DESKTOP
mv ${DESKTOP}2 ${DESKTOP}

done
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del script
f_versionInstalada
#Si no existe el fichero se descargara
F_download
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales
