#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20151116

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=pokerth
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=http://sourceforge.net/projects/$PRGNAM/files/$PRGNAM/
	VERSION=`curl -s $WEB | grep -i latest | grep PokerTH |cut -d "/" -f9 | cut -d- -f2 | cut -d "a" -f1 | sed 's/.$//g' | sed "s/ //g"`
	EXTENSION=tar.bz2
	SRCNAM=PokerTH-$VERSION-src
	SOURCES=$SRCNAM.$EXTENSION
	DOWNLOAD=http://downloads.sourceforge.net/$PRGNAM/$SOURCES
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo ""
echo "$VERDE"Compilamos ..."$CIERRE"
sleep 1

sed -i "s|libircclient/||" src/net/common/ircthread.cpp

qmake pokerth.pro

make  || exit 1
make install DESTDIR=$PKG INSTALL_ROOT=$PKG

mkdir -p $PKG/usr/bin
install -s -D -m 0755 $TMP/PokerTH-$VERSION-src/bin/pokerth_server $PKG/usr/bin
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del script
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales