#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20151008

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	WEB=http://sourceforge.net/projects/pokerth/files/pokerth/
	VERSION=`curl -s $WEB | grep -i latest | grep PokerTH |cut -d "/" -f9 | cut -d- -f2 | cut -d "a" -f1 | sed 's/.$//g' | sed "s/ //g"`
	PRGNAM=pokerth
	echo -ne "\033]2;${PRGNAM}_updater\007"
	DOWNLOAD=http://downloads.sourceforge.net/pokerth/PokerTH-$VERSION-src.tar.bz2
}

# Si el paquete no existe se descargara de internet
F_download(){
	if [ ! -f PokerTH-$VERSION-src.tar.bz2 ]; then
	echo ""
	echo "$CYAN"Descargando sources de $PRGNAM-$VERSION"$CIERRE"
	sleep 3
	aria2c -x 3 $DOWNLOAD
fi
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo ""
echo "$VERDE"Descomprimiendo ..."$CIERRE"
sleep 3
tar xvf PokerTH-$VERSION-src.tar.bz2
cd PokerTH-$VERSION-src
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
 -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

sed -i "s|libircclient/||" src/net/common/ircthread.cpp

qmake pokerth.pro

make  || exit 1
make install DESTDIR=$PKG INSTALL_ROOT=$PKG

mkdir -p $PKG/usr/bin
install -s -D -m 0755 $TMP/PokerTH-$VERSION-src/bin/pokerth_server $PKG/usr/bin
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del script
f_versionInstalada
#Si no existe el fichero se descargara
F_download
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales
