#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20151116

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=steam
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=http://repo.steampowered.com/steam/archive/precise/
	VERSION=`curl -s $WEB | grep .tar.gz | tail -2 | grep steam_ | head -1 | cut -d '"' -f12 | sed "s/steam_//g" | sed 's/.tar.gz//g'`
	EXTENSION=tar.gz
	SRCNAM=${PRGNAM}_${VERSION}
	SOURCES=$SRCNAM.$EXTENSION
	DOWNLOAD=${WEB}${SOURCES}
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Compilamos ..."$CIERRE"
sleep 1

make install DESTDIR=$PKG

# Eliminamos la restriccion root
sed -i '137,141d' $PKG/usr/bin/steam
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales