#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20160706

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	WEB=https://www.python.org/downloads/
	#VERSION=`curl -s $WEB | grep .tar.xz | head -1 | cut -d "-" -f2 | cut -d "t" -f-1 | sed "s/.$//g"`
	VERSION=3.5.2
	PRGNAM=python3
	echo -ne "\033]2;${PRGNAM}_updater\007"
	PRGNAM2=Python
	PYVER=$(cut -d. -f1,2 <<< "$VERSION")
	SITEPK=$PKG/usr/lib${LIBDIRSUFFIX}/python${PYVER}/site-packages
	TOOLSDIR=/usr/lib${LIBDIRSUFFIX}/python${PYVER}/site-packages
	EXTENSION=tar.xz
	SOURCES=$PRGNAM2-$VERSION.$EXTENSION
	DOWNLOAD=https://www.python.org/ftp/python/$VERSION/$SOURCES
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
cd $PRGNAM2-$VERSION

# Parcheamos
cat > python3.readline.set_pre_input_hook.diff << "EOF"
--- ./Modules/readline.c.orig	2009-10-26 21:32:51.000000000 +0200
+++ ./Modules/readline.c	2010-05-30 14:07:10.000000000 +0300
@@ -12,6 +12,9 @@
 #include <errno.h>
 #include <sys/time.h>
 
+/* This seems to be needed for set_pre_input_hook to work */
+#define HAVE_RL_PRE_INPUT_HOOK 1
+
 #if defined(HAVE_SETLOCALE)
 /* GNU readline() mistakenly sets the LC_CTYPE locale.
  * This is evil.  Only the user or the app's main() should do this!

EOF

cat > python3.no-static-library.diff << "EOF"
diff -uar Python-3.5.1.orig/Makefile.pre.in Python-3.5.1/Makefile.pre.in
--- Python-3.5.1.orig/Makefile.pre.in	2015-12-07 03:39:09.000000000 +0200
+++ Python-3.5.1/Makefile.pre.in	2015-12-14 21:25:22.103542432 +0200
@@ -564,7 +564,7 @@
 	$(RUNSHARED) $(PYTHON_FOR_BUILD) ./Tools/clinic/clinic.py --make
 
 # Build the interpreter
-$(BUILDPYTHON):	Programs/python.o $(LIBRARY) $(LDLIBRARY) $(PY3LIBRARY)
+$(BUILDPYTHON):	Programs/python.o $(LDLIBRARY) $(PY3LIBRARY)
 	$(LINKCC) $(PY_LDFLAGS) $(LINKFORSHARED) -o $@ Programs/python.o $(BLDLIBRARY) $(LIBS) $(MODLIBS) $(SYSLIBS) $(LDLAST)
 
 platform: $(BUILDPYTHON) pybuilddir.txt
@@ -599,18 +599,6 @@
 		_TCLTK_INCLUDES='$(TCLTK_INCLUDES)' _TCLTK_LIBS='$(TCLTK_LIBS)' \
 		$(PYTHON_FOR_BUILD) $(srcdir)/setup.py $$quiet build
 
-# Build static library
-# avoid long command lines, same as LIBRARY_OBJS
-$(LIBRARY): $(LIBRARY_OBJS)
-	-rm -f $@
-	$(AR) $(ARFLAGS) $@ Modules/getbuildinfo.o
-	$(AR) $(ARFLAGS) $@ $(PARSER_OBJS)
-	$(AR) $(ARFLAGS) $@ $(OBJECT_OBJS)
-	$(AR) $(ARFLAGS) $@ $(PYTHON_OBJS) Python/frozen.o
-	$(AR) $(ARFLAGS) $@ $(MODULE_OBJS) $(SIGNAL_OBJS)
-	$(AR) $(ARFLAGS) $@ $(MODOBJS)
-	$(RANLIB) $@
-
 libpython$(LDVERSION).so: $(LIBRARY_OBJS)
 	if test $(INSTSONAME) != $(LDLIBRARY); then \
 		$(BLDSHARED) -Wl,-h$(INSTSONAME) -o $(INSTSONAME) $(LIBRARY_OBJS) $(MODLIBS) $(SHLIBS) $(LIBC) $(LIBM) $(LDLAST); \
@@ -700,7 +688,7 @@
 		echo "-----------------------------------------------"; \
 	fi
 
-Programs/_testembed: Programs/_testembed.o $(LIBRARY) $(LDLIBRARY) $(PY3LIBRARY)
+Programs/_testembed: Programs/_testembed.o $(LDLIBRARY) $(PY3LIBRARY)
 	$(LINKCC) $(PY_LDFLAGS) $(LINKFORSHARED) -o $@ Programs/_testembed.o $(BLDLIBRARY) $(LIBS) $(MODLIBS) $(SYSLIBS) $(LDLAST)
 
 ############################################################################
@@ -1372,18 +1360,6 @@
 		else	true; \
 		fi; \
 	done
-	@if test -d $(LIBRARY); then :; else \
-		if test "$(PYTHONFRAMEWORKDIR)" = no-framework; then \
-			if test "$(SHLIB_SUFFIX)" = .dll; then \
-				$(INSTALL_DATA) $(LDLIBRARY) $(DESTDIR)$(LIBPL) ; \
-			else \
-				$(INSTALL_DATA) $(LIBRARY) $(DESTDIR)$(LIBPL)/$(LIBRARY) ; \
-				$(RANLIB) $(DESTDIR)$(LIBPL)/$(LIBRARY) ; \
-			fi; \
-		else \
-			echo Skip install of $(LIBRARY) - use make frameworkinstall; \
-		fi; \
-	fi
 	$(INSTALL_DATA) Modules/config.c $(DESTDIR)$(LIBPL)/config.c
 	$(INSTALL_DATA) Programs/python.o $(DESTDIR)$(LIBPL)/python.o
 	$(INSTALL_DATA) $(srcdir)/Modules/config.c.in $(DESTDIR)$(LIBPL)/config.c.in

EOF

patch -p1 -i $TMP/$PRGNAM2-$VERSION/python3.readline.set_pre_input_hook.diff || exit 1
patch -p1 -i $TMP/$PRGNAM2-$VERSION/python3.no-static-library.diff || exit 1

if [ "$ARCH" = "x86_64" ]; then
cat > python3.x86_64.diff << "EOF"
diff -uar Python-3.5.1.orig/Lib/distutils/command/install.py Python-3.5.1/Lib/distutils/command/install.py
--- Python-3.5.1.orig/Lib/distutils/command/install.py	2015-12-07 03:39:07.000000000 +0200
+++ Python-3.5.1/Lib/distutils/command/install.py	2015-12-14 21:27:46.083400395 +0200
@@ -29,15 +29,15 @@
 
 INSTALL_SCHEMES = {
     'unix_prefix': {
-        'purelib': '$base/lib/python$py_version_short/site-packages',
-        'platlib': '$platbase/lib/python$py_version_short/site-packages',
+        'purelib': '$base/lib64/python$py_version_short/site-packages',
+        'platlib': '$platbase/lib64/python$py_version_short/site-packages',
         'headers': '$base/include/python$py_version_short$abiflags/$dist_name',
         'scripts': '$base/bin',
         'data'   : '$base',
         },
     'unix_home': {
-        'purelib': '$base/lib/python',
-        'platlib': '$base/lib/python',
+        'purelib': '$base/lib64/python',
+        'platlib': '$base/lib64/python',
         'headers': '$base/include/python/$dist_name',
         'scripts': '$base/bin',
         'data'   : '$base',
diff -uar Python-3.5.1.orig/Lib/distutils/sysconfig.py Python-3.5.1/Lib/distutils/sysconfig.py
--- Python-3.5.1.orig/Lib/distutils/sysconfig.py	2015-12-07 03:39:07.000000000 +0200
+++ Python-3.5.1/Lib/distutils/sysconfig.py	2015-12-14 21:27:46.083400395 +0200
@@ -133,7 +133,7 @@
 
     if os.name == "posix":
         libpython = os.path.join(prefix,
-                                 "lib", "python" + get_python_version())
+                                 "lib64", "python" + get_python_version())
         if standard_lib:
             return libpython
         else:
diff -uar Python-3.5.1.orig/Lib/site.py Python-3.5.1/Lib/site.py
--- Python-3.5.1.orig/Lib/site.py	2015-12-07 03:39:08.000000000 +0200
+++ Python-3.5.1/Lib/site.py	2015-12-14 21:27:46.083400395 +0200
@@ -303,7 +303,7 @@
         seen.add(prefix)
 
         if os.sep == '/':
-            sitepackages.append(os.path.join(prefix, "lib",
+            sitepackages.append(os.path.join(prefix, "lib64",
                                         "python" + sys.version[:3],
                                         "site-packages"))
         else:
diff -uar Python-3.5.1.orig/Lib/sysconfig.py Python-3.5.1/Lib/sysconfig.py
--- Python-3.5.1.orig/Lib/sysconfig.py	2015-12-07 03:39:08.000000000 +0200
+++ Python-3.5.1/Lib/sysconfig.py	2015-12-14 21:27:46.084400429 +0200
@@ -20,10 +20,10 @@
 
 _INSTALL_SCHEMES = {
     'posix_prefix': {
-        'stdlib': '{installed_base}/lib/python{py_version_short}',
-        'platstdlib': '{platbase}/lib/python{py_version_short}',
-        'purelib': '{base}/lib/python{py_version_short}/site-packages',
-        'platlib': '{platbase}/lib/python{py_version_short}/site-packages',
+        'stdlib': '{installed_base}/lib64/python{py_version_short}',
+        'platstdlib': '{platbase}/lib64/python{py_version_short}',
+        'purelib': '{base}/lib64/python{py_version_short}/site-packages',
+        'platlib': '{platbase}/lib64/python{py_version_short}/site-packages',
         'include':
             '{installed_base}/include/python{py_version_short}{abiflags}',
         'platinclude':
@@ -32,10 +32,10 @@
         'data': '{base}',
         },
     'posix_home': {
-        'stdlib': '{installed_base}/lib/python',
-        'platstdlib': '{base}/lib/python',
-        'purelib': '{base}/lib/python',
-        'platlib': '{base}/lib/python',
+        'stdlib': '{installed_base}/lib64/python',
+        'platstdlib': '{base}/lib64/python',
+        'purelib': '{base}/lib64/python',
+        'platlib': '{base}/lib64/python',
         'include': '{installed_base}/include/python',
         'platinclude': '{installed_base}/include/python',
         'scripts': '{base}/bin',
@@ -61,10 +61,10 @@
         'data': '{userbase}',
         },
     'posix_user': {
-        'stdlib': '{userbase}/lib/python{py_version_short}',
-        'platstdlib': '{userbase}/lib/python{py_version_short}',
-        'purelib': '{userbase}/lib/python{py_version_short}/site-packages',
-        'platlib': '{userbase}/lib/python{py_version_short}/site-packages',
+        'stdlib': '{userbase}/lib64/python{py_version_short}',
+        'platstdlib': '{userbase}/lib64/python{py_version_short}',
+        'purelib': '{userbase}/lib64/python{py_version_short}/site-packages',
+        'platlib': '{userbase}/lib64/python{py_version_short}/site-packages',
         'include': '{userbase}/include/python{py_version_short}',
         'scripts': '{userbase}/bin',
         'data': '{userbase}',
diff -uar Python-3.5.1.orig/Makefile.pre.in Python-3.5.1/Makefile.pre.in
--- Python-3.5.1.orig/Makefile.pre.in	2015-12-07 03:39:09.000000000 +0200
+++ Python-3.5.1/Makefile.pre.in	2015-12-14 21:27:46.084400429 +0200
@@ -125,7 +125,7 @@
 MANDIR=		@mandir@
 INCLUDEDIR=	@includedir@
 CONFINCLUDEDIR=	$(exec_prefix)/include
-SCRIPTDIR=	$(prefix)/lib
+SCRIPTDIR=	$(prefix)/lib64
 ABIFLAGS=	@ABIFLAGS@
 
 # Detailed destination directories
diff -uar Python-3.5.1.orig/Modules/getpath.c Python-3.5.1/Modules/getpath.c
--- Python-3.5.1.orig/Modules/getpath.c	2015-12-07 03:39:10.000000000 +0200
+++ Python-3.5.1/Modules/getpath.c	2015-12-14 21:27:46.085400463 +0200
@@ -511,7 +511,7 @@
     _pythonpath = Py_DecodeLocale(PYTHONPATH, NULL);
     _prefix = Py_DecodeLocale(PREFIX, NULL);
     _exec_prefix = Py_DecodeLocale(EXEC_PREFIX, NULL);
-    lib_python = Py_DecodeLocale("lib/python" VERSION, NULL);
+    lib_python = Py_DecodeLocale("lib64/python" VERSION, NULL);
 
     if (!_pythonpath || !_prefix || !_exec_prefix || !lib_python) {
         Py_FatalError(
@@ -700,7 +700,7 @@
     }
     else
         wcsncpy(zip_path, _prefix, MAXPATHLEN);
-    joinpath(zip_path, L"lib/python00.zip");
+    joinpath(zip_path, L"lib64/python00.zip");
     bufsz = wcslen(zip_path);   /* Replace "00" with version */
     zip_path[bufsz - 6] = VERSION[0];
     zip_path[bufsz - 5] = VERSION[2];
@@ -712,7 +712,7 @@
             fprintf(stderr,
                 "Could not find platform dependent libraries <exec_prefix>\n");
         wcsncpy(exec_prefix, _exec_prefix, MAXPATHLEN);
-        joinpath(exec_prefix, L"lib/lib-dynload");
+        joinpath(exec_prefix, L"lib64/lib-dynload");
     }
     /* If we found EXEC_PREFIX do *not* reduce it!  (Yet.) */
 
diff -uar Python-3.5.1.orig/configure Python-3.5.1/configure
--- Python-3.5.1.orig/configure	2015-12-07 03:39:11.000000000 +0200
+++ Python-3.5.1/configure	2015-12-14 21:27:46.089400598 +0200
@@ -14464,7 +14464,7 @@
 $as_echo "$LDVERSION" >&6; }
 
 
-LIBPL='$(prefix)'"/lib/python${VERSION}/config-${LDVERSION}"
+LIBPL='$(prefix)'"/lib64/python${VERSION}/config-${LDVERSION}"
 
 
 # Check whether right shifting a negative integer extends the sign bit
diff -uar Python-3.5.1.orig/setup.py Python-3.5.1/setup.py
--- Python-3.5.1.orig/setup.py	2015-12-07 03:39:11.000000000 +0200
+++ Python-3.5.1/setup.py	2015-12-14 21:27:46.090400632 +0200
@@ -469,7 +469,7 @@
         # directories (i.e. '.' and 'Include') must be first.  See issue
         # 10520.
         if not cross_compiling:
-            add_dir_to_list(self.compiler.library_dirs, '/usr/local/lib')
+            add_dir_to_list(self.compiler.library_dirs, '/usr/local/lib64')
             add_dir_to_list(self.compiler.include_dirs, '/usr/local/include')
         # only change this for cross builds for 3.3, issues on Mageia
         if cross_compiling:
@@ -750,11 +750,11 @@
             elif curses_library:
                 readline_libs.append(curses_library)
             elif self.compiler.find_library_file(lib_dirs +
-                                                     ['/usr/lib/termcap'],
+                                                     ['/usr/lib64/termcap'],
                                                      'termcap'):
                 readline_libs.append('termcap')
             exts.append( Extension('readline', ['readline.c'],
-                                   library_dirs=['/usr/lib/termcap'],
+                                   library_dirs=['/usr/lib64/termcap'],
                                    extra_link_args=readline_extra_link_args,
                                    libraries=readline_libs) )
         else:
@@ -791,8 +791,8 @@
             if krb5_h:
                 ssl_incs += krb5_h
         ssl_libs = find_library_file(self.compiler, 'ssl',lib_dirs,
-                                     ['/usr/local/ssl/lib',
-                                      '/usr/contrib/ssl/lib/'
+                                     ['/usr/local/ssl/lib64',
+                                      '/usr/contrib/ssl/lib64/'
                                      ] )
 
         if (ssl_incs is not None and

EOF
  patch -p1 -i $TMP/$PRGNAM2-$VERSION/python3.x86_64.diff || exit 1
fi


# Fixes
sed -i '1s|^#.*/usr/local/bin/python|#!/usr/bin/python3|' Lib/cgi.py
sed -i 's|\("install",\)|\1 "--ignore-installed",|' Lib/ensurepip/__init__.py

echo 
echo "$VERDE"Configurando ..."$CIERRE"
sleep 1  
  
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --mandir=/usr/man \
  --docdir=/usr/doc/$PRGNAM-$VERSION \
  --with-threads \
  --enable-ipv6 \
  --enable-shared \
  --with-system-expat \
  --with-system-ffi \
  --build=$ARCH-slackware-linux

echo 
echo "$VERDE"Compilamos ..."$CIERRE"
sleep 1  
  
make  || exit 1
make install DESTDIR=$PKG

# Restore original ensurepip behaviour.
sed -i 's|\("install",\) "--ignore-installed",|\1|' \
  $PKG/usr/lib${LIBDIRSUFFIX}/python${PYVER}/ensurepip/__init__.py

# Remove to avoid overwriting a copy from Python2.
rm -f $PKG/usr/bin/2to3

# We'll install the python-tools under site-packages:
mkdir -p $SITEPK
cp -a Tools/* $SITEPK

# Remove DOS batch/exe files.
find $PKG \( -name '*.exe' -o -name '*.bat' \) -exec rm -f '{}' \;

# Fix permissions on dynamic libraries.
find $PKG -type f -perm 555 -exec chmod 755 '{}' \;
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales