#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20160324

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	WEB=http://downloads.sourceforge.net/wxpython
	VERSION=2.8.12.1
	PRGNAM=wxPython
	echo -ne "\033]2;${PRGNAM}_updater\007"
	SRCNAM=$PRGNAM-src-$VERSION
	EXTENSION=tar.bz2
	SOURCES=$PRGNAM-src-$VERSION.$EXTENSION
	DOWNLOAD=$WEB/$SOURCES
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
# Configuramos paquete
echo ""
echo "$VERDE"Configurando ..."$CIERRE"
sleep 1

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --disable-static \
  --with-sdl \
  --with-opengl \
  --without-gnomeprint \
  --enable-unicode \
  --enable-graphics_ctx \
  --enable-display \
  --enable-mediactrl \
  --enable-sound \
  --libdir=/usr/lib$LIBDIRSUFFIX \
  --build=$ARCH-slackware-linux

make  || exit 1
#Additional stuff from contrib
make -C contrib/src/gizmos || exit 1
make -C contrib/src/ogl || exit 1
make -C contrib/src/stc || exit 1

make install DESTDIR=$PKG  || exit 1
make -C contrib/src/gizmos install DESTDIR=$PKG  || exit 1
make -C contrib/src/ogl install DESTDIR=$PKG  || exit 1
make -C contrib/src/stc install DESTDIR=$PKG  || exit 1

cd wxPython
  python setup.py \
    WXPORT=gtk2 \
    UNICODE=1 \
    EP_ADD_OPTS=1 \
    EP_FULL_VER=0 \
    NO_SCRIPTS=0 \
    WX_CONFIG="$TMP/$PRGNAM-src-$VERSION/wx-config --no_rpath" \
    build_ext --include-dirs=$TMP/$PRGNAM-src-$VERSION/lib/wx/include/gtk2-unicode-release-2.8 \
              --library-dirs=$TMP/$PRGNAM-src-$VERSION/lib \
              --rpath=/usr/lib$LIBDIRSUFFIX \
    build

  python setup.py \
    WXPORT=gtk2 \
    UNICODE=1 \
    EP_ADD_OPTS=1 \
    EP_FULL_VER=0 \
    NO_SCRIPTS=0 \
    WX_CONFIG="$TMP/$PRGNAM-src-$VERSION/wx-config --prefix=$PKG/usr/bin/ --no_rpath" \
    SYS_WX_CONFIG="wx-config --enable-unicode" \
    build_ext --include-dirs=$TMP/$PRGNAM-src-$VERSION/lib/wx/include/gtk2-unicode-release-2.8 \
              --library-dirs=$TMP/$PRGNAM-src-$VERSION/lib \
              --rpath=/usr/lib$LIBDIRSUFFIX \
    install --root=$PKG
    
mkdir -p $PKG/usr/share/{applications,pixmaps} $PKG/usr/share/icons/hicolor/{16x16,32x32}/apps
install -m 644 distrib/*.desktop $PKG/usr/share/applications/

    install -m 644 wx/py/PyCrust_16.png $PKG/usr/share/icons/hicolor/16x16/apps/PyCrust.png
    install -m 644 wx/py/PyCrust_32.png $PKG/usr/share/icons/hicolor/32x32/apps/PyCrust.png
    ln -s /usr/share/icons/hicolor/32x32/apps/PyCrust.png $PKG/usr/share/pixmaps/PyCrust.png
    install -m 644 wx/py/PySlices_16.png $PKG/usr/share/icons/hicolor/16x16/apps/PySlices.png
    install -m 644 wx/py/PySlices_32.png $PKG/usr/share/icons/hicolor/32x32/apps/PySlices.png
    ln -s /usr/share/icons/hicolor/32x32/apps/PySlices.png $PKG/usr/share/pixmaps/PySlices.png
    install -m 644 wx/tools/XRCed/XRCed_16.png $PKG/usr/share/icons/hicolor/16x16/apps/XRCed.png
    install -m 644 wx/tools/XRCed/XRCed_32.png $PKG/usr/share/icons/hicolor/32x32/apps/XRCed.png
    ln -s /usr/share/icons/hicolor/32x32/apps/XRCed.png $PKG/usr/share/pixmaps/XRCed.png
    
    # don't ship editra - it releases independently and the included version is outdated
    rm $PKG/usr/bin/editra
    rm $PKG/usr/share/applications/Editra.desktop
    rm -rf $PKG/usr/lib$LIBDIRSUFFIX/python2.7/site-packages/wx-2.8-gtk2-unicode/wx/tools/Editra
cd -

# Para no crear conflictos con las gtk3 eliminamos el wx-config apuntando a gtk2
rm -rf $PKG/usr/bin/wx-config 2>/dev/null

# Relink
ln -fs /usr/lib${LIBDIRSUFFIX}/wx/config/gtk2-unicode-release-2.8 \
       $PKG/usr/bin/wx-config-2.8
       
rm -rf $PKG/usr/share/applications/{PySlices.desktop,PySlicesShell.desktop}
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del script
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales