#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20151106

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=bleachbit
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=http://bleachbit.sourceforge.net/download
	VERSION=`curl -s $WEB|grep released|head -1|rev|cut -d ' ' -f2|rev|sed 's/ //g'`
	EXTENSION=tar.bz2
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	DOWNLOAD=http://sourceforge.net/projects/bleachbit/files/$SOURCES
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
# Exclude the Windows-only cleaners from the source per author's instructions.
grep -l os=.windows. cleaners/*xml | xargs rm -f

echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1
make || exit 1
make install DESTDIR=$PKG prefix=/usr

# Arreglo en el fichero desktop
sed -i 's/Categories=GTK;System;/Categories=mantenimiento;/g' $PKG/usr/share/applications/bleachbit.desktop
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales
