#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20151005

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=cairo-dock
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://launchpad.net/cairo-dock-core/
	VERSION=`curl -s $WEB | grep "Latest version is" | sed "s/Latest version is //g" | sed "s/ //g"`
	RAMA=$(echo $VERSION | cut -d "." -f-2)
	EXTENSION=tar.gz
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	DOWNLOAD=https://launchpad.net/cairo-dock-core/$RAMA/$VERSION/+download/$SOURCES
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 3 
 
cmake \
  -DCMAKE_C_FLAGS_RELEASE:STRING="$SLKCFLAGS" \
  -DCMAKE_CXX_FLAGS_RELEASE:STRING="$SLKCFLAGS" \
  -DLIB_SUFFIX=${LIBDIRSUFFIX} \
  -DCMAKE_INSTALL_PREFIX=/usr \
  -DMAN_INSTALL_DIR=/usr/man \
  -DCMAKE_BUILD_TYPE=Release .

make VERBOSE=1  || exit 1
make install DESTDIR=$PKG
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_compilar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales
