#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20150906

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=cairo-dock-plugins
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://launchpad.net/cairo-dock-plug-ins/
	VERSION=`curl -s $WEB | grep "Latest version is" | sed "s/Latest version is //g" | sed "s/ //g"`
	RAMA=$(echo $VERSION | cut -d "." -f-2)
	DOWNLOAD=https://launchpad.net/cairo-dock-plug-ins/$RAMA/$VERSION/+download/$PRGNAM-$VERSION.tar.gz
}

# Comprobar dependencias
F_dependencias(){
echo "$ROSA"Comprobando dependencias ..."$CIERRE"
echo ""

DEPENDENCIAS="cairo-dock"
CONTINUAR=0

echo "$CYAN"Dependencias de este paquete:""
echo ""
sleep 3

for X in $DEPENDENCIAS; do
	
	if [ -f /usr/bin/$X ]; then
		echo ""$AMARILLO"$X :$VERDE Instalada"$CIERRE""
	else
		echo ""$AMARILLO"$X :$ROJO  No instalada"$CIERRE""
		CONTINUAR=1
	fi
done

if [ $CONTINUAR -eq 1 ]; then
	echo ""
	echo ""$ROJO"No se cumplen los requisitos no se puede continuar"$CIERRE""
	sleep 3
	exit 1
else
	echo ""
	echo ""$VERDE"Bien ..podemos continuar"$CIERRE""
	echo ""
fi
}

# Si el paquete no existe se descargara de internet
F_download(){
	if [ ! -f $PRGNAM-$VERSION.tar.gz ]; then
	echo 
	echo "$CYAN"Descargando sources de $PRGNAM-$VERSION"$CIERRE"
	sleep 3
	aria2c -x 3 $DOWNLOAD
	fi
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Descomprimiendo ..."$CIERRE"
sleep 3
rm -rf $PRGNAM-$VERSION
tar -xvf $PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
 -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
 -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 3 
 
cmake \
  -DCMAKE_C_FLAGS_RELEASE:STRING="$SLKCFLAGS" \
  -DCMAKE_CXX_FLAGS_RELEASE:STRING="$SLKCFLAGS" \
  -DLIB_SUFFIX=${LIBDIRSUFFIX} \
  -DCMAKE_INSTALL_PREFIX=/usr \
  -DCMAKE_BUILD_TYPE=Release .

make  VERBOSE=1 || exit 1
make install DESTDIR=$PKG

mkdir -p $PKG/usr/lib${LIBDIRSUFFIX}/ruby/1.9.1
if [ -d $PKG/usr/usr ]; then
  mv $PKG/usr/usr/lib${LIBDIRSUFFIX}/ruby/1.9.1/CDApplet.rb \
     $PKG/usr/lib${LIBDIRSUFFIX}/ruby/1.9.1
  rm -rf $PKG/usr/usr
elif [ -e $PKG/usr/CDApplet.rb ]; then
  mkdir -p $PKG/usr/lib${LIBDIRSUFFIX}/ruby/1.9.1
  mv $PKG/usr/CDApplet.rb $PKG/usr/lib${LIBDIRSUFFIX}/ruby/1.9.1
fi
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Compronar dependencias
F_dependencias
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
F_download
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales
