#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20150906

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=dosbox
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=http://sourceforge.net/projects/$PRGNAM/files/$PRGNAM/
	VERSION=`curl -s $WEB | grep /latest | cut -d "/" -f8 | sed "s/ //g"`
	DOWNLOAD=http://downloads.sourceforge.net/project/$PRGNAM/$PRGNAM/$VERSION/$PRGNAM-$VERSION.tar.gz
}

# Si el paquete no existe se descargara de internet
F_download(){
	if [ ! -f $PRGNAM-$VERSION.tar.gz ]; then
	echo 
	echo "$CYAN"Descargando sources de $PRGNAM-$VERSION"$CIERRE"
	sleep 1
	aria2c -x 3 $DOWNLOAD
	fi
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Descomprimiendo ..."$CIERRE"
sleep 1
rm -rf $PRGNAM-$VERSION
tar -xzvf $PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 -o -perm 511 \) \
 -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
 -exec chmod 644 {} \;
 
if [ $VERSION = 0.74 ]; then
echo 
echo "$VERDE"Aplicando parche ..."$CIERRE"
sleep 1
cat > dosbox-0.74-gcc46.patch << "EOF"
--- include/dos_inc.h.old	2011-04-28 08:46:04.505011354 +0200
+++ include/dos_inc.h	2011-04-28 08:46:27.104408178 +0200
@@ -21,6 +21,7 @@
 #ifndef DOSBOX_DOS_INC_H
 #define DOSBOX_DOS_INC_H
 
+#include <cstddef>
 #ifndef DOSBOX_DOS_SYSTEM_H
 #include "dos_system.h"
 #endif

EOF
patch -p0 < dosbox-0.74-gcc46.patch
fi

echo 
echo "$VERDE"Configurando ..."$CIERRE"
sleep 1

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --mandir=/usr/man \
  --docdir=/usr/doc/$PRGNAM-$VERSION \
  --build=$ARCH-slackware-linux

echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1 
make  DESTDIR=$PKG || exit 1
make install-strip DESTDIR=$PKG
install -D -m 0644 src/dosbox.ico $PKG/usr/share/pixmaps/dosbox.ico

# Gneramos el fichero .desktop
cat > dosbox.desktop << "EOF"
[Desktop Entry]
Version=1.0
Name=dosbox
Comment=DOS Emulator
GenericName=dosbox
Exec=dosbox
Icon=/usr/share/pixmaps/dosbox.ico
Terminal=false
Type=Application
Categories=System;
StartupNotify=true
EOF

mkdir -p $PKG/usr/share/applications
mv dosbox.desktop $PKG/usr/share/applications

}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
F_download
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales
