#!/bin/bash

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20150502

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=firmwares
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB="http://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git"
	VERSION="$(curl -s "$WEB/info/web/last-modified"|cut -d' ' -f1|tr -d '-')"
}

# Descarga los firmwares mas nuevos disponibles
F_descargar() {
echo ""
echo "$VERDE"Se procede a descargar los firmwares desde kernel.org"$CIERRE"
echo "$AMARILLO"
git clone "$WEB"
echo "$CIERRE"
}

# Creamos directorios , eliminamos sobrantes .git y movemos
F_arreglar(){
rm -Rf $TMP/linux-firmware/.git
rm -Rf $TMP/linux-firmware/LICENSE*
rm -Rf $TMP/linux-firmware/LICENCE*
rm -Rf $TMP/linux-firmware/WHENCE
rm -Rf $TMP/linux-firmware/README
rm -Rf $TMP/linux-firmware/Makefile
rm -Rf $TMP/linux-firmware/GPL-3
rm -Rf $TMP/linux-firmware/configure
rm -Rf $TMP/linux-firmware/htc_7010.fw
rm -Rf $TMP/linux-firmware/htc_9271.fw
mkdir -p $PKG/lib/firmware
mv $TMP/linux-firmware/* $PKG/lib/firmware/

# Aqui conseguimos las ulimas version de firmware para chips atheros usb
if [ -d $TMP/ath9k-htc-firmware-blob ]; then
rm -rf $TMP/ath9k-htc-firmware-blob
fi
echo "$AMARILLO"
git clone https://github.com/olerem/ath9k-htc-firmware-blob
mv $TMP/ath9k-htc-firmware-blob/htc_7010.fw $PKG/lib/firmware/
mv $TMP/ath9k-htc-firmware-blob/htc_9271.fw $PKG/lib/firmware/
echo "$CIERRE"
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura noarch
#Comprobamos version instalada del script
f_versionInstalada
#Descarga los firmwares mas nuevos disponibles
F_descargar
#Eliminar innecesarios
F_arreglar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales