#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20151008

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	WEB=http://www.adobe.com/software/flash/about/
	VERSION=`curl -s $WEB | grep -i "<td>11.2.*.*</td>" | head -1 | sed "s/<td>//" | cut -d "<" -f-1 | sed "s/ //g"`
	PRGNAM=flashplayer-plugin
	echo -ne "\033]2;${PRGNAM}_updater\007"
	DOWNLOAD=https://fpdownload.macromedia.com/get/flashplayer/pdc/$VERSION/install_flash_player_11_linux.i386.tar.gz
}

# Si el paquete no existe se descargara de internet
F_download(){
	if [ ! -f install_flash_player_11_linux.i386.tar.gz ]; then
		echo ""
		echo "$CYAN"Descargando sources de $PRGNAM-$VERSION"$CIERRE"
		sleep 3
		aria2c -x 3 $DOWNLOAD
	fi
}

# Descomprimimos el fichero descargado
F_descomprimir(){
	echo ""
	echo "$VERDE"Descomprimiendo ..."$CIERRE"
	sleep 3
	tar xvf install_flash_player_11_linux.i386.tar.gz -C $PKG

	mkdir -p $PKG/usr/lib/mozilla/plugins
	mv $PKG/libflashplayer.so $PKG/usr/lib/mozilla/plugins

	cd $PKG
	rm -rf readme.txt
	chown -R root:root $PKG
	chmod -R g-w $PKG
	find $PKG -type f -name "*.so" -exec chmod 0755 {} \;
}

# Creamos desktop
F_desktop(){
rm -rf $PKG/usr/share/applications/*.desktop
echo "[Desktop Entry]
Name=Adobe Flash Player
Comment=Preferences for Adobe Flash Player
Comment[es]=Preferencias para Adobe Flash Player
Exec=flash-player-properties
Icon=flash-player-properties
Terminal=false
Type=Application
StartupNotify=true
Categories=Settings" > $PKG/usr/share/applications/$PRGNAM.desktop

# Creamos config
mkdir -p $PKG/etc/adobe
echo "#Hardware video decoding
#EnableLinuxHWVideoDecode=1" > $PKG/etc/adobe/mms.cfg

# Eliminamos carpeta lgpl
if [ -d $PKG/LGPL ]; then
rm -rf $PKG/LGPL
fi
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del script
f_versionInstalada
#Si no existe el fichero se descargara
F_download
#Descomprimir fichero descargado
F_descomprimir
#Creamos la entrada al menu
F_desktop
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales