#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20160118

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	WEB=http://sourceforge.net/projects/gparted/files/gparted/
	VERSION=`curl -s $WEB | grep '<tr title="gparted-' | head -1 | sed 's/<tr title="gparted-//g' | sed 's/" class="folder ">//g' | sed "s/ //g"`
	PRGNAM=gparted
	echo -ne "\033]2;${PRGNAM}_updater\007"
	EXTENSION=tar.gz
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	DOWNLOAD=$WEB/$PRGNAM-$VERSION/$SOURCES
}

F_compilar(){
	sed -i "s:@gksuprog@ @installdir@/gparted %f:@installdir@/gparted_polkit %f:g" \
	gparted.desktop.in.in
	
	echo ""
	echo "$VERDE"Configurando ..."$CIERRE"
	sleep 1
	
	CFLAGS="$SLKCFLAGS" \
	CXXFLAGS="$SLKCFLAGS" \
	./configure \
	  --prefix=/usr \
	  --sysconfdir=/etc \
	  --localstatedir=/var \
	  --mandir=/usr/man \
	  --disable-doc \
	  --build=$ARCH-slackware-linux
	  
	echo ""
	echo "$VERDE"Compilando ..."$CIERRE"
	sleep 1
	
	make  || exit 1
	make install-strip DESTDIR=$PKG
}

# Generamos ficheros necesarios
F_extras(){
cat > com.slackware.pkexec.gparted.policy << "EOF"
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE policyconfig PUBLIC
"-//freedesktop//DTD PolicyKit Policy Configuration 1.0//EN"
"http://www.freedesktop.org/standards/PolicyKit/1/policyconfig.dtd">
<policyconfig>
<action id="com.slackware.pkexec.gparted">
<message>Authentication is required to run the GParted Partition Editor</message>
<icon_name>gparted</icon_name>
<defaults>
<allow_any>auth_admin</allow_any>
<allow_inactive>auth_admin</allow_inactive>
<allow_active>auth_admin</allow_active>
</defaults>
<annotate key="org.freedesktop.policykit.exec.path">/usr/sbin/gparted</annotate>
<annotate key="org.freedesktop.policykit.exec.allow_gui">true</annotate>
</action>
</policyconfig>
EOF

cat > gparted_polkit << "EOF"
#!/bin/bash
if [ $(which pkexec) ]; then
	pkexec --disable-internal-agent "/usr/sbin/gparted" "$@"
else
	/usr/sbin/gparted "$@"
fi
EOF

# Instalamos la regla polkit
install -Dm0644 com.slackware.pkexec.gparted.policy \
$PKG/usr/share/polkit-1/actions/com.slackware.pkexec.gparted.policy

install -Dm0755 gparted_polkit \
$PKG/usr/sbin/gparted_polkit
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del script
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Creamos la entrada al menu
F_compilar
#Generamos ficheros necesarios
F_extras
#Creamos xzm , instalamos y salimos
f_tareasFinales