#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20151116

#################################################
## Funciones comunes. Su nombre empieza por f_ ##
#################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables(){
	PRGNAM=hardinfo
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://github.com/lpereira/hardinfo
	VERSION=$(curl -s $WEB/blob/master/CMakeLists.txt|grep HARDINFO_VERSION|cut -d ';' -f2|cut -d '&' -f-1)_$(curl -s $WEB|grep commit/|head -1|rev|cut -d / -f1|cut -d '"' -f2|rev|cut -c-6)
	DOWNLOAD=$WEB/$SOURCES
}

# Git clone
F_download(){
echo ""
echo "$VERDE"Descargando sources de ${AMARILLO}$PRGNAM-$VERSION${BLANCO}..."$CIERRE"
sleep 1
cd $TMP
git clone $WEB
}

# Compilamos
F_compilar(){
echo ""
echo "$VERDE"Compilamos${BLANCO}..."$CIERRE"
sleep 1
	cd $TMP/$PRGNAM
	mkdir build
	cd build
	cmake -DCMAKE_INSTALL_PREFIX=/usr ..
	make  || exit 1
	make install DESTDIR=$PKG

# Entrada desktop
rm -rf $PKG/usr/share/applications/hardinfo.desktop
mkdir -p $PKG/usr/share/pixmaps
cp -rf $PKG/usr/share/hardinfo/pixmaps/logo.png $PKG/usr/share/pixmaps/hardinfo.png
echo "[Desktop Entry]
Name=Hardinfo
Exec=hardinfo
Icon=hardinfo
Terminal=false
Type=Application
Categories=System;
" > $PKG/usr/share/applications/hardinfo.desktop
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del script
f_versionInstalada
#Si no existe el fichero se descargara
F_download
#Creamos la entrada al menu
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales