#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20151024

#################################################
## Funciones comunes. Su nombre empieza por f_ ##
#################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables(){
	WEB=http://sourceforge.net/projects/hardinfo.berlios/files/
	VERSION=`curl -s $WEB | grep /latest | cut -d "/" -f 7 | cut -d- -f2 | cut -d "." -f-3`
	PRGNAM=hardinfo
	echo -ne "\033]2;${PRGNAM}_updater\007"
	EXTENSION=tar.bz2
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	DOWNLOAD=$WEB/$SOURCES
}

# Compilamos
F_compilar(){
	sed -i "s|share/man|man|" configure

	CFLAGS="$SLKCFLAGS" \
	CXXFLAGS="$SLKCFLAGS" \
	./configure \
	--prefix=/usr \
	--libdir=/usr/lib${LIBDIRSUFFIX} \
	--sysconfdir=/etc \
	--localstatedir=/var \
	--mandir=/usr/man \
	--build=$ARCH-slackware-linux

	make  || exit 1
	make install DESTDIR=$PKG

	rm -rf $PKG/usr/local

# Entrada desktop
rm -rf $PKG/usr/share/applications/hardinfo.desktop
mkdir -p $PKG/usr/share/pixmaps
cp -rf $PKG/usr/share/hardinfo/pixmaps/logo.png $PKG/usr/share/pixmaps/hardinfo.png
echo "[Desktop Entry]
Name=Hardinfo
Exec=hardinfo
Icon=hardinfo
Terminal=false
Type=Application
Categories=System;
" > $PKG/usr/share/applications/hardinfo.desktop
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del script
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Creamos la entrada al menu
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales