#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20160404

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=keepassx
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://github.com/keepassx/keepassx
	VERSION=`curl -s $WEB/releases|grep tar.gz|head -1|cut -d / -f5|cut -d t -f-1|sed 's/.$//g'`
	EXTENSION=tar.gz
	SOURCES=$VERSION.$EXTENSION
	DOWNLOAD=$WEB/archive/$SOURCES
}

F_compilar(){
echo 
echo "$VERDE"Configurando ..."$CIERRE"
sleep 1
mkdir build
cd build
  cmake -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=/usr/lib${LIBDIRSUFFIX} \
    -DCMAKE_BUILD_TYPE=Release ..

echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1    
make  || exit 1
echo 
echo "$VERDE"Realizando test ..."$CIERRE"
sleep 1
make test || exit 1
make install DESTDIR=$PKG

# Modificamos el desktop
echo "[Desktop Entry]
Name=KeePassX
GenericName=Cross Platform Password Manager
GenericName[es]=Gestor de contraseñas multiplataforma
Exec=keepassx %f
Icon=keepassx
Comment=Cross Platform Password Manager
Comment[es]=Gestor de contraseñas multiplataforma
Terminal=false
Type=Application
Categories=System;
MimeType=application/x-keepass;" > $PKG/usr/share/applications/keepassx.desktop
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del script
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales