#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20151008

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	WEB=http://sourceforge.net/projects/keepassx/files/KeePassX/
	VERSION=`curl -s $WEB | grep /latest | cut -d '/' -f 8 | cut -d ":" -f 1 | cut -d '-' -f 2`
	PRGNAM=keepassx
	echo -ne "\033]2;${PRGNAM}_updater\007"
	EXTENSION=tar.gz
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	DOWNLOAD=$WEB$VERSION/$SOURCES
}

F_compilar(){
# Generamos parche si procede
if [ $VERSION = "0.4.3" ]; then
cat > keepassx-0.4.3-gcc47.patch << "EOF"
diff --git a/src/lib/random.cpp b/src/lib/random.cpp
index 1007172..f12dd1c 100644
--- a/src/lib/random.cpp
+++ b/src/lib/random.cpp
@@ -19,6 +19,7 @@
  ***************************************************************************/
 
 #include "random.h"
+#include <unistd.h>
 
 
 #if defined(Q_WS_X11) || defined(Q_WS_MAC)

EOF
# Aplicamos parche
patch -p1 < keepassx-0.4.3-gcc47.patch
fi

qmake \
  QMAKE_CFLAGS="$SLKCFLAGS" \
  QMAKE_CXXFLAGS="$SLKCFLAGS"
  
make  || exit 1
make install INSTALL_ROOT=$PKG

# Modificamos el desktop
echo "[Desktop Entry]
Name=KeePassX
GenericName=Cross Platform Password Manager
GenericName[es]=Gestor de contraseñas multiplataforma
Exec=keepassx %f
Icon=keepassx
Comment=Cross Platform Password Manager
Comment[es]=Gestor de contraseñas multiplataforma
Terminal=false
Type=Application
Categories=System;
MimeType=application/x-keepass;" > $PKG/usr/share/applications/keepassx.desktop
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del script
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales