#!/bin/bash

# Script by USUARIONUEVO @ www.seguridadwireless.net

# Eliminamos posibles ficheros viejos de modificaciones de scripts	
rm -rf /opt/wifislax-updaters/*/*~ &>/dev/null

SCRIPT_VERSION=20160508

# Colores
CIERRE=${CIERRE:-"[0m"}
ROJO=${ROJO:-"[1;31m"}
VERDE=${VERDE:-"[1;32m"}
CYAN=${CYAN:-"[1;36m"}
AMARILLO=${AMARILLO:-"[1;33m"}
BLANCO=${BLANCO:-"[1;37m"}
ROSA=${ROSA:-"[1;35m"}

# Variables globales
# El PRGNAM2 se usa en la creacion del xzm ,NO BORRAR
PRGNAM2=kernel
PRGNAM=linux
SCRIPTNAME=linux_updater
TAG=sw
M0DNUM=000
MODNAM=Kernel
BUILD=1
KERNEL_SISTEMA=`uname -r|cut -d '-' -f1|sed 's/ //g'`
RAMA_SISTEMA=`uname -r|cut -d '-' -f1|cut -d "." -f-2|sed 's/ //g'`
WEB=https://www.kernel.org/

export MAKEFLAGS='-j '$(grep -c ^processor /proc/cpuinfo)

echo -ne "\033]2;${PRGNAM}_updater\007"

# Bienvenida
clear
echo $ROSA
echo "
      __ __                 __  _____                _ __       
     / // /__ _______  ___ / / / ___/__  __ _  ___  (_) /__ ____
    / ,< / -_) __/ _ \/ -_) / / /__/ _ \/  ' \/ _ \/ / / -_) __/
   /_/|_|\__/_/ /_//_/\__/_/  \___/\___/_/_/_/ .__/_/_/\__/_/   
                                            /_/                  "
echo ""                                         
echo ""$AMARILLO"   ##### By USUARIONUEVO @ www.seguridadwireless.net #####"$CIERRE""
echo ""
sleep 1

# Sin internet el script no continua.
if [ ! "$(ping google.com -c1 2>/dev/null)" ]; then
echo "$ROJO"No tengo internet"$CIERRE ... $BLANCO"el script se cerrara..."$CIERRE"
echo ""
sleep 1
exit 0
fi

# Comprobar updates para el script
SERVIDOR_WEB="https://raw.githubusercontent.com/wifislax-ng/wifislax-updaters/master"
DIRECTORIO=$(find /opt/wifislax-updaters -type f -name ${SCRIPTNAME} | rev | cut -d/ -f2- | rev | head -1)
SERVIDOR_VERSION=$(timeout -s SIGTERM 3 curl -s $SERVIDOR_WEB/${DIRECTORIO##*/}/${SCRIPTNAME} | grep "SCRIPT_VERSION=" | head -1 |cut -d "=" -f2)


echo ${CYAN}Version Script$CIERRE: $ROJO${SCRIPT_VERSION:6}$BLANCO/$AMARILLO${SCRIPT_VERSION:4:2}$BLANCO/$ROJO${SCRIPT_VERSION:0:4}$CIERRE

if [ "$(ping github.com -c1 2>/dev/null)" ]; then
if [[ $SCRIPT_VERSION -lt $SERVIDOR_VERSION ]]; then
echo
echo "$ROSA"Comprobando si hay actualizaciones para el script..."$CIERRE."
echo ${ROJO}NUEVA VERSION$CIERRE
echo 
echo ${ROSA}Version Server$CIERRE: $ROJO${SERVIDOR_VERSION:6}$BLANCO/$AMARILLO${SERVIDOR_VERSION:4:2}$BLANCO/$ROJO${SERVIDOR_VERSION:0:4}$CIERRE
echo
echo ${CYAN}Actualizando ${SCRIPTNAME}
curl -s $SERVIDOR_WEB/${DIRECTORIO##*/}/${SCRIPTNAME} -o $DIRECTORIO/${SCRIPTNAME}
echo ${ROJO}LISTO$CIERRE
sleep 1
$0
exit
fi
fi

# Aseguramos la existencia del directorio de compilacion y si no existe se crea
if [ ! -d /usr/src ]; then
mkdir -p /usr/src
fi

# Menu de opciones
echo ""
PS3='Selecciona una opcion: '
OPCIONES=("${VERDE}Seguir rama del sistema ${AMARILLO}(recomendado)${CIERRE}" "${VERDE}Ultimo disponible como estable${CIERRE}" "${VERDE}Elegir uno custom${CIERRE}" "${VERDE}El ultimo disponible rcX${CIERRE}")
select OPT in "${OPCIONES[@]}"
do
    case $OPT in
        "${VERDE}Seguir rama del sistema ${AMARILLO}(recomendado)${CIERRE}")
            RAMA=`echo $(uname -r|cut -d . -f-2)`
            KERNEL_ELEGIDO=`curl -s $WEB|grep linux-$RAMA.*|head -1 |cut -d 'x' -f 4|cut -d '-' -f 2|cut -d " " -f 2|cut -d "t" -f1|sed 's/.$//g'`
            RAMA_ELEGIDO=`echo $KERNEL_ELEGIDO |cut -d "." -f-2 |sed 's/ //g'`
            FAMILIA=`echo $KERNEL_ELEGIDO|cut -d. -f1`
            DESCARGA=https://www.kernel.org/pub/linux/kernel/v$FAMILIA.x/linux-$KERNEL_ELEGIDO.tar.xz
            AUFS=$RAMA_ELEGIDO
            break;;
        "${VERDE}Ultimo disponible como estable${CIERRE}")
            KERNEL_ELEGIDO=`curl -s $WEB|grep .tar.xz|head -1|cut -d "-" -f2|cut -d "t" -f-1|sed "s/.$//g"`
            RAMA_ELEGIDO=`echo $KERNEL_ELEGIDO|cut -d "." -f-2|sed 's/ //g'`
            FAMILIA=`echo $KERNEL_ELEGIDO|cut -d. -f1`
            DESCARGA=https://www.kernel.org/pub/linux/kernel/v$FAMILIA.x/linux-$KERNEL_ELEGIDO.tar.xz
            AUFS=$RAMA_ELEGIDO
            break;;
        "${VERDE}Elegir uno custom${CIERRE}")
            CUSTOM="TRUE"
            break;;
        "${VERDE}El ultimo disponible rcX${CIERRE}")
            KERNEL_ELEGIDO=`curl -s $WEB|grep rc[0-9]|tail -1|cut -d v -f3|cut -d '"' -f-1`
            RAMA_ELEGIDO=`echo $KERNEL_ELEGIDO|cut -d "-" -f-1|sed 's/ //g'`
            FAMILIA=`echo $KERNEL_ELEGIDO|cut -d. -f1`
            DESCARGA=https://www.kernel.org/pub/linux/kernel/v$FAMILIA.x/testing/linux-$KERNEL_ELEGIDO.tar.xz
            AUFS=$FAMILIA.x-rcN
            break;;
        *)  echo opcion invalida;;
    esac
done

if [ ! -z $CUSTOM ]; then
# Numero de Kernel completo que queremos compilar
echo "$VERDE"
echo "Escribe el numero de kernel exacto que te gustaria compilar y pulsa ${BLANCO}ENTER"
echo "$ROSA"
read KERNEL_ELEGIDO
RAMA_ELEGIDO=`echo $KERNEL_ELEGIDO|cut -d "." -f-2|sed 's/ //g'`
FAMILIA=`echo $KERNEL_ELEGIDO|cut -d. -f1`
AUFS=$RAMA_ELEGIDO
DESCARGA=https://www.kernel.org/pub/linux/kernel/v$FAMILIA.x/linux-$KERNEL_ELEGIDO.tar.xz
echo "$CIERRE"
fi

# Entramos a la ruta de trabajo
cd /usr/src/

# Si el paquete no existe se descargara de internet
if [ ! -f linux-$KERNEL_ELEGIDO.tar.xz ]; then
echo ""
echo "$CYAN"Descargando sources de $PRGNAM-$KERNEL_ELEGIDO "$CIERRE"
sleep 1
echo $ROSA
wget -N -L -c -q --show-progress $DESCARGA
echo $CIERRE
fi

# Si existen restos de una prueba anterior seeliminaran
rm -rf /usr/src/$PRGNAM-$KERNEL_ELEGIDO &>/dev/null

# Descomprimir fichero
echo ""
echo "$VERDE"Descomprimiendo ..."$CIERRE"
sleep 1
tar xvf $PRGNAM-$KERNEL_ELEGIDO.tar.xz

# Entrar a la ruta del kernel descomprimido
cd $PRGNAM-$KERNEL_ELEGIDO
# Se limpia por si los de kernel.org se dejaron algun fichero que no es de kernel
make mrproper

###################################
### Generamos parche wireless  ####
###################################
cat > Negative-channel-multi.patch << "EOF"
--- a/net/wireless/chan.c	2013-08-29 18:47:51.000000000 +0200
+++ b/net/wireless/chan.c	2013-08-31 22:20:45.014734447 +0200
@@ -441,4 +441,2 @@
 		return -EOPNOTSUPP;
-	if (!cfg80211_has_monitors_only(rdev))
-		return -EBUSY;

--- a/net/mac80211/cfg.c	Tue May 28 16:57:23 2013 -0400
+++ b/net/mac80211/cfg.c	Tue May 28 17:16:15 2013 -0400
@@ -801,3 +801,4 @@
 		}
-	} else if (local->open_count == local->monitors) {
+	// Patch: Always allow channel change, even if a normal virtual interface is present
+	} else /*if (local->open_count == local->monitors)*/ {
 		local->_oper_channel = chandef->chan;


--- a/net/mac80211/cfg.c
+++ b/net/mac80211/cfg.c
@@ -3588,9 +3589,9 @@ static int ieee80211_cfg_get_channel
 	if (chanctx_conf) {
 		*chandef = chanctx_conf->def;
 		ret = 0;
-	} else if (local->open_count > 0 &&
+	} else /*if (local->open_count > 0 &&
 		   local->open_count == local->monitors &&
-		   sdata->vif.type == NL80211_IFTYPE_MONITOR) {
+		   sdata->vif.type == NL80211_IFTYPE_MONITOR)*/ {
 		if (local->use_chanctx)
 			*chandef = local->monitor_chandef;
 		else

EOF

# Aplicamos parche si hay error se parara el proceso ( exit 1 )
echo ""
echo ""$VERDE"Aplicando parche wireless para channel -1 "$BLANCO"..."$CIERRE""
sleep 1
patch -f -p1 < Negative-channel-multi.patch || exit 1


# Parche para bug temporal ralink no ve clientes en modo monitor
if [ $RAMA_ELEGIDO = 4.4 ]; then
cat > ralink.patch << "EOF"
--- a/drivers/net/wireless/rt2x00/rt2400pci.c
+++ b/drivers/net/wireless/rt2x00/rt2400pci.c
@@ -273,8 +273,10 @@ static void rt2400pci_config_filter(struct rt2x00_dev *rt2x00dev,
 			   !(filter_flags & FIF_PLCPFAIL));
 	rt2x00_set_field32(&reg, RXCSR0_DROP_CONTROL,
 			   !(filter_flags & FIF_CONTROL));
-	rt2x00_set_field32(&reg, RXCSR0_DROP_NOT_TO_ME, 1);
+	rt2x00_set_field32(&reg, RXCSR0_DROP_NOT_TO_ME,
+			   !test_bit(CONFIG_MONITORING, &rt2x00dev->flags));
 	rt2x00_set_field32(&reg, RXCSR0_DROP_TODS,
+			   !test_bit(CONFIG_MONITORING, &rt2x00dev->flags) &&
 			   !rt2x00dev->intf_ap_count);
 	rt2x00_set_field32(&reg, RXCSR0_DROP_VERSION_ERROR, 1);
 	rt2x00mmio_register_write(rt2x00dev, RXCSR0, reg);
--- a/drivers/net/wireless/rt2x00/rt2500pci.c
+++ b/drivers/net/wireless/rt2x00/rt2500pci.c
@@ -274,8 +274,10 @@ static void rt2500pci_config_filter(struct rt2x00_dev *rt2x00dev,
 			   !(filter_flags & FIF_PLCPFAIL));
 	rt2x00_set_field32(&reg, RXCSR0_DROP_CONTROL,
 			   !(filter_flags & FIF_CONTROL));
-	rt2x00_set_field32(&reg, RXCSR0_DROP_NOT_TO_ME, 1);
+	rt2x00_set_field32(&reg, RXCSR0_DROP_NOT_TO_ME,
+			   !test_bit(CONFIG_MONITORING, &rt2x00dev->flags));
 	rt2x00_set_field32(&reg, RXCSR0_DROP_TODS,
+			   !test_bit(CONFIG_MONITORING, &rt2x00dev->flags) &&
 			   !rt2x00dev->intf_ap_count);
 	rt2x00_set_field32(&reg, RXCSR0_DROP_VERSION_ERROR, 1);
 	rt2x00_set_field32(&reg, RXCSR0_DROP_MCAST,
--- a/drivers/net/wireless/rt2x00/rt2500usb.c
+++ b/drivers/net/wireless/rt2x00/rt2500usb.c
@@ -437,8 +437,10 @@ static void rt2500usb_config_filter(struct rt2x00_dev *rt2x00dev,
 			   !(filter_flags & FIF_PLCPFAIL));
 	rt2x00_set_field16(&reg, TXRX_CSR2_DROP_CONTROL,
 			   !(filter_flags & FIF_CONTROL));
-	rt2x00_set_field16(&reg, TXRX_CSR2_DROP_NOT_TO_ME, 1);
+	rt2x00_set_field16(&reg, TXRX_CSR2_DROP_NOT_TO_ME,
+			   !test_bit(CONFIG_MONITORING, &rt2x00dev->flags));
 	rt2x00_set_field16(&reg, TXRX_CSR2_DROP_TODS,
+			   !test_bit(CONFIG_MONITORING, &rt2x00dev->flags) &&
 			   !rt2x00dev->intf_ap_count);
 	rt2x00_set_field16(&reg, TXRX_CSR2_DROP_VERSION_ERROR, 1);
 	rt2x00_set_field16(&reg, TXRX_CSR2_DROP_MULTICAST,
--- a/drivers/net/wireless/rt2x00/rt2800lib.c
+++ b/drivers/net/wireless/rt2x00/rt2800lib.c
@@ -1490,7 +1490,8 @@ void rt2800_config_filter(struct rt2x00_dev *rt2x00dev,
 			   !(filter_flags & FIF_FCSFAIL));
 	rt2x00_set_field32(&reg, RX_FILTER_CFG_DROP_PHY_ERROR,
 			   !(filter_flags & FIF_PLCPFAIL));
-	rt2x00_set_field32(&reg, RX_FILTER_CFG_DROP_NOT_TO_ME, 1);
+	rt2x00_set_field32(&reg, RX_FILTER_CFG_DROP_NOT_TO_ME,
+			   !test_bit(CONFIG_MONITORING, &rt2x00dev->flags));
 	rt2x00_set_field32(&reg, RX_FILTER_CFG_DROP_NOT_MY_BSSD, 0);
 	rt2x00_set_field32(&reg, RX_FILTER_CFG_DROP_VER_ERROR, 1);
 	rt2x00_set_field32(&reg, RX_FILTER_CFG_DROP_MULTICAST,
--- a/drivers/net/wireless/rt2x00/rt2x00.h
+++ b/drivers/net/wireless/rt2x00/rt2x00.h
@@ -669,6 +669,7 @@ enum rt2x00_state_flags {
 	CONFIG_POWERSAVING,
 	CONFIG_HT_DISABLED,
 	CONFIG_QOS_DISABLED,
+	CONFIG_MONITORING,
 
 	/*
 	 * Mark we currently are sequentially reading TX_STA_FIFO register
--- a/drivers/net/wireless/rt2x00/rt2x00config.c
+++ b/drivers/net/wireless/rt2x00/rt2x00config.c
@@ -277,6 +277,11 @@ void rt2x00lib_config(struct rt2x00_dev *rt2x00dev,
 	else
 		clear_bit(CONFIG_POWERSAVING, &rt2x00dev->flags);
 
+	if (conf->flags & IEEE80211_CONF_MONITOR)
+		set_bit(CONFIG_MONITORING, &rt2x00dev->flags);
+	else
+		clear_bit(CONFIG_MONITORING, &rt2x00dev->flags);
+
 	rt2x00dev->curr_band = conf->chandef.chan->band;
 	rt2x00dev->curr_freq = conf->chandef.chan->center_freq;
 	rt2x00dev->tx_power = conf->power_level;
--- a/drivers/net/wireless/rt2x00/rt2x00mac.c
+++ b/drivers/net/wireless/rt2x00/rt2x00mac.c
@@ -385,11 +385,6 @@ void rt2x00mac_configure_filter(struct ieee80211_hw *hw,
 			*total_flags |= FIF_PSPOLL;
 	}
 
-	/*
-	 * Check if there is any work left for us.
-	 */
-	if (rt2x00dev->packet_filter == *total_flags)
-		return;
 	rt2x00dev->packet_filter = *total_flags;
 
 	rt2x00dev->ops->lib->config_filter(rt2x00dev, *total_flags);
--- a/drivers/net/wireless/rt2x00/rt61pci.c
+++ b/drivers/net/wireless/rt2x00/rt61pci.c
@@ -530,8 +530,10 @@ static void rt61pci_config_filter(struct rt2x00_dev *rt2x00dev,
 			   !(filter_flags & FIF_PLCPFAIL));
 	rt2x00_set_field32(&reg, TXRX_CSR0_DROP_CONTROL,
 			   !(filter_flags & (FIF_CONTROL | FIF_PSPOLL)));
-	rt2x00_set_field32(&reg, TXRX_CSR0_DROP_NOT_TO_ME, 1);
+	rt2x00_set_field32(&reg, TXRX_CSR0_DROP_NOT_TO_ME,
+			   !test_bit(CONFIG_MONITORING, &rt2x00dev->flags));
 	rt2x00_set_field32(&reg, TXRX_CSR0_DROP_TO_DS,
+			   !test_bit(CONFIG_MONITORING, &rt2x00dev->flags) &&
 			   !rt2x00dev->intf_ap_count);
 	rt2x00_set_field32(&reg, TXRX_CSR0_DROP_VERSION_ERROR, 1);
 	rt2x00_set_field32(&reg, TXRX_CSR0_DROP_MULTICAST,
--- a/drivers/net/wireless/rt2x00/rt73usb.c
+++ b/drivers/net/wireless/rt2x00/rt73usb.c
@@ -480,8 +480,10 @@ static void rt73usb_config_filter(struct rt2x00_dev *rt2x00dev,
 			   !(filter_flags & FIF_PLCPFAIL));
 	rt2x00_set_field32(&reg, TXRX_CSR0_DROP_CONTROL,
 			   !(filter_flags & (FIF_CONTROL | FIF_PSPOLL)));
-	rt2x00_set_field32(&reg, TXRX_CSR0_DROP_NOT_TO_ME, 1);
+	rt2x00_set_field32(&reg, TXRX_CSR0_DROP_NOT_TO_ME,
+			   !test_bit(CONFIG_MONITORING, &rt2x00dev->flags));
 	rt2x00_set_field32(&reg, TXRX_CSR0_DROP_TO_DS,
+			   !test_bit(CONFIG_MONITORING, &rt2x00dev->flags) &&
 			   !rt2x00dev->intf_ap_count);
 	rt2x00_set_field32(&reg, TXRX_CSR0_DROP_VERSION_ERROR, 1);
 	rt2x00_set_field32(&reg, TXRX_CSR0_DROP_MULTICAST,
EOF
echo ""
echo ""$VERDE"Aplicando parche ralink "$BLANCO"..."$CIERRE""
sleep 1
patch -f -p1 < ralink.patch || exit 1
fi

# Parte1 avisamos por si quieres poner un config
if [ ! -f /usr/src/$PRGNAM-$KERNEL_ELEGIDO/.config ]; then
echo ""
echo ""$CYAN"No se detecto fichero config ..."$CIERRE""
echo ""
echo ""$CYAN"Si quieres añadir uno hazlo en /usr/src/$PRGNAM-$KERNEL_ELEGIDO/.config ..."$CIERRE""
echo ""$CYAN"Si no añades un config se usara la config del kernel actual."$CIERRE""
echo ""
echo ""$CYAN"Cuando pulses "$AMARILLO"ENTER "$CYAN"el proceso continuara"$CIERRE""
echo ""
read junk
fi

# Parte2 sino hay config generamos una en base al kernel actual
if [ -f /usr/src/$PRGNAM-$KERNEL_ELEGIDO/.config ]; then
echo ""
echo ""$CYAN"Usando config añadida por el usuario ..."$CIERRE""
echo ""
else
echo ""
echo ""$CYAN"Generamos fichero .config ..."$CIERRE""
echo ""
modprobe configs && zcat /proc/config.gz > /usr/src/$PRGNAM-$KERNEL_ELEGIDO/.config
fi

# Descargamos version de aufs correspondiente a nuestra rama y aplicamos
if [ $RAMA_ELEGIDO = 4.1 ]; then
RAMA_ELEGIDO=4.1.13+
AUFS=4.1.13+
fi
if [ $RAMA_ELEGIDO = 3.18 ]; then
RAMA_ELEGIDO=3.18.25+
AUFS=3.18.25+
fi
DEST=/usr/src/$PRGNAM-$KERNEL_ELEGIDO/$AUFS.patch

# Creamos parche y aplicamos
echo ""
echo ""$VERDE"Creamos y aplicamos el parche aufs "$BLANCO"..."$CIERRE""
rm -r /tmp/aufs* 2>/dev/null
mkdir /tmp/aufs$$
cd /tmp/aufs$$
if [ $FAMILIA = 4 ]; then
git clone https://github.com/sfjro/aufs4-standalone.git aufs4-standalone.git || exit 1
cd aufs4-standalone.git || exit 1
else
git clone git://git.code.sf.net/p/aufs/aufs3-standalone aufs3-standalone.git  || exit 1
cd aufs3-standalone.git || exit 1
fi
git checkout origin/aufs${AUFS} || exit 1
mkdir ../a ../b
cp -r {Documentation,fs,include} ../b
rm ../b/include/uapi/linux/Kbuild 2>/dev/null || rm ../b/include/linux/Kbuild
cd ..
diff -rupN a/ b/ > $DEST
cat aufs$FAMILIA-standalone.git/*.patch >> $DEST
rm -r /tmp/aufs$$

# Verificamos la existencia del parche aufs
if [ ! -f /usr/src/$PRGNAM-$KERNEL_ELEGIDO/$AUFS.patch ]; then
echo ""
echo ""$ROJO"La creacion del parche aufs a fallado ...saliendo..."
echo ""
sleep 1
exit 0
fi

# Aplicamos parche aufs
cd /usr/src/$PRGNAM-$KERNEL_ELEGIDO
patch -f -p1 -i $AUFS.patch || exit 1

# Compilamos el kernel
make oldconfig || exit 1
make xconfig || exit 1

# Variables para calcular tiempo de inicio
COMIENZO=$(date +%s)

# Comienza la compilacion del kernel
make || exit 1
make modules || exit 1

# Arquitectura segun el fichero config
if [ ! -z "`grep -i 'CONFIG_64BIT=y' .config`" ]; then
HEADERS=x86_64
IMAGEN=x86_64
ARCH=x86_64
else
HEADERS=i386
IMAGEN=x86
ARCH=i586
fi

# Comprobar si es un kernel SMP (pae)
if [ -z "`grep -i 'CONFIG_HIGHMEM64G=y' .config`" ]; then
SMP=""
VMLINUZ="vmlinuz"
VMLINUZCONFIG=""
else
SMP="SMP-"
VMLINUZ="vmlinuz2"
VMLINUZCONFIG="smp"
fi

# Creamos la tuta de destina a instalar el kernel
mkdir -p $HOME/Desktop/$SMP$MODNAM-$KERNEL_ELEGIDO-$ARCH-$BUILD$TAG
make modules_install INSTALL_MOD_PATH=$HOME/Desktop/$SMP$MODNAM-$KERNEL_ELEGIDO-$ARCH-$BUILD$TAG || exit 1

# Instalamos las cabeceras kernel-headers
make headers_install ARCH=$HEADERS INSTALL_HDR_PATH=$HOME/Desktop/$SMP$MODNAM-$KERNEL_ELEGIDO-$ARCH-$BUILD$TAG/usr || exit 1
rm -r $HOME/Desktop/$SMP$MODNAM-$KERNEL_ELEGIDO-$ARCH-$BUILD$TAG/usr/include/*/.install
rm -r $HOME/Desktop/$SMP$MODNAM-$KERNEL_ELEGIDO-$ARCH-$BUILD$TAG/usr/include/*/..install.cmd

# Copiamos el vmlinuz
cp /usr/src/$PRGNAM-$KERNEL_ELEGIDO/arch/$IMAGEN/boot/bzImage $HOME/Desktop/$VMLINUZ &>/dev/null

# Generamos kernel sources recortadas
mv System.map ../
make clean
mv ../System.map .
make prepare
make scripts
rm -Rf Documentation drivers fs net sound firmware
ls -1d arch/* | grep -v $IMAGEN | xargs rm -Rf
ls -1d include/* | grep asm- | grep -v $IMAGEN | grep -v generic | xargs rm -Rf
cp include/generated/* include/linux &>/dev/null

# Preparamos creacion de xzm
mkdir -p $HOME/Desktop/$SMP$MODNAM-$KERNEL_ELEGIDO-$ARCH-$BUILD$TAG/usr/src
cp -r /usr/src/$PRGNAM-$KERNEL_ELEGIDO $HOME/Desktop/$SMP$MODNAM-$KERNEL_ELEGIDO-$ARCH-$BUILD$TAG/usr/src

# Realizamos limpieza
RUTA_LIMPIEZA=$HOME/Desktop/$SMP$MODNAM-$KERNEL_ELEGIDO-$ARCH-$BUILD$TAG/usr/src/$PRGNAM-$KERNEL_ELEGIDO
FILES_BORRAR="kernel.txt Negative-channel-multi.patch ralink.patch $AUFS.patch .config.old"
for X in $FILES_BORRAR; do
rm $RUTA_LIMPIEZA/$X &>/dev/null
done

# Por que usa una script que baja todos los firmwares desde el git
rm -Rf $HOME/Desktop/$SMP$MODNAM-$KERNEL_ELEGIDO-$ARCH-$BUILD$TAG/lib/firmware

# Creamos xzm de kernel + sources
mksquashfs $HOME/Desktop/$SMP$MODNAM-$KERNEL_ELEGIDO-$ARCH-$BUILD$TAG $HOME/Desktop/$SMP$MODNAM-$KERNEL_ELEGIDO-$ARCH-$BUILD$TAG.xzm -comp xz -b 256K
mv $HOME/Desktop/$SMP$MODNAM-$KERNEL_ELEGIDO-$ARCH-$BUILD$TAG.xzm $HOME/Desktop/$M0DNUM-$SMP$MODNAM-$KERNEL_ELEGIDO-$ARCH-$BUILD$TAG.xzm

# Finalizamos
rm -Rf $HOME/Desktop/$SMP$MODNAM-$KERNEL_ELEGIDO-$ARCH-$BUILD$TAG
AHORA=$(($(date +%s)-3600));
TIEMPO="$(date --date=@$(($AHORA-$COMIENZO)) +%X)"
echo ""
echo "${AMARILLO}Tiempo empleado${BLANCO}: $TIEMPO"
echo ""
# Si no es wifislax ya hemos acabado aqui.
if [ ! -f /etc/wifislax-version ]; then
echo ""
echo ""$AMARILLO"Bye Bye"$CIERRE""
exit 0
fi
# En modo live es absurdo ofrecer instarlo
if [ -d /mnt/live ]; then
echo ""
echo ""$AMARILLO"Bye Bye"$CIERRE""
exit 0
fi
# Si se trata de wifislax en HDD puedo instalar el kernel.
echo ""$AMARILLO"Pulsa ENTER si quieres instalar el kernel,si no te interesa cierra el scipt."$CIERRE""
read junk
echo ""
echo ""$VERDE"Instalando Kernel $KERNEL_ELEGIDO en sistema ..."$CIERRE""

cp -r $HOME/Desktop/$VMLINUZ /boot/vmlinuz-$KERNEL_ELEGIDO-$VMLINUZCONFIG-wifislax
xzm2dir $HOME/Desktop/$M0DNUM-$SMP$MODNAM-$KERNEL_ELEGIDO-$ARCH-$BUILD$TAG.xzm /
update-grub
echo ""
echo ""$CYAN"Instalacion completada ..."$CIERRE""
echo ""
echo ""$AMARILLO"Bye Bye"$CIERRE""