#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20151117

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=qjackctl
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=http://qjackctl.sourceforge.net/#Downloads
	VERSION=`curl -s $WEB|grep tar.gz|head -1|rev|cut -d- -f-1|rev|cut -d t -f-1|sed 's/.$//g'`
	EXTENSION=tar.gz
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	DOWNLOAD=http://downloads.sourceforge.net/$PRGNAM/$SOURCES
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="jack-audio-connection-kit qt5"
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Configurando ..."$CIERRE"
sleep 1
echo "QMAKE_CXXFLAGS_RELEASE=$SLKCFLAGS" >> qjackctl.pro.in

CFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --mandir=/usr/man \
  --docdir=/usr/doc/$PRGNAM-$VERSION \
  --build=$ARCH-slackware-linux

echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1
make || exit 1
make install DESTDIR=$PKG || exit 1

echo '[Desktop Entry]
Name=QjackCtl
GenericName=JACK Control
Comment=QjackCtl is a JACK Audio Connection Kit Qt GUI Interface
Exec=qjackctl
Icon=qjackctl
Categories=Audio;AudioVideo;X-MIDI;X-JACK;X-ALSA;Qt;
Terminal=false
Type=Application'> $PKG/usr/share/applications/qjackctl.desktop
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
#Compronar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales