#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20150902

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=slapt-get
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=http://software.jaos.org/
	VERSION=`curl -s $WEB | grep slapt-get | grep source | grep .tar.gz | cut -d- -f4 | cut -d '>' -f2 | cut -d ' ' -f1 |sed "s/ //g"`
	DOWNLOAD=${WEB}source/slapt-get/$PRGNAM-$VERSION.tar.gz
}

# Si el paquete no existe se descargara de internet
F_download(){
	if [ ! -f $PRGNAM-$VERSION.tar.gz ]; then
	echo 
	echo "$CYAN"Descargando sources de $PRGNAM-$VERSION"$CIERRE"
	sleep 1
	aria2c -x 3 $DOWNLOAD
	fi
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo ""
echo "$VERDE"Descomprimiendo ..."$CIERRE"
sleep 3
tar xvf $PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
find -L . \
  \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 -o -perm 511 \) \
  -exec chmod 755 {} \; -o \
  \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
  -exec chmod 644 {} \;
  
make -j$NUCLEOS || exit 1
make install DESTDIR=$PKG

rm -rf $PKG/etc/slapt-get/slapt-getrc

echo '# Working directory for local storage/cache.
WORKINGDIR=/var/slapt-get

# Exclude package names and expressions.
# To exclude pre and beta packages, add this to the exclude: 
#   [0-9\_\.\-]{1}pre[0-9\-\.\-]{1}
EXCLUDE=^kernel-.*,.*-[0-9]+dl$,x86_64,-*sw,^sysvinit-scripts,

# Base url to directory with a PACKAGES.TXT.
SOURCE=ftp://ftp.slackware.com/pub/slackware/slackware-current/
SOURCE=ftp://ftp.slackware.com/pub/slackware/slackware-current/extra/
SOURCE=ftp://ftp.slackware.com/pub/slackware/slackware-current/testing/
SOURCE=ftp://ftp.slackware.com/pub/slackware/slackware-current/pasture/

# Packages on a CD/DVD.
# SOURCE=file:///mnt/cdrom/:OFFICIAL

# Home made packages.
# SOURCE=file:///var/www/packages/:CUSTOM' > $PKG/etc/slapt-get/slapt-getrc
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
F_download
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales
