#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20151024

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=ttf-mscorefonts
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=http://sourceforge.net/projects/corefonts/files/the%20fonts/final/
	VERSION=0.1
	DOWNLOAD=
}

# Si el paquete no existe se descargara de internet
F_download(){
	echo 
	echo "$CYAN"Descargando sources de $PRGNAM-$VERSION"$CIERRE"
	sleep 1
	for x in andale32.exe arial32.exe arialb32.exe comic32.exe courie32.exe georgi32.exe impact32.exe times32.exe trebuc32.exe verdan32.exe wd97vwr32.exe webdin32.exe; do
	if [ ! -f $x ]; then
	aria2c -x 3 ${WEB}$x
	fi
	done
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
	echo 
	echo "$CYAN"Descargando sources de $PRGNAM-$VERSION"$CIERRE"
	sleep 1
	rm -rf $PRGNAM-$VERSION
	mkdir $PRGNAM-$VERSION
	mv *.exe $PRGNAM-$VERSION
	cd $PRGNAM-$VERSION
	chown -R root:root .
	find -L . \
	\( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
	-o -perm 511 \) -exec chmod 755 {} \; -o \
	\( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
	-o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
  
mkdir -p $PKG/usr/share/fonts/TTF/msttcorefonts
cabextract *.exe -L -F *.TTF -d $PKG/usr/share/fonts/TTF/msttcorefonts
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
F_download
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales
