#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20160221
CATEGORIA="Editores de audio"

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=ardour
	SRCNAM=Ardour
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=http://www.liwjatan.at/files/src/ardour/
	VERSION=`curl -s $WEB | grep .tar.bz2 | head -1 | cut -d- -f3 | cut -d t -f1 | sed "s/.$//g"`
	RAMA=`echo $VERSION | cut -d . -f1`
	EXTENSION=tar.bz2
	SOURCES=${SRCNAM}-${VERSION}.$EXTENSION
	DOWNLOAD=${WEB}$SOURCES
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="graphviz liblrdf aubio"
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
  python waf configure --prefix=/usr \
                        --configdir=/etc \
                        --with-backends="jack,alsa" \
                        --libjack=weak \
                        --optimize \
                        --cxx11 \
                        --docs

  python waf build $MAKEFLAGS
  
  python2 waf install --destdir=$PKG
  
# Entrada a menu
mkdir -p $PKG/usr/share/applications
echo "[Desktop Entry]
Name=Ardour $RAMA
Comment=Multitrack hard disk recorder
Exec=ardour$RAMA
Icon=/usr/share/ardour$RAMA/icons/ardour_icon_256px.png
Terminal=false
Type=Application
X-MultipleArgs=false
Categories=Audio;AudioVideoEditing;AudioVideo;Video;" > $PKG/usr/share/applications/$PRGNAM.desktop
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
#Compronar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales
