#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20160228
CATEGORIA="Editores de audio"

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=ardour
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://github.com/Ardour/${PRGNAM}
	VERSION=`curl -s $WEB/releases|grep tar.gz|head -1|cut -d t -f1|cut -d / -f5|sed "s/.$//g"`
	RAMA=`echo $VERSION | cut -d . -f1`
	WEB=git://git.ardour.org/ardour/ardour.git
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="graphviz liblrdf aubio"
f_dependencias
}

# Git clone
F_download(){
if [ -d $TMP/$PRGNAM ]; then
rm -rf $TMP/$PRGNAM
fi
echo ""
echo "$VERDE"Descargando sources de ${AMARILLO}$PRGNAM-$VERSION${BLANCO}..."$CIERRE"
sleep 1
cd $TMP
git clone $WEB
cd $TMP/$PRGNAM
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
  python waf configure --prefix=/usr \
                        --configdir=/etc \
                        --with-backends="jack,alsa" \
                        --libjack=weak \
                        --optimize \
                        --cxx11 \
                        --docs

  python waf build $MAKEFLAGS
  
  python2 waf install --destdir=$PKG
  
# Entrada a menu
mkdir -p $PKG/usr/share/applications
echo "[Desktop Entry]
Name=Ardour $RAMA
Comment=Multitrack hard disk recorder
Exec=ardour$RAMA
Icon=/usr/share/ardour$RAMA/icons/ardour_icon_256px.png
Terminal=false
Type=Application
X-MultipleArgs=false
Categories=Audio;AudioVideoEditing;AudioVideo;Video;" > $PKG/usr/share/applications/$PRGNAM.desktop
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
#Compronar dependencias
F_dependencias
# Git clone
F_download
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales