#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20151115
CATEGORIA="Editores de audio"

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=audacity
	SRCNAM=Audacity
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://github.com/audacity/audacity/releases
	VERSION=`curl -s $WEB|grep [0-9].tar.gz|head -1|cut -d- -f2|cut -d t -f-1|sed 's/.$//g'`
	EXTENSION=tar.gz
	SOURCES=$SRCNAM-$VERSION.$EXTENSION
	DOWNLOAD=https://github.com/audacity/audacity/archive/$SOURCES
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="wxPython"
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){  
# Configuramos paquete
echo ""
echo "$VERDE"Configurando ..."$CIERRE"
sleep 1

if [ -x /usr/bin/listplugins ];      then do_ladspa="--with-ladspa";          else do_ladspa="--without-ladspa";   fi
if pkg-config --exists libavcodec;   then do_ffmpeg="-ffmpeg=system";         else do_ffmpeg="out-ffmpeg";         fi
if pkg-config --exists soundtouch;   then do_soundtouch="-soundtouch=system"; else do_soundtouch="out-soundtouch"; fi
if pkg-config --exists twolame;      then do_twolame="-libtwolame=system";    else do_twolame="out-libtwolame";    fi
if pkg-config --exists vamp-hostsdk; then do_vamp="-libvamp=system";          else do_vamp="out-libvamp";          fi
if $(pkg-config --exists lilv-0) && $(pkg-config --exists suil-0); then do_lv2="-lv2=system"; else do_lv2="out-lv2"; fi

# fix vamp plugin search path on x86_64 - thanks to B. Watson
sed -i "s,lib/vamp,lib$LIBDIRSUFFIX/vamp,g" \
  lib-src/libvamp/src/vamp-hostsdk/PluginHostAdapter.cpp || true

# Patch
echo "ZGlmZiAtTmF1ciBhdWRhY2l0eS1zcmMtMi4wLjYtb3JpZy9zcmMvRkZtcGVnLmggYXVkYWNpdHkt
c3JjLTIuMC42L3NyYy9GRm1wZWcuaAotLS0gYXVkYWNpdHktc3JjLTIuMC42LW9yaWcvc3JjL0ZG
bXBlZy5oCTIwMTQtMDktMjggMjE6NTQ6NTUuMTU5NjM2MjA4IC0wNDAwCisrKyBhdWRhY2l0eS1z
cmMtMi4wLjYvc3JjL0ZGbXBlZy5oCTIwMTQtMDktMjggMjE6NTU6MTEuMjQ2Mjc2NzY2IC0wNDAw
CkBAIC02ODgsNyArNjg4LDcgQEAKICAgIEZGTVBFR19GVU5DVElPTl9XSVRIX1JFVFVSTigKICAg
ICAgIEFWT3V0cHV0Rm9ybWF0KiwKICAgICAgIGF2X29mb3JtYXRfbmV4dCwKLSAgICAgIChBVk91
dHB1dEZvcm1hdCAqZiksCisgICAgICAoY29uc3QgQVZPdXRwdXRGb3JtYXQgKmYpLAogICAgICAg
KGYpCiAgICApOwogICAgRkZNUEVHX0ZVTkNUSU9OX1dJVEhfUkVUVVJOKApAQCAtNzU1LDcgKzc1
NSw3IEBACiAgICBGRk1QRUdfRlVOQ1RJT05fV0lUSF9SRVRVUk4oCiAgICAgICBpbnQsCiAgICAg
ICBhdl9maWZvX3NpemUsCi0gICAgICAoQVZGaWZvQnVmZmVyICpmKSwKKyAgICAgIChjb25zdCBB
VkZpZm9CdWZmZXIgKmYpLAogICAgICAgKGYpCiAgICApOwogICAgRkZNUEVHX0ZVTkNUSU9OX1dJ
VEhfUkVUVVJOKApAQCAtODAxLDcgKzgwMSw3IEBACiAgICBGRk1QRUdfRlVOQ1RJT05fV0lUSF9S
RVRVUk4oCiAgICAgICBBVkRpY3Rpb25hcnlFbnRyeSAqLAogICAgICAgYXZfZGljdF9nZXQsCi0g
ICAgICAoQVZEaWN0aW9uYXJ5ICptLCBjb25zdCBjaGFyICprZXksIGNvbnN0IEFWRGljdGlvbmFy
eUVudHJ5ICpwcmV2LCBpbnQgZmxhZ3MpLAorICAgICAgKGNvbnN0IEFWRGljdGlvbmFyeSAqbSwg
Y29uc3QgY2hhciAqa2V5LCBjb25zdCBBVkRpY3Rpb25hcnlFbnRyeSAqcHJldiwgaW50IGZsYWdz
KSwKICAgICAgIChtLCBrZXksIHByZXYsIGZsYWdzKQogICAgKTsKICAgIEZGTVBFR19GVU5DVElP
Tl9XSVRIX1JFVFVSTigK" | base64 -d > $TMP/audacity-ffmpeg.patch
patch -p1 < $TMP/audacity-ffmpeg.patch
  
# libsoxr is the new default resampling library
LDFLAGS="-L/usr/lib$LIBDIRSUFFIX" \
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
WX_CONFIG=/usr/bin/wx-config-2.8 ./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --enable-unicode \
  --enable-nyquist \
  --with-expat=system \
  --with-libvorbis=system \
  --with-libmad=system \
  --with-libflac=system \
  --with-libsndfile=system \
  --with-libid3tag=system \
  --with-libsoxr \
  --with-portaudio \
  $do_ladspa \
  --with$do_ffmpeg \
  --with$do_lv2 \
  --with$do_soundtouch \
  --with$do_twolame \
  --with$do_vamp \
  --without-libresample \
  --without-libsamplerate

# ensure we use the system headers for these: note that we do this after the
# configure as this last wants to run sub-configures in these dirs
for i in ffmpeg expat libid3tag libflac libmad libresample libsndfile libvamp lv2 soundtouch twolame; do
  rm -rf lib-src/$i
done

echo ""
echo "$VERDE"Compilamos ..."$CIERRE"
sleep 1
make  || exit 1
make install DESTDIR=$PKG
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del script
f_versionInstalada
# Comprobar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales