#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20151024
CATEGORIA="Editores de audio"

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	WEB=http://sourceforge.net/projects/audacity/files/audacity/
	#VERSION=`curl -s $WEB | grep -m 1 "<tr title="|cut -d '"' -f2| sed "s/ //g"`
	VERSION=2.1.0
	PRGNAM=audacity
	echo -ne "\033]2;${PRGNAM}_updater\007"
	EXTENSION=tar.xz
	SOURCES=$PRGNAM-src-$VERSION.$EXTENSION
	SRCNAM=$PRGNAM-src-$VERSION
	DOWNLOAD=http://ponce.cc/slackware/sources/repo/$SRCNAM.tar.xz
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="wxPython"
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
# Fix vamp plugin search path on x86_64 - thanks to B. Watson
sed -i "s,lib/vamp,lib$LIBDIRSUFFIX/vamp,g" \
       lib-src/libvamp/src/vamp-hostsdk/PluginHostAdapter.cpp
       
# Renombramos temporalmente este fichero y al acabar lo devolvemos
if [ -f /usr/lib/libvamp-hostsdk.la ]; then
mv -f /usr/lib/libvamp-hostsdk.la /usr/lib/libvamp-hostsdk.la.RENOMBRADO
fi
  
# Configuramos paquete
echo ""
echo "$VERDE"Configurando ..."$CIERRE"
sleep 3

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
WX_CONFIG=/usr/bin/wx-config-2.8 ./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --disable-dynamic-loading \
  --with-libvamp \
  --enable-unicode \
  --enable-nyquist \
  --enable-vamp \
  --with-expat \
  --with-libvorbis \
  --with-libmad \
  --with-libflac \
  --with-libsndfile \
  --with-libid3tag \
  --with-libresample \
  --with-ffmpeg \
  --with-soundtouch \
  --with-libtwolame

make  || exit 1
make install DESTDIR=$PKG

# Devolvemos el fichero renombrado anteriormente
if [ -f /usr/lib/libvamp-hostsdk.la.RENOMBRADO ]; then
mv -f /usr/lib/libvamp-hostsdk.la.RENOMBRADO /usr/lib/libvamp-hostsdk.la
fi
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del script
f_versionInstalada
# Comprobar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales