#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20150919

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=bluray-keys
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=http://www.labdv.com/aacs/KEYDB.cfg
	VERSION=`curl -s $WEB | grep VUK | head -1 | cut -d ' ' -f5`
	DOWNLOAD=$WEB
}

# Si el paquete no existe se descargara de internet
F_download(){
	if [ ! -f KEYDB.cfg ]; then
	echo 
	echo "$CYAN"Descargando sources de $PRGNAM-$VERSION"$CIERRE"
	sleep 1
	aria2c -x 3 $DOWNLOAD
	fi
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Creando paquete ..."$CIERRE"
sleep 2
mkdir -p $PKG/root/.config/aacs/
cp -rf $TMP/KEYDB.cfg $PKG/root/.config/aacs/
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura noarch
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
F_download
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales
