#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20160322
CATEGORIA=Grabacion

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=brasero
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://download.gnome.org/sources/$PRGNAM
	RAMA=`curl -s $WEB/|egrep -o ">[0-9].[0-9]{1,2}/"|tr -d '>/'|egrep -v "1$|3$|5$|7$|9$"|tail -1`
	VERSION=`curl -s ${WEB}/${RAMA}/|egrep -o "IS-$RAMA.[0-9]{1,2}"|cut -d- -f2|tail -1`
	EXTENSION=tar.xz
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	DOWNLOAD=$WEB/$RAMA/$SOURCES
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="gst-plugins-bad"
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
# Configuramos paquete
echo ""
echo "$VERDE"Configurando ..."$CIERRE"
sleep 1
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --enable-static=no \
  --enable-shared=yes \
  --enable-gtk-doc=no \
  --disable-schemas-compile \
  --enable-nautilus=no \
  --enable-libburnia=yes

make  || exit 1
make install DESTDIR=$PKG
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del script
f_versionInstalada
# Comprobar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales