#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20160420
CATEGORIA="Reproductores multimedia"

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=clementine
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://www.clementine-player.org/es/downloads
	VERSION=`curl -s $WEB|grep Clementine| grep .tar.gz|head -1|cut -d "/" -f 7|cut -d t -f-1|sed 's/.$//g'`
	EXTENSION=tar.gz
	SOURCES=$VERSION.$EXTENSION
	SRCNAM=Clementine-$VERSION
	DOWNLOAD=https://github.com/clementine-player/Clementine/archive/$SOURCES
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="libspotify libechonest cryptopp"
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo "LS0tIGEvc3JjL2NvcmUvZGF0YWJhc2UuY3BwCisrKyBiL3NyYy9jb3JlL2RhdGFiYXNlLmNwcApA
QCAtMjY1LDYgKzI2NSwxNiBAQAogICBTdGF0aWNJbml0KCk7CgogICB7CisjaWZkZWYgU1FMSVRF
X0RCQ09ORklHX0VOQUJMRV9GVFMzX1RPS0VOSVpFUgorICAgIFFWYXJpYW50IHYgPSBkYi5kcml2
ZXIoKS0+aGFuZGxlKCk7CisgICAgaWYgKHYuaXNWYWxpZCgpICYmIHFzdHJjbXAodi50eXBlTmFt
ZSgpLCAic3FsaXRlMyoiKSA9PSAwKSB7CisgICAgICBzcWxpdGUzKiBoYW5kbGUgPSAqc3RhdGlj
X2Nhc3Q8c3FsaXRlMyoqPih2LmRhdGEoKSk7CisgICAgICBpZiAoaGFuZGxlKSB7ICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAKKyAgICAgICAgc3FsaXRlM19kYl9jb25maWcoaGFuZGxlLCBTUUxJVEVf
REJDT05GSUdfRU5BQkxFX0ZUUzNfVE9LRU5JWkVSLCAxLCBOVUxMKTsgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
IAorICAgICAgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCisgICAgfSAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKKyNlbmRpZiAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgIAorICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgCiAgICAgUVNxbFF1ZXJ5IHNldF9mdHNfdG9rZW5pemVyKCJTRUxFQ1QgZnRzM190b2tl
bml6ZXIoOm5hbWUsIDpwb2ludGVyKSIsIGRiKTsKICAgICBzZXRfZnRzX3Rva2VuaXplci5iaW5k
VmFsdWUoIjpuYW1lIiwgInVuaWNvZGUiKTsKICAgICBzZXRfZnRzX3Rva2VuaXplci5iaW5kVmFs
dWUoCg==" | base64 -d > $TMP/sqlite.patch
patch -p1 -i $TMP/sqlite.patch || exit 1

echo ""
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1

mkdir build
cd build
  cmake \
	-DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
	-DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS" \
	-DCMAKE_INSTALL_PREFIX=/usr \
	-DLIB_SUFFIX=${LIBDIRSUFFIX} \
	-DMAN_INSTALL_DIR=/usr/man \
	-DCMAKE_BUILD_TYPE=Release \
	..
  make all CFLAGS="-fPIC" PMFLAGS="-DNEWBUFFER"  || exit 1
  make install DESTDIR=$PKG
cd ..
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del script
f_versionInstalada
#Compronar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales