#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20151024
CATEGORIA="Editores de video"

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	WEB=http://sourceforge.net/projects/dvdauthor/files/dvdauthor/
	VERSION=`curl -s $WEB | grep /latest | cut -d '/' -f 8 | cut -d ":" -f 1 | cut -d '-' -f 2 | cut -d "t" -f-1`
	PRGNAM=dvdauthor
	echo -ne "\033]2;${PRGNAM}_updater\007"
	EXTENSION=tar.gz
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	DOWNLOAD=$WEB/$VERSION/$SOURCES
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
# Generamos parche y aplicamos
if [ $VERSION = "0.7.1" ]; then
echo "Aplicamos parche ..."
cat > glibc2.20.patch << "EOF"
Index: dvdauthor/src/dvdvml.l
===================================================================
--- dvdauthor/src/dvdvml.l
+++ dvdauthor/src/dvdvml.l      2014-09-14 19:36:05.098847465 +0000
@@ -19,6 +19,7 @@
  * USA
  */
 
+#include "config.h"
 #include "compat.h" /* needed for bool */
 #include "dvdvm.h"
 #include "dvdvmy.h"
Index: dvdauthor/src/dvdvmy.y
===================================================================
--- dvdauthor/src/dvdvmy.y
+++ dvdauthor/src/dvdvmy.y      2014-09-14 19:36:28.251618378 +0000
@@ -19,6 +19,7 @@
  * USA
  */
 
+#include "config.h"
 #include "compat.h" /* needed for bool */
 #include "dvdvm.h"

EOF
# Aplicamos parche
patch -p1 < glibc2.20.patch
fi
 
# Configuramos paquete
echo ""
echo "$VERDE"Configurando ..."$CIERRE"
sleep 3
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib$LIBDIRSUFFIX \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --mandir=/usr/man \
  --build=$ARCH-slackware-linux
  
# Compilamos paquete
echo ""
echo "$VERDE"Compilando ..."$CIERRE"
sleep 3
make  || exit 1
make install-strip DESTDIR=$PKG
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del script
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Creamos xzm , instalamos y salimos
f_tareasFinales
