#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20150502
CATEGORIA="Editores de video"

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	WEB=http://sourceforge.net/projects/dvdstyler/files/dvdstyler/
	VERSION=`curl -s $WEB | grep /latest | cut -d '/' -f 8 | cut -d ":" -f 1 | cut -d '-' -f 2 | cut -d "t" -f-1`
	PRGNAM=dvdstyler
	SPRGNAM=DVDStyler
	echo -ne "\033]2;${PRGNAM}_updater\007"
}

# Comprobar dependencias
F_dependencias(){
echo "$ROSA"Comprobando dependencias ..."$CIERRE"
echo ""

DEPENDENCIAS="svgview dvdauthor libquicktime_config"
CONTINUAR=0

echo "$CYAN"Dependencias de este paquete:""
sleep 3

for X in $DEPENDENCIAS; do
	
	if [ -f /usr/bin/$X ]; then
		echo ""$AMARILLO"$X :$VERDE Instalada"$CIERRE""
	else
		echo ""$AMARILLO"$X :$ROJO  No instalada"$CIERRE""
		CONTINUAR=1
	fi
done

DEPENDENCIAS2="gtk2-unicode-3.0"
for X in $DEPENDENCIAS2; do
	
	if [ -f /usr/lib/wx/config/$X ]; then
		echo ""$AMARILLO"$X :$VERDE Instalada"$CIERRE""
	else
		echo ""$AMARILLO"$X :$ROJO  No instalada"$CIERRE""
		CONTINUAR=1
	fi
done

if [ $CONTINUAR -eq 1 ]; then
	echo ""
	echo ""$ROJO"No se cumplen los requisitos no se puede continuar"$CIERRE""
	sleep 3
	exit 1
else
	echo ""
	echo ""$VERDE"Bien ..podemos continuar"$CIERRE""
	echo ""
fi
}

# Si el paquete no existe se descargara de internet
F_download(){
	if [ ! -f $SPRGNAM-$VERSION.tar.bz2 ]; then
	echo ""
	echo "$CYAN"Descargando sources de $PRGNAM-$VERSION"$CIERRE"
	sleep 3
	aria2c -x 3 $WEB/$VERSION/$SPRGNAM-$VERSION.tar.bz2
	fi
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo ""
echo "$VERDE"Descomprimiendo ..."$CIERRE"
sleep 3
rm -rf $SPRGNAM-$VERSION
tar xvf $SPRGNAM-$VERSION.tar.bz2
cd $SPRGNAM-$VERSION
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
 -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
 
# Configuramos paquete
echo ""
echo "$VERDE"Configurando ..."$CIERRE"
sleep 3

# a header is renamed in ffmpeg-0.9 so check if applies
if [ -f /usr/include/libavfilter/buffersink.h ]; then
  sed -i "s|vsink_buffer\.h|buffersink.h|" src/mediatrc_ffmpeg.cpp || exit 1
fi

sh autogen.sh || true

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --with-wx-config=/usr/bin/wx-config \
  --mandir=/usr/man \
  --docdir=/usr/doc/$PRGNAM-$VERSION \
  --build=$ARCH-slackware-linux
  
# Compilamos paquete
echo ""
echo "$VERDE"Compilando ..."$CIERRE"
sleep 3
make -j$NUCLEOS
make install DESTDIR=$PKG
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
# Comprobar dependencias
F_dependencias
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del script
f_versionInstalada
#Si no existe el fichero se descargara
F_download
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales
