#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20151024
CATEGORIA="Reproductores multimedia"

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	WEB=http://www.exaile.org/download/
	VERSION=`curl -s $WEB | grep .tar.gz | tail -1 | cut -d ">" -f 3 | sed "s/ //g" | cut -d "S" -f1`
	PRGNAM=exaile
	echo -ne "\033]2;${PRGNAM}_updater\007"
	EXTENSION=tar.gz
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	DOWNLOAD=https://github.com/exaile-dev/exaile/archive/$VERSION.$EXTENSION
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
# Fix manpage location.
sed -i -e 's|share/man|man|g' Makefile

make  || exit 1
PREFIX=/usr \
LIBINSTALLDIR=/lib${LIBDIRSUFFIX} \
make install DESTDIR=$PKG

# Eliminamos la restriccion root
sed -i '21,29d' $PKG/usr/lib/exaile/exaile.py
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del script
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales
