#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20151024
CATEGORIA="Editores de video"

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=HandBrake
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://handbrake.fr/downloads.php
	VERSION=`curl -s $WEB | grep Current | cut -d: -f2 | cut -d '<' -f-1 | sed "s/ //g"`
	EXTENSION=tar.bz2
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	DOWNLOAD=https://handbrake.fr/rotation.php?file=$SOURCES
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
if [ $ARCH = i486 ]; then
ARCH=i686
fi

SLKCFLAGS="$SLKCFLAGS -fno-aggressive-loop-optimizations"
saved_CFLAGS="$CFLAGS"
saved_CXXFLAGS="$CFLAGS"
export CFLAGS="$SLKCFLAGS"
export CXXFLAGS="$SLKCFLAGS"

set -e
  
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --disable-gtk-update-checks \
  --arch=$ARCH

cd build
  # Fix underlinking by configuring the gtk module first, then sed:
  make gtk.configure
  sed -i '/^LDFLAGS/s/$/ -ltheoraenc -ltheoradec/' gtk/src/Makefile
  make  || exit 1
  make install DESTDIR=$PKG
  cd $TMP/$PRGNAM-$VERSION

export CFLAGS="$saved_CFLAGS"
export CXXFLAGS="$saved_CXXFLAGS"
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura i686
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales
