#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20150921
CATEGORIA="Editores de video"

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=HandBrake
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=https://handbrake.fr/downloads.php
	VERSION=`curl -s $WEB | grep Current | cut -d: -f2 | cut -d '<' -f-1 | sed "s/ //g"`
	DOWNLOAD=https://handbrake.fr/rotation.php?file=$PRGNAM-$VERSION.tar.bz2
}

# Si el paquete no existe se descargara de internet
F_download(){
	if [ ! -f $PRGNAM-$VERSION.tar.bz2 ]; then
	echo 
	echo "$CYAN"Descargando sources de $PRGNAM-$VERSION"$CIERRE"
	sleep 1
	aria2c -x 3 $DOWNLOAD
	fi
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
if [ $ARCH = i486 ]; then
ARCH=i686
fi
echo 
echo "$VERDE"Descomprimiendo ..."$CIERRE"
sleep 1
rm -rf $PRGNAM-$VERSION
tar xvf $PRGNAM-$VERSION.tar.bz2
cd $PRGNAM-$VERSION
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

SLKCFLAGS="$SLKCFLAGS -fno-aggressive-loop-optimizations"
saved_CFLAGS="$CFLAGS"
saved_CXXFLAGS="$CFLAGS"
export CFLAGS="$SLKCFLAGS"
export CXXFLAGS="$SLKCFLAGS"

set -e
  
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --disable-gtk-update-checks \
  --arch=$ARCH

cd build
  # Fix underlinking by configuring the gtk module first, then sed:
  make gtk.configure
  sed -i '/^LDFLAGS/s/$/ -ltheoraenc -ltheoradec/' gtk/src/Makefile
  make  || exit 1
  make install DESTDIR=$PKG
  cd $TMP/$PRGNAM-$VERSION

export CFLAGS="$saved_CFLAGS"
export CXXFLAGS="$saved_CXXFLAGS"
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura i686
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
F_download
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales
