#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20151116
CATEGORIA=Grabacion

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=k3b
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=http://slackware.mirrors.tds.net/pub/slackware/slackware-current/slackware/kde/
	ARCHIVO=$(curl -s $WEB | grep $PRGNAM | grep -o -E 'href="([^"#]+)"' | cut -d'"' -f2 | grep -E *txz$)
	VERSION=$(echo $ARCHIVO | cut -d- -f2)
}

# Si el paquete no existe se descargara de internet
F_download(){
	if [ ! -f $ARCHIVO ]; then
	echo ""
	echo "$CYAN"Descargando sources de $PRGNAM-$VERSION"$CIERRE"
	sleep 1
	aria2c -x 3 $WEB/$ARCHIVO
	fi
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo ""
echo "$VERDE"Descomprimiendo ..."$CIERRE"
sleep 1
rm -rf $PRGNAM-$VERSION
txz2dir $TMP/$ARCHIVO $PKG
rm -Rf $PKG/var/log/packages/*

# Creamos configuracion basica
mkdir -p  $PKG/$HOME/.kde/share/config
echo "[General Options]
Allow overburning=false
Fifo buffer=4
Force unsafe operations=false
Last system check version=2.0.2
Lock Panels=true
Manual buffer size=false
Navigator breadcrumb mode=true
No cd eject=false
Show Document Header=true
Temp Dir=/tmp/kde-root/
burnfree=true
check system config=false

[TipOfDay]
RunOnStart=false

[main_window_settings]
Height 768=769
Width 1366=1367" > $PKG/$HOME/.kde/share/config/k3brc

rm -rf $PKG/usr/share/kde4/services/ServiceMenus/k3b_create_data_project*
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo1
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del script
f_versionInstalada
#Si no existe el fichero se descargara
F_download
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales