#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20160220
CATEGORIA="Editores de video"

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	WEB=http://lives-video.com/index.php?do=downloads
	VERSION=`curl -s $WEB | grep -a .tar.bz2 | cut -d - -f3 | cut -d t -f-1 | sed "s/.$//g" `
	PRGNAM=lives
	SRCNAM=LiVES
	echo -ne "\033]2;${PRGNAM}_updater\007"
	EXTENSION=tar.bz2
	SOURCES=$SRCNAM-$VERSION.$EXTENSION
	DOWNLOAD=http://lives-video.com/releases/$SOURCES
}

# Comprobar dependencias
F_dependencias(){
if [ $VERSION = "2.6.0" ]; then
FFMPEGVERSION=ffmpeg28
PKG_CONFIG_PATH="/usr/lib/ffmpeg2.8/pkgconfig"
else
FFMPEGVERSION=ffmpeg
fi
DEPENDENCIAS="$FFMPEGVERSION"
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 2

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --mandir=/usr/man \
  --build=$ARCH-slackware-linux \

make  || exit 1
mkdir -p $PKG/usr/bin
make install DESTDIR=$PKG

cd $PKG/usr/bin && rm -f lives && ln -s lives-exe lives
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
# Comprobar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales