#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20150503
CATEGORIA="Reproductores multimedia"

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	WEB=http://www.mixxx.org/download/
	VERSION=`curl -s ${WEB} | grep src.tar.gz |tail -1|cut -d "/" -f4| cut -d "-" -f2`
	PRGNAM=mixxx
	echo -ne "\033]2;${PRGNAM}_updater\007"
	DOWNLOAD=http://downloads.mixxx.org/${PRGNAM}-${VERSION}/${PRGNAM}-${VERSION}-src.tar.gz
}

# Si el paquete no existe se descargara de internet
F_download(){
	if [ ! -f ${PRGNAM}-${VERSION}-src.tar.gz ]; then
	echo ""
	echo "$CYAN"Descargando sources de ${PRGNAM}-${VERSION}"$CIERRE"
	sleep 3
	aria2c -x 3 $DOWNLOAD
	fi
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo ""
echo "$VERDE"Descomprimiendo ..."$CIERRE"
sleep 3
rm -rf ${PRGNAM}-${VERSION}
tar xvf ${PRGNAM}-${VERSION}-src.tar.gz
cd ${PRGNAM}-${VERSION}
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
 -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
 
# Compilamos paquete
echo ""
echo "$VERDE"Compilando ..."$CIERRE"
sleep 3

CFLAGS="$SLKCFLAGS" \
QTDIR=/usr/lib$LIBDIRSUFFIX/qt \
scons \
  shoutcast=0 \
  prefix=/usr

QTDIR=/usr/lib$LIBDIRSUFFIX/qt \
scons \
  install_root=$PKG/usr \
  prefix=/usr \
  install

cd $PKG 
# Modificamos el desktop
echo "[Desktop Entry]
Name=Mixxx
GenericName=Digital DJ interface
Comment=A digital DJ interface
Exec=mixxx
Terminal=false
Icon=mixxx-icon
Type=Application
StartupNotify=true
Categories=AudioVideo;Audio;
" > $PKG/usr/share/applications/mixxx.desktop
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del script
f_versionInstalada
#Si no existe el fichero se descargara
F_download
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales
