#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20150906
CATEGORIA="Editores de audio"

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	WEB=http://sourceforge.net/projects/lmuse/files/
	VERSION=`curl -s $WEB | grep /latest | head -1| rev | cut -f 3- -d . | cut -f 1 -d - | rev`
	RAMA=`echo $VERSION | cut -c 1-3`
	PRGNAM=muse
	echo -ne "\033]2;${PRGNAM}_updater\007"
	DESCARGA=http://sourceforge.net/projects/lmuse/files/$PRGNAM-$RAMA/$PRGNAM-$VERSION.tar.gz
}

# Si el paquete no existe se descargara de internet
F_download(){
	if [ ! -f $PRGNAM-$VERSION.tar.gz ]; then
	echo 
	echo "$CYAN"Descargando sources de $PRGNAM-$VERSION"$CIERRE"
	sleep 1
	aria2c -x 3 $DESCARGA
	fi
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Descomprimiendo ..."$CIERRE"
sleep 1
rm -rf $PRGNAM-$VERSION
tar xvf $PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 -o -perm 511 \) \
 -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
 -exec chmod 644 {} \;

mkdir -p build
cd build
  cmake \
    -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
    -DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS" \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DLIB_SUFFIX=${LIBDIRSUFFIX} \
    -DENABLE_PYTHON:STRING="ON" \
    -DPYTHON_INCLUDE_DIR=/usr/include/python2.7 \
    -DPYTHON_LIBRARY=/usr/lib/libpython2.7.so \
    -DCMAKE_BUILD_TYPE=Release .. \
    -DCMAKE_ENABLE_VST_VESTIGE=1 \
    -DCMAKE_ENABLE_VST_NATIVE=1 \
    -DENABLE_PYTHON=1 \
    -DENABLE_FLUID=1 \
    -DENABLE_DSSI=1 \
    -DENABLE_LASH=1 \
    -DENABLE_OSC=1 ..
  make  || exit 1
  make install DESTDIR=$PKG
cd ..

# Arreglo para demonio jackd
BINARIO=`grep -r Exec $PKG/usr/share/applications/muse.desktop | cut -d '=' -f2`
sed -i "s/Exec=$BINARIO/Exec=muse_starter/g" $PKG/usr/share/applications/muse.desktop
echo "#!/bin/bash
setcap cap_ipc_lock,cap_sys_nice=ep /usr/bin/jackd
$BINARIO" > $PKG/usr/bin/muse_starter
chmod 777 $PKG/usr/bin/muse_starter
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
F_download
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales
