#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20150502
CATEGORIA="Reproductores streaming"

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	WEB=https://code.google.com/p/sopcast-player/downloads/list
	SP_AUTH_VERSION=`curl -s $WEB | grep sp-auth | head -1 | cut -d "/" -f 5 | cut -d '"' -f-1 | cut -d- -f 3 | cut -d "t" -f1 | sed "s/.$//g" | sed "s/ //g"`
	VERSION=`curl -s $WEB | sed "s/sp-auth-$SP_AUTH_VERSION.tar.gz//g" | grep .tar.gz | tail -1 | cut -d- -f 3 | cut -d "t" -f1 | sed "s/.$//g" | sed "s/ //g"`
	PRGNAM=sopcast-player
	echo -ne "\033]2;${PRGNAM}_updater\007"
	DESCARGA=https://sopcast-player.googlecode.com/files/sopcast-player-$VERSION.tar.gz
}

# Comprobar dependencias ( si hay mas de una se separan por un espacio )
F_dependencias(){
echo "$ROSA"Comprobando dependencias ..."$CIERRE"
echo ""
DEPENDENCIAS="sopcast vlc"
CONTINUAR=0

echo "$CYAN"Dependencias de este paquete:""
echo ""
sleep 3

for X in $DEPENDENCIAS; do
	
	if hash $X 2>/dev/null ; then
		echo ""$AMARILLO"$X :$VERDE Instalada"$CIERRE""
	else
		echo ""$AMARILLO"$X :$ROJO  No instalada"$CIERRE""
		CONTINUAR=1
	fi
done

if [ $CONTINUAR -eq 1 ]; then
	echo ""
	echo ""$ROJO"No se cumplen los requisitos no se puede continuar"$CIERRE""
	echo ""
	sleep 3
	exit 1
else
	echo ""
	echo ""$VERDE"Bien ..podemos continuar"$CIERRE""
	echo ""
fi
}

# Si el paquete no existe se descargara de internet
F_download(){
	if [ ! -f sopcast-player-$VERSION.tar.gz ]; then
	echo ""
	echo "$CYAN"Descargando sources de $PRGNAM-$VERSION"$CIERRE"
	sleep 3
	aria2c -x 3 $DESCARGA
	fi
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo ""
echo "$VERDE"Descomprimiendo ..."$CIERRE"
sleep 3
rm -rf $PRGNAM
tar xvf $PRGNAM-$VERSION.tar.gz
cd $PRGNAM
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 -o -perm 511 \) \
 -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
 -exec chmod 644 {} \;
  
# Compilamos paquete
echo ""
echo "$VERDE"Compilando ..."$CIERRE"
sleep 3
make -j$NUCLEOS PREFIX=/usr 
make install DESTDIR=$PKG
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
# Comprobar dependencias ( si hay mas de una se separan por un espacio )
F_dependencias
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del script
f_versionInstalada
#Si no existe el fichero se descargara
F_download
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales
