#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20151116
CATEGORIA="Reproductores streaming"

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	WEB=https://code.google.com/p/sopcast-player/downloads/list
	VERSION=`curl -s $WEB | grep sp-auth | head -1 | cut -d "/" -f 5 | cut -d '"' -f-1 | cut -d- -f 3 | cut -d "t" -f1 | sed "s/.$//g" | sed "s/ //g"`
	PRGNAM=sopcast
	SRCNAM=sp-auth
	echo -ne "\033]2;${PRGNAM}_updater\007"
	EXTENSION=tar.gz
	SOURCES=$SRCNAM-$VERSION.$EXTENSION
	DOWNLOAD=https://sopcast-player.googlecode.com/files/$SOURCES
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo ""
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1
make  install DESTDIR=$PKG
  
( cd $PKG/usr/bin ; ln -sf sp-sc sopcast )
rm -rf $PKG/usr/share
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del script
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales