#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20151005
CATEGORIA="Reproductores streaming"

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=sopcast-player
	WEB=https://code.google.com/p/$PRGNAM/downloads/list
	SP_AUTH_VERSION=`curl -s $WEB | grep sp-auth | head -1 | cut -d "/" -f 5 | cut -d '"' -f-1 | cut -d- -f 3 | cut -d "t" -f1 | sed "s/.$//g" | sed "s/ //g"`
	VERSION=`curl -s $WEB | sed "s/sp-auth-$SP_AUTH_VERSION.tar.gz//g" | grep .tar.gz | tail -1 | cut -d- -f 3 | cut -d "t" -f1 | sed "s/.$//g" | sed "s/ //g"`
	echo -ne "\033]2;${PRGNAM}_updater\007"
	EXTENSION=tar.gz
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	DOWNLOAD=https://$PRGNAM.googlecode.com/files/$SOURCES
}

# Comprobar dependencias ( si hay mas de una se separan por un espacio )
F_dependencias(){
echo "$ROSA"Comprobando dependencias ..."$CIERRE"
echo ""
DEPENDENCIAS="sopcast vlc"
CONTINUAR=0

echo "$CYAN"Dependencias de este paquete:""
echo ""
sleep 3

for X in $DEPENDENCIAS; do
	
	if hash $X 2>/dev/null ; then
		echo ""$AMARILLO"$X :$VERDE Instalada"$CIERRE""
	else
		echo ""$AMARILLO"$X :$ROJO  No instalada"$CIERRE""
		CONTINUAR=1
	fi
done

if [ $CONTINUAR -eq 1 ]; then
	echo ""
	echo ""$ROJO"No se cumplen los requisitos no se puede continuar"$CIERRE""
	echo ""
	sleep 3
	exit 1
else
	echo ""
	echo ""$VERDE"Bien ..podemos continuar"$CIERRE""
	echo ""
fi
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo ""
echo "$VERDE"Compilando ..."$CIERRE"
sleep 3
make  PREFIX=/usr || exit 1
make install DESTDIR=$PKG
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
# Comprobar dependencias ( si hay mas de una se separan por un espacio )
F_dependencias
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del script
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_compilar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales
