#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20160715
CATEGORIA="Reproductores streaming"

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=spotify
	SRCNAM=spotify-client
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=http://repository.spotify.com/pool/non-free/s/spotify-client
	if [ $ARCH = x86_64 ]; then
	DEBARCH=amd64
	else
	DEBARCH=i386
	fi
	VERSION=`curl -s $WEB/|grep $DEBARCH|tail -1|cut -d _ -f2|cut -d- -f-1`
	RAMA=`curl -s $WEB/|grep $DEBARCH|tail -1|cut -d _ -f2|cut -d- -f2`
	ARCHIVO=${SRCNAM}_${VERSION}-${RAMA}_${DEBARCH}.deb
	DOWNLOAD=$WEB/$ARCHIVO
}

# Si el paquete no existe se descargara de internet
F_download(){
	if [ ! -f $ARCHIVO ]; then
	echo ""
	echo "$CYAN"Descargando sources de $PRGNAM-$VERSION"$CIERRE"
	sleep 1
	aria2c -x 3 $DOWNLOAD
	fi
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $PKG
ar -p $TMP/$ARCHIVO data.tar.gz | tar zxv
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

## create our opt/ directory
mkdir -p $PKG/opt/$PRGNAM/

## move usr/ to opt/ to avoid
## collisions
mv usr/ $PKG/opt/$PRGNAM/

## rebuild some directories
mkdir -p $PKG/usr/{bin,doc}/
mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION

## we make our own launcher
cat <<EOT > $PKG/usr/bin/$PRGNAM
#!/bin/sh
/opt/$PRGNAM/usr/bin/$PRGNAM "\$@"
EOT

chmod 755 $PKG/usr/bin/$PRGNAM

## install all icon sizes, thanks to Dhaby
(
  cd $PKG/opt/$PRGNAM/usr/share/$PRGNAM/icons
  for IMG in $PRGNAM-linux-*.png; do
    SIZE=${IMG##*$PRGNAM-linux-}
    DIRNAME=${SIZE%.png}x${SIZE%.png}
    install -D $IMG $PKG/usr/share/icons/hicolor/$DIRNAME/apps/$SRCNAM.png
  done
)

mkdir -p $PKG/usr/share/applications/
mv $PKG/opt/$PRGNAM/usr/share/$PRGNAM/$PRGNAM.desktop \
  $PKG/usr/share/applications/$SRCNAM.desktop
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
# Definimos arquitectura del sitema
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del script
f_versionInstalada
#Si no existe el fichero se descargara
F_download
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales