#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20160422
CATEGORIA="Reproductores multimedia"

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=vlc
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=http://download.videolan.org
	VERSION=$(curl -s $WEB/$PRGNAM/ | grep -Po 'href="\K.*(?=")' | sed 's/\///g' | sort -g | tail -1)
	EXTENSION=tar.xz
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	DOWNLOAD=$WEB/$PRGNAM/$VERSION/$SOURCES
}

# Comprobar dependencias
F_dependencias(){
DEPENDENCIAS="ffmpeg libass libdc1394 libdvbpsi libmpeg2 libupnp portaudio twolame opus gsm opencv libkate faac libdca libmatroska libshout speex jack2 zvbi faad2 libavc1394 libmodplug musepack-tools vcdimager dirac gnome-vfs live555 rtmpdump lua libdvdcss fluidsynth schroedinger chromaprint x264 x265 libbluray"
f_dependencias
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Configurando ..."$CIERRE"
sleep 1

if [ $VERSION = "2.2.2" ]; then
echo "LS0tIG1vZHVsZXMvdmlzdWFsaXphdGlvbi9wcm9qZWN0bS5jcHAub3JpZwkyMDEzLTA5LTEzIDAx
OjE4OjM0LjAwMDAwMDAwMCArMTAwMAorKysgbW9kdWxlcy92aXN1YWxpemF0aW9uL3Byb2plY3Rt
LmNwcAkyMDE0LTA5LTA0IDE0OjUzOjIxLjUxMDI0MjAzNiArMTAwMApAQCAtNzksOCArNzksOCBA
QAogIyBkZWZpbmUgRk9OVF9QQVRIX01FTlUgIkM6XFxXSU5ET1dTXFxGb250c1xcYXJpYWwudHRm
IgogIyBkZWZpbmUgUFJFU0VUX1BBVEggICAgTlVMTAogI2Vsc2UKLSMgZGVmaW5lIEZPTlRfUEFU
SCAgICAgICIvdXNyL3NoYXJlL2ZvbnRzL3RydWV0eXBlL3R0Zi1kZWphdnUvRGVqYVZ1U2Fucy50
dGYiCi0jIGRlZmluZSBGT05UX1BBVEhfTUVOVSAiL3Vzci9zaGFyZS9mb250cy90cnVldHlwZS90
dGYtZGVqYXZ1L0RlamFWdVNhbnNNb25vLnR0ZiIKKyMgZGVmaW5lIEZPTlRfUEFUSCAgICAgICIv
dXNyL3NoYXJlL2ZvbnRzL1RURi9EZWphVnVTYW5zLnR0ZiIKKyMgZGVmaW5lIEZPTlRfUEFUSF9N
RU5VICIvdXNyL3NoYXJlL2ZvbnRzL1RURi9EZWphVnVTYW5zTW9uby50dGYiCiAjIGRlZmluZSBQ
UkVTRVRfUEFUSCAgICAiL3Vzci9zaGFyZS9wcm9qZWN0TS9wcmVzZXRzIgogI2VuZGlmCiAK
" | base64 -d > $TMP/patch-projectM-fontpath.diff

patch -p0 < $TMP/patch-projectM-fontpath.diff

echo "LS0tIGJpbi9NYWtlZmlsZS5hbS5vcmlnCTIwMTUtMDYtMDMgMTA6NDk6NTEuMjY2MjgyNzM2ICsx
MDAwCisrKyBiaW4vTWFrZWZpbGUuYW0JMjAxNS0wNi0wMyAxMDo1MDoyMC40NjkyODIzMTAgKzEw
MDAKQEAgLTcyLDYgKzcyLDEwIEBACiB2bGNfY2FjaGVfZ2VuX0RFUEVOREVOQ0lFUyA9IHZsY193
aW4zMl9yYy4kKE9CSkVYVCkKIGVuZGlmCiAKK2lmIEhBVkVfR09CSkVDVAordmxjX2NhY2hlX2dl
bl9MREFERCArPSAkKEdPQkpFQ1RfTElCUykKK2VuZGlmCisKICMKICMgUGx1Zy1pbnMgY2FjaGUK
ICMKLS0tIGNvbmZpZ3VyZS5hYy5vcmlnCTIwMTUtMDYtMDMgMTA6NTM6MjIuMjk5Mjc5NjU3ICsx
MDAwCisrKyBjb25maWd1cmUuYWMJMjAxNS0wNi0wMyAwOTo0NDozMy4zMzgzMzk4ODkgKzEwMDAK
QEAgLTc2Miw2ICs3NjIsMTIgQEAKICAgICBdKQogXSkKIAorZG5sCitkbmwgQ2hlY2sgZm9yIGdv
YmplY3QKK2RubAoraGF2ZV9nb2JqZWN0PSJubyIKK1BLR19DSEVDS19NT0RVTEVTKFtHT0JKRUNU
XSwgW2dvYmplY3QtMi4wXSwgWyBoYXZlX2dvYmplY3Q9InllcyIgXSkKK0FNX0NPTkRJVElPTkFM
KEhBVkVfR09CSkVDVCwgWyB0ZXN0ICIke2hhdmVfZ29iamVjdH0iID0gInllcyIgXSkKIAogZG5s
CiBkbmwgQ2hlY2sgZm9yIHpsaWIuaCBhbmQgLWx6IGFsb25nIHdpdGggc3lzdGVtIC1sbWluaXpp
cCBpZiBhdmFpbGFibGUK" | base64 -d > $TMP/patch_vlc_cache_gen.diff

patch -p0 < $TMP/patch_vlc_cache_gen.diff

echo "LS0tIGEvY29uZmlndXJlLmFjDQorKysgYi9jb25maWd1cmUuYWMNCkBAIC0zNzU0LDkgKzM3NTQs
OSBAQA0KICAgICAgICAgICBBQ19NU0dfV0FSTihbTm90IGJ1aWxkaW5nIFF0IEludGVyZmFjZSB3
aXRoIFgxMSBoZWxwZXJzLl0pDQogICAgICAgXSkNCiANCi0gICAgICBQS0dfQ0hFQ0tfRVhJU1RT
KFtRdDVDb3JlID49IDUuNS4wIFF0NUNvcmUgPCA1LjYuMF0sIFsNCi0gICAgICAgIEFDX01TR19F
UlJPUihbIllvdSBjYW5ub3QgYnVpbGQgVkxDIHdpdGggUXQtNS41LjAuIFlvdSBuZWVkIHRvIGJh
Y2twb3J0IEk3OGVmMjk5NzUxODFlZTIyNDI5YzliZDRiMTFkOTZkOWU2OGI3YTljIl0pDQotICAg
ICAgXSkNCisjICAgICAgUEtHX0NIRUNLX0VYSVNUUyhbUXQ1Q29yZSA+PSA1LjUuMCBRdDVDb3Jl
IDwgNS42LjBdLCBbDQorIyAgICAgICAgQUNfTVNHX0VSUk9SKFsiWW91IGNhbm5vdCBidWlsZCBW
TEMgd2l0aCBRdC01LjUuMC4gWW91IG5lZWQgdG8gYmFja3BvcnQgI0k3OGVmMjk5NzUxODFlZTIy
NDI5YzliZDRiMTFkOTZkOWU2OGI3YTljIl0pDQorIyAgICAgIF0pDQogDQogICAgICAgUVRfUEFU
SD0iJChldmFsICRQS0dfQ09ORklHIC0tdmFyaWFibGU9ZXhlY19wcmVmaXggUXQ1Q29yZSkiDQog
ICAgICAgUVRfSE9TVF9QQVRIPSIkKGV2YWwgJFBLR19DT05GSUcgLS12YXJpYWJsZT1ob3N0X2Jp
bnMgUXQ1Q29yZSkiDQo=" | base64 -d > $TMP/native_widgets.patch

patch -p1 < $TMP/native_widgets.patch
fi

autoreconf -f

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
LDFLAGS="$SLKLDFLAGS" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --sysconfdir=/etc \
  --mandir=/usr/man \
  --enable-run-as-root \
  --docdir=/usr/doc/vlc-$VERSION \
  --localstatedir=/var \
  --enable-merge-ffmpeg \
  --with-kde-solid=no \
  --build=$ARCH-slackware-linux
  
echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1
make  || exit 1
make install DESTDIR=$PKG || exit 1

mkdir -p $PKG/$(cd /usr/share/vim/vim*/syntax ; pwd)
cp extras/analyser/vlc.vim $PKG/$(cd /usr/share/vim/vim*/syntax ; pwd)/
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del script
f_versionInstalada
# Comprobar dependencias
F_dependencias
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales
