#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20160119
CATEGORIA="Reproductores multimedia"

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=vlc
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=http://download.videolan.org
	VERSION=$(curl -s $WEB/$PRGNAM/ | grep -Po 'href="\K.*(?=")' | sed 's/\///g' | sort -g | tail -1)
	EXTENSION=tar.xz
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	DOWNLOAD=$WEB/$PRGNAM/$VERSION/$SOURCES
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
# Configuramos el paquete 
echo "$VERDE"
echo "Configurando paquete$ROJO $PRGNAM-$VERSION $CIERRE..."
sleep 1

# Comprobamos version de opencv
OPENCV=$(ls /var/log/packages/*|grep opencv|cut -d- -f2|cut -c 1)
if [ $OPENCV = 3 ]; then
echo "ZGlmZiAtLWdpdCBhL21vZHVsZXMvdmlkZW9fZmlsdGVyL29wZW5jdl9leGFtcGxlLmNwcCBiL21v
ZHVsZXMvdmlkZW9fZmlsdGVyL29wZW5jdl9leGFtcGxlLmNwcAppbmRleCBhZTNhZjA1Li45OThm
Mjg2IDEwMDY0NAotLS0gYS9tb2R1bGVzL3ZpZGVvX2ZpbHRlci9vcGVuY3ZfZXhhbXBsZS5jcHAK
KysrIGIvbW9kdWxlcy92aWRlb19maWx0ZXIvb3BlbmN2X2V4YW1wbGUuY3BwCkBAIC00MSw2ICs0
MSw4IEBACiAKICNpbmNsdWRlIDxvcGVuY3YyL2NvcmUvY29yZV9jLmg+CiAjaW5jbHVkZSA8b3Bl
bmN2Mi9jb3JlL2NvcmUuaHBwPgorI2luY2x1ZGUgPG9wZW5jdjIvaW1ncHJvYy9pbWdwcm9jX2Mu
aD4KKyNpbmNsdWRlIDxvcGVuY3YyL2ltZ3Byb2MvaW1ncHJvYy5ocHA+CiAjaW5jbHVkZSA8b3Bl
bmN2Mi9vYmpkZXRlY3Qvb2JqZGV0ZWN0LmhwcD4KIAogLyoqKioqKioqKioqKioqKioqKioqKioq
KioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqCg==" |base64 -d > $TMP/opencv.patch
echo $VERDE
echo "Aplicando parche opencv3!..."
echo $AMARILLO
patch -p1 -i $TMP/opencv.patch || exit 1
echo $CIERRE
fi

# Aqui empezamos a configurar 
sh bootstrap

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \

./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --sysconfdir=/etc \
  --mandir=/usr/man \
  --enable-run-as-root \
  --docdir=/usr/doc/vlc-$VERSION \
  --localstatedir=/var \
  --enable-merge-ffmpeg \
  --with-kde-solid=no \
  --build=$ARCH-slackware-linux

make  || exit 1
make install DESTDIR=$PKG
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos version instalada del script
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales