#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20160403

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=ladspa_sdk
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=http://pkgs.fedoraproject.org/repo/pkgs/ladspa
	VERSION=1.13
	EXTENSION=tgz
	SRCNAM=${PRGNAM}_${VERSION}
	SOURCES=$SRCNAM.$EXTENSION
	DOWNLOAD=$WEB/$SOURCES/671be3e1021d0722cadc7fb27054628e/$SOURCES
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1

cd src
  make \
    CFLAGS="$SLKCFLAGS -I. -Wall -Werror -fPIC" \
    INSTALL_PLUGINS_DIR="/usr/lib${LIBDIRSUFFIX}/ladspa" \
    INSTALL_BINARY_DIR="/usr/bin"

  make install \
    INSTALL_PLUGINS_DIR="$PKG/usr/lib${LIBDIRSUFFIX}/ladspa" \
    INSTALL_BINARY_DIR="$PKG/usr/bin" \
    INSTALL_INCLUDE_DIR="$PKG/usr/include"
cd -

mkdir -p $PKG/etc/profile.d/
cat << EOF > $PKG/etc/profile.d/ladspa.csh
#!/bin/csh
setenv LADSPA_PATH /usr/lib${LIBDIRSUFFIX}/ladspa
EOF
cat << EOF > $PKG/etc/profile.d/ladspa.sh
#!/bin/sh
export LADSPA_PATH=/usr/lib${LIBDIRSUFFIX}/ladspa
EOF
chmod 0755 $PKG/etc/profile.d/*

# Cleanup files left in /tmp by make
rm -f /tmp/test.wav || true
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales