#!/bin/sh

# Script by www.seguridadwireless.net

SCRIPT_VERSION=20160403

############################################################
## Funciones comunes. Su nombre empieza por f_ ##
############################################################
f_variables(){
	. /opt/wifislax-updaters/Funciones/funciones_updater
}

############################################################
## Funciones propias del script. Su nombre empieza por F_ ##
############################################################
# Definicion de variables
F_variables() {
	PRGNAM=lv2
	echo -ne "\033]2;${PRGNAM}_updater\007"
	WEB=http://lv2plug.in/spec
	VERSION=1.12.0
	EXTENSION=tar.bz2
	SOURCES=$PRGNAM-$VERSION.$EXTENSION
	DOWNLOAD=$WEB/$SOURCES
}

# Descomprimimos el fichero descargado y compilamos
F_compilar(){
echo 
echo "$VERDE"Configurando ..."$CIERRE"
sleep 1

./waf configure \
  --prefix=/usr \
  --libdir=/usr/lib$LIBDIRSUFFIX \
  --lv2dir=/usr/lib$LIBDIRSUFFIX/lv2

echo 
echo "$VERDE"Compilando ..."$CIERRE"
sleep 1

./waf build
./waf install --destdir=$PKG

mkdir -p $PKG/etc/profile.d

cat <<EOF > $PKG/etc/profile.d/$PRGNAM.sh
#!/bin/sh
export LV2_PATH=/usr/lib$LIBDIRSUFFIX/lv2
EOF

cat <<EOF > $PKG/etc/profile.d/$PRGNAM.csh
#!/bin/csh
setenv LV2_PATH /usr/lib$LIBDIRSUFFIX/lv2
EOF

chmod 0755 $PKG/etc/profile.d/*
}

###################################
## BLOQUE PRINCIPAL DE EJECUCION ##
###################################
# Si se cierra el script inesperadamente, ejecutar la funcion de limpieza
trap f_exitmode SIGHUP SIGINT

#Inicializamos las variables globales
f_variables
#Asignamos o detectamos arquitectura
f_arquitectura
#Comprobamos conexion a Internet
f_comprobarConexion
#Inicializamos las variables del script
F_variables
#Creamos directorio de trabajo
f_directorioTemporal
#Mostramos el mensaje de presentacion
f_presentacion
#Comprobamos updates del script
f_comprobarUpdates
#Comprobamos version instalada del paquete
f_versionInstalada
#Si no existe el fichero se descargara
f_download
#Preparamos entorno
f_preparar
#Descomprimir fichero descargado y compilamos
F_compilar
#Hacemos strip sobre el paquete
f_strip
#Creamos xzm , instalamos y salimos
f_tareasFinales